#! /usr/bin/env node
/**
* ts2pas
* https://github.com/CWBudde/TS2Pas
*
* Copyright (c) 2016 Christian-W. Budde
* Licensed under the MIT license.
*/

var TObject={$ClassName:"TObject",$Parent:null,ClassName:function(s){return s.$ClassName},ClassType:function(s){return s},ClassParent:function(s){return s.$Parent},$Init:function(){},Create:function(s){return s},Destroy:function(s){for(var prop in s)if(s.hasOwnProperty(prop))delete s.prop},Destroy$:function(s){return s.ClassType.Destroy(s)},Free:function(s){if(s!==null)s.ClassType.Destroy(s)}}
function StrReplace(s,o,n){return o?s.replace(new RegExp(StrRegExp(o),"g"),n):s}
function StrRegExp(s){return s.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")}
var Exception={$ClassName:"Exception",$Parent:TObject,$Init:function(){var FMessage=""},Create:function(s,Msg){s.FMessage=Msg;return s}}
function stringRepeat(s,n){if(n<1)return'';var r='';while(n>0){if(n&1)r+=s;n>>=1,s+=s};return r};function DupeString(s,n){return stringRepeat(s,n)}
function $W(e){return e.ClassType?e:Exception.Create($New(Exception),e.constructor.name+", "+e.message)}
function $StrSet(s,i,v,z){if(i<1)throw Exception.Create($New(Exception),"Lower bound exceeded! Index "+i.toString()+z);if(i>s.length)throw Exception.Create($New(Exception),"Upper bound exceeded! Index "+i.toString()+z);return s.substring(0,i-1)+v+s.substring(i)}
function $New(c){var i={ClassType:c};c.$Init(i);return i}
function $Is(o,c){if(o===null)return false;return $Inh(o.ClassType,c)};function $Inh(s,c){if(s===null)return false;while((s)&&(s!==c))s=s.$Parent;return(s)?true:false};function $Extend(base,sub,props){function F(){};F.prototype=base.prototype;sub.prototype=new F();sub.prototype.constructor=sub;for(var n in props){if(props.hasOwnProperty(n)){sub.prototype[n]=props[n]}}}
function $AsIntf(o,i){if(o===null)return null;var r=o.ClassType.$Intf[i].map(function(e){return function(){var arg=Array.prototype.slice.call(arguments);arg.splice(0,0,o);return e.apply(o,arg)}});r.O=o;return r};function $As(o,c){if((o===null)||$Is(o,c))return o;throw Exception.Create($New(Exception),"Cannot cast instance of type \""+o.ClassType.$ClassName+"\" to class \""+c.$ClassName+"\"")}
function JError(){}
$Extend(Object,JError,{});function Wn(Ko){if(Ko==(Ko).split(".")[0])Ko+=".d.ts";dY.readFile(Ko,function(KH,bg){var Po="",NB=null;Po=bg.toString("utf8");NB=v.createSourceFile(Ko,Po,2,true);Ht(NB)})};function TG(sW,CW){if(sW==(sW).split(".")[0])sW+=".d.ts";dY.readFile(sW,function(c9,kx){var ND="",al=null,eL="";ND=kx.toString("utf8");al=VA.bl($New(VA));al.Name=(sW).split(".")[0];eL=VA.vr(al,ND);dY.writeFile(CW,eL,function(Zb){});al=null})};function d2(w9){TG(w9,(w9).split(".")[0]+".pas")};function Ht(Jb){zx(Jb)};function zx(HP){var R=undefined;switch(HP.kind){case 9:console.log(HP.text);break;case 69:console.log(HP.text);break;case 151:console.log(HP.text);break;case 122:console.log("declare");break;case 135:console.log(HP.left);break;default:console.log(HP.kind)}
v.forEachChild(HP,zx);return R};function Copy$vw(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$vw($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Copy$Lr(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$Lr($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Copy$NF(s,d){d.persistent=s.persistent;return d}
function Clone$NF($){return{persistent:$.persistent}}
function Copy$S7(s,d){d.curr=s.curr;d.prev=s.prev;return d}
function Clone$S7($){return{curr:$.curr,prev:$.prev}}
function Copy$ED(s,d){d.curr=s.curr;d.prev=s.prev;return d}
function Clone$ED($){return{curr:$.curr,prev:$.prev}}
function Copy$m1(s,d){d.persistent=s.persistent;d.interval=s.interval;return d}
function Clone$m1($){return{persistent:$.persistent,interval:$.interval}}
function Copy$fl(s,d){d.encoding=s.encoding;d.flag=s.flag;return d}
function Clone$fl($){return{encoding:$.encoding,flag:$.flag}}
function Copy$Mn(s,d){d.encoding=s.encoding;d.flag=s.flag;return d}
function Clone$Mn($){return{encoding:$.encoding,flag:$.flag}}
function Copy$RU(s,d){d.flags=s.flags;d.encoding=s.encoding;d.string_=s.string_;return d}
function Clone$RU($){return{flags:$.flags,encoding:$.encoding,string_:$.string_}}
function Copy$Vf(s,d){d.bufferSize=s.bufferSize;d.encoding=s.encoding;d.fd=s.fd;d.mode=s.mode;d.flags=s.flags;return d}
function Clone$Vf($){return{bufferSize:$.bufferSize,encoding:$.encoding,fd:$.fd,mode:$.mode,flags:$.flags}}
function Copy$Dz(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$Dz($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Copy$Mb(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$Mb($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Pe(){var R=null;R=require("fs");return R};function lX(){var R=null;R=require("stream");return R};function WD(){var R=null;R=require("events");return R};var VA={$ClassName:"TTranslator",$Parent:TObject,$Init:function($){TObject.$Init($);$.NeedsSemicolon=false;$.Name="";$.ho=[];$.FO=[];$.dv=[];$.QE=[];$.wl=$.fp=null},QC:function(S){return S.wl.getTokenText()},Js:function(S){return S.wl.getToken()},Dy:function(S,LJ){if(!(S.wl.isIdentifier()||LJ.indexOf(VA.Js(S))>=0))VA.yI(S,0)},e1:function(S,wZ){if(!(wZ.indexOf(VA.Js(S))>=0))VA.yI(S,0)},th:function(S,IQ){if(VA.Js(S)!=IQ)VA.yI(S,IQ)},UR:function(S){var R="";var vZ=0;var wD=null,Jx=0;var y8=null,Kq=0;var DO=null,Rf=0;var hI=null;var iz=[],tl=[],DX=[],Ob=[];R="unit "+dR(S.Name)+";"+"\r\n"+"\r\n";R+="interface"+"\r\n"+"\r\n";tl=S.FO;var $t1;for(vZ=0,$t1=tl.length;vZ<$t1;vZ++){wD=tl[vZ];R=R+Zu.EF$(wD)}
iz=S.QE;var $t2;for(Jx=0,$t2=iz.length;Jx<$t2;Jx++){y8=iz[Jx];R=R+Zu.EF$(y8)}
R+="type"+"\r\n";Zu.WU(Zu);Ob=S.dv;var $t3;for(Kq=0,$t3=Ob.length;Kq<$t3;Kq++){DO=Ob[Kq];R=R+Zu.EF$(DO)}
Zu.kk(Zu);R+="var"+"\r\n";Zu.WU(Zu);DX=S.ho;var $t4;for(Rf=0,$t4=DX.length;Rf<$t4;Rf++){hI=DX[Rf];R=R+Zu.EF$(hI)}
Zu.kk(Zu);return R},bl:function(S){S.NeedsSemicolon=false;return S},yI:function(S,MN){var ly=null,xe="";ly=v.getLineAndCharacterOfPosition(S.fp,S.wl.getTokenPos());xe=("Unknown token \""+VA.QC(S).toString()+"\" in this context ("+(ly.line+1).toString()+":"+(ly.character+1).toString()+")");if(MN>0)xe+=("; Expected ("+MN.toString()+")");console.trace("");throw Exception.Create($New(Exception),xe)},ae:function(S){var R=null;VA.Dy(S,[]);R=Zu.VI$($New(hl),$AsIntf(S,"E7"));R.Name=VA.QC(S);if(VA.YB(S,54,false))R.Type=VA.Yk(S);if(S.NeedsSemicolon)VA.e1(S,[23,24].slice());return R},lq:function(S,Q2){do{Q2.push(VA.ae(S));if(VA.Js(S)==23)break;if(VA.Js(S)!=24)break;if(!VA.hS(S,false))break}while(!(VA.Js(S)==23||(!S.wl.isIdentifier())||(!S.NeedsSemicolon)&&(!S.wl.isIdentifier())))},Cq:function(S){var R=null;var M8=0,pN=false;VA.Dy(S,[121,110,111,112,113].slice());if(VA.Js(S)==121)return VA.BS(S);M8=0;switch(VA.Js(S)){case 112:M8=0;VA.Ok(S,[113].slice(),true);break;case 111:M8=1;VA.Ok(S,[113].slice(),true);break;case 110:M8=2;VA.Ok(S,[113].slice(),true);break}
pN=VA.Js(S)==113;if(pN)VA.hS(S,true);R=VA.h9(S);$As(R,yK).IsStatic=pN;$As(R,yK).Visibility=M8;if(S.NeedsSemicolon)VA.e1(S,[23,16].slice());return R},S2:function(S){var R=null;var qk=[],qk=[121,110,111,112,113,16,23].slice();VA.th(S,73);R=Zu.VI$($New(TB),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);VA.pQ(S,[83,106,15].slice(),true);if(VA.Js(S)==83){VA.hS(S,true);R.Extends.push(VA.FA(S))}
if(VA.Js(S)==106){VA.hS(S,true);R.Implements.push(VA.YL(S));while(VA.Js(S)==24){VA.hS(S,true);R.Implements.push(VA.YL(S))}}
VA.th(S,15);VA.Ok(S,qk,false);while(VA.Js(S)!=16){R.Members.push(VA.Cq(S));if(VA.Js(S)==23)VA.Ok(S,qk,false)}
VA.th(S,16);return R},BS:function(S){var R=null;VA.th(S,121);VA.YB(S,17,true);R=Zu.VI$($New(x1),$AsIntf(S,"E7"));while(VA.hS(S,false)){R.ParameterList.push(VA.LN(S));VA.e1(S,[24,18,23].slice());if(VA.Js(S)==18)break}
VA.e1(S,[18,23].slice());if(VA.Js(S)!=23)VA.YB(S,23,true);return R},h1:function(S){var R=null;VA.th(S,122);R=Zu.VI$($New(mQ),$AsIntf(S,"E7"));VA.pQ(S,[102,108,74,87,73,81,125,126].slice(),true);switch(VA.Js(S)){case 102:case 108:case 74:R.Variables.push(VA.xJ(S));break;case 87:R.Functions.push(VA.Hj(S));break;case 73:R.Classes.push(VA.S2(S));break;case 81:R.Enums.push(VA.N5(S));break;case 125:R.Modules.push(VA.Hq(S));break;case 126:R.Namespaces.push(VA.xc(S));break}
return R},N5:function(S){var R=null;R=VA.mj(S);return R},Hj:function(S){var R=null;VA.th(S,87);R=Zu.VI$($New(SQ),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);R.CallSignature=VA.EE(S);if(S.NeedsSemicolon)VA.e1(S,[23].slice());return R},Hq:function(S){var R=null;var fw=[],fw=[82,102,108,74,132,87,73,107,81,125,89,16,23].slice();var fb=false,BY=null;VA.th(S,125);R=Zu.VI$($New(A8),$AsIntf(S,"E7"));VA.Ok(S,[9].slice(),true);R.IdentifierPath=VA.YL(S);VA.th(S,15);VA.pQ(S,fw,true);while(VA.Js(S)!=16){fb=VA.Js(S)==82;if(fb){VA.pQ(S,fw.concat([77,56]),true);if(VA.Js(S)==77){fb=false;VA.hS(S,false);VA.YB(S,23,false);VA.pQ(S,fw,true)}
if(VA.Js(S)==56){fb=false;VA.hS(S,false);VA.YB(S,23,false);VA.pQ(S,fw,true)}}
switch(VA.Js(S)){case 102:case 108:R.Variables.push(VA.xJ(S));break;case 74:VA.Ok(S,[81].slice(),false);if(VA.Js(S)==81){R.Enums.push(VA.N5(S))}else{BY=Zu.VI$($New(yl),$AsIntf(S,"E7"));BY.IsConst=true;VA.lq(S,BY.AmbientBindingList);R.Variables.push(BY)}
VA.pQ(S,fw,true);break;case 132:R.TypeAliases.push(VA.U8(S));VA.pQ(S,fw,true);break;case 87:R.Functions.push(VA.Hj(S));break;case 73:R.Classes.push(VA.OU(S));VA.pQ(S,fw,true);break;case 125:R.Modules.push(VA.Hq(S));VA.pQ(S,fw,true);break;case 107:R.Interfaces.push(VA.X4(S));VA.pQ(S,fw,true);break;case 89:VA.TN(S);if(!S.NeedsSemicolon)VA.pQ(S,fw,true);break;case 81:VA.mj(S);VA.pQ(S,fw,true);break}
if(VA.Js(S)==23)VA.pQ(S,fw,true)}
VA.th(S,16);return R},xc:function(S){var R=null;return R},h9:function(S){var R=null;var yr="";VA.Dy(S,[]);yr=VA.QC(S);VA.pQ(S,[54,17,23].slice(),true);if(VA.Js(S)==17){R=VA.Un(S)}else R=VA.jw(S);if(S.NeedsSemicolon)VA.Dy(S,[23,16,24].slice());return R},Un:function(S){var R=null;VA.th(S,17);R=Zu.VI$($New(Mm),$AsIntf(S,"E7"));R.CallSignature=VA.jf(S);VA.e1(S,[18,23].slice());if(VA.Js(S)!=23)VA.YB(S,23,true);return R},jw:function(S){var R=null;R=Zu.VI$($New(LZ),$AsIntf(S,"E7"));if(VA.Js(S)==54)R.Type=VA.qM(S);return R},xJ:function(S){var R=null;VA.e1(S,[102,108,74].slice());R=Zu.VI$($New(yl),$AsIntf(S,"E7"));R.IsConst=VA.Js(S)==74;VA.hS(S,true);VA.lq(S,R.AmbientBindingList);return R},tp:function(S){var R=null;R=Zu.VI$($New(Tt),$AsIntf(S,"E7"));R.Type=VA.OO(S);VA.e1(S,[23,16].slice());return R},EE:function(S){var R=null;R=Zu.VI$($New(Lb),$AsIntf(S,"E7"));VA.pQ(S,[17,25].slice(),true);if(VA.Js(S)==25){R.TypeParameters.push(VA.s4(S));VA.YB(S,17,true)}
VA.th(S,17);VA.Ok(S,[112,110,111,22,18].slice(),true);while(VA.Js(S)!=18){R.ParameterList.push(VA.bO(S));if(VA.Js(S)==24)VA.Ok(S,[22].slice(),false)}
VA.e1(S,[18].slice());VA.pQ(S,[54,23].slice(),true);if(VA.Js(S)==54)R.Type=VA.qM(S);return R},jf:function(S){var R=null;VA.e1(S,[17,25].slice());R=Zu.VI$($New(Lb),$AsIntf(S,"E7"));if(VA.Js(S)==25){R.TypeParameters.push(VA.s4(S));VA.YB(S,17,true)}
VA.th(S,17);VA.Ok(S,[112,110,111,22,18].slice(),true);while(VA.Js(S)!=18){R.ParameterList.push(VA.bO(S));if(VA.Js(S)==24)VA.Ok(S,[22].slice(),false)}
VA.e1(S,[18].slice());VA.pQ(S,[54,23].slice(),true);if(VA.Js(S)==54)R.Type=VA.qM(S);return R},OU:function(S){var R=null;var lF=[],lF=[92,9,82,16,23].slice();var Xe=0,CD=false,fK=null;VA.th(S,73);R=Zu.VI$($New(PX),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);VA.pQ(S,[83,106,15].slice(),true);if(VA.Js(S)==83){VA.hS(S,true);R.Extends.push(VA.FA(S))}
if(VA.Js(S)==106){VA.hS(S,true);R.Implements.push(VA.YL(S));while(VA.Js(S)==24){VA.hS(S,true);R.Implements.push(VA.YL(S))}}
VA.th(S,15);VA.th(S,15);VA.Ok(S,lF,false);while(VA.Js(S)!=16){Xe=0;switch(VA.Js(S)){case 112:Xe=0;VA.Ok(S,[92].slice(),true);break;case 111:Xe=1;VA.Ok(S,[92].slice(),true);break;case 110:Xe=2;VA.Ok(S,[92].slice(),true);break}
CD=VA.Js(S)==113;if(CD)VA.Ok(S,[92,17].slice(),true);fK=VA.fA(S);R.Members.push(fK);if(VA.Js(S)==23)VA.Ok(S,lF,false)}
return R},fA:function(S){var R=null;var fX="",Ma=false;VA.Dy(S,[92,17,9,82].slice());if(VA.Js(S)==17){R=VA.tp(S)}else{fX=VA.QC(S);VA.pQ(S,[25,53,54,17].slice(),true);if(VA.Js(S)==25){R.TypeParameters.push(VA.s4(S));VA.pQ(S,[53,54,17].slice(),true)}
Ma=VA.Js(S)==53;if(Ma)VA.YB(S,54,true);switch(VA.Js(S)){case 54:R=VA.xy(S);$As(R,CC).Nullable=Ma;break;case 17:if((fX).toLowerCase()=="constructor"){R=VA.NP(S)}else R=VA.aK(S);break}
R.Name=fX}
if(S.NeedsSemicolon)VA.e1(S,[23,24,16].slice());return R},NP:function(S){var R=null;R=Zu.VI$($New(Nm),$AsIntf(S,"E7"));R.Type=VA.OO(S);if(S.NeedsSemicolon)VA.e1(S,[23,16].slice());return R},M7:function(S){var R=null;VA.th(S,92);R=Zu.VI$($New(Nm),$AsIntf(S,"E7"));if(VA.hS(S,false)){VA.YB(S,17,false)}
VA.th(S,17);VA.Ok(S,[112,110,111,22,18].slice(),true);while(VA.Js(S)!=18){R.ParameterList.push(VA.bO(S));if(VA.Js(S)==24)VA.Ok(S,[22].slice(),false)}
VA.th(S,18);VA.YB(S,54,true);R.Type=VA.Yk(S);return R},PQ:function(S){var R=null;VA.th(S,92);R=Zu.VI$($New(as),$AsIntf(S,"E7"));VA.YB(S,17,true);while(VA.Ok(S,[22].slice(),false)){R.ParameterList.push(VA.LN(S));VA.e1(S,[24,18,23].slice());if(VA.Js(S)==18)break}
VA.e1(S,[18,23].slice());if(VA.pQ(S,[54,34].slice(),false))R.ResultType=VA.qM(S);return R},cm:function(S){while(VA.pQ(S,[82,122,107,125,89,1].slice(),true)){{var $t5=VA.Js(S);if($t5==82){continue}
else if($t5==122){S.ho.push(VA.h1(S))}
else if($t5==107){S.dv.push(VA.X4(S))}
else if($t5==125){S.QE.push(VA.Ar(S))}
else if($t5==89){S.FO.push(VA.TN(S))}
else if($t5==1){break}}}},mj:function(S){var R=null;VA.th(S,81);R=Zu.VI$($New(f7),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);VA.YB(S,15,true);VA.hS(S,true);do{R.Items.push(VA.xm(S))}while(!(!VA.hS(S,false)));VA.th(S,16);return R},xm:function(S){var R=null;VA.Dy(S,[]);R=Zu.VI$($New(Kw),$AsIntf(S,"E7"));R.Name=VA.QC(S);if(VA.YB(S,56,false)){VA.YB(S,8,true);R.Value=VA.QC(S);VA.nq(S)}
VA.th(S,24);return R},JN:function(S){var R=null;VA.th(S,82);R=Zu.VI$($New(Ex),$AsIntf(S,"E7"));VA.Ok(S,[77].slice(),true);R.RL=VA.Js(S)==82||(VA.QC(S)).toLowerCase()=="default";if(R.RL)VA.hS(S,true);R.Name=VA.QC(S);VA.YB(S,23,true);return R},xy:function(S){var R=null;R=Zu.VI$($New(CC),$AsIntf(S,"E7"));R.Type=VA.qM(S);if(S.NeedsSemicolon)VA.Dy(S,[23,16,24].slice());return R},kr:function(S){var R=null;VA.th(S,87);R=Zu.VI$($New(wv),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);VA.YB(S,17,true);R.Type=VA.OO(S);return R},LN:function(S){var R=null;var FC=false;VA.Dy(S,[22].slice());FC=VA.Js(S)==22;if(FC)VA.hS(S,true);R=Zu.VI$($New(dg),$AsIntf(S,"E7"));R.Name=VA.QC(S);VA.pQ(S,[53,54,18].slice(),true);R.IsOptional=VA.Js(S)==53;if(R.IsOptional)VA.pQ(S,[54].slice(),true);if(VA.Js(S)==54)R.Type=VA.qM(S);return R},OO:function(S){var R=null;VA.th(S,17);R=Zu.VI$($New(tk),$AsIntf(S,"E7"));while(VA.Ok(S,[22].slice(),false)){R.ParameterList.push(VA.LN(S));VA.e1(S,[24,18,23].slice());if(VA.Js(S)==18)break}
VA.e1(S,[18,23].slice());if(VA.pQ(S,[54,34].slice(),false))R.ResultType=VA.qM(S);return R},Ok:function(S,y6,k5){var R=false;VA.nq(S);R=S.wl.isIdentifier()||y6.indexOf(VA.Js(S))>=0;if((!R)&&k5)VA.yI(S,0);return R},hS:function(S,Hh){var R=false;VA.nq(S);R=S.wl.isIdentifier();if((!R)&&Hh)VA.yI(S,69);return R},YL:function(S){var R="";VA.Dy(S,[9].slice());R=VA.QC(S);while(VA.YB(S,21,false)){VA.hS(S,true);R+="."+VA.QC(S)}
return R},TN:function(S){var R=null;VA.th(S,89);R=Zu.VI$($New(oI),$AsIntf(S,"E7"));VA.Ok(S,[37,9].slice(),true);switch(VA.Js(S)){case 37:R.Name="*";VA.YB(S,116,true);VA.hS(S,true);VA.YB(S,133,true);VA.YB(S,9,true);break;case 9:R.Name=S.wl.getTokenValue();break;default:R.Name=VA.QC(S);VA.YB(S,56,true);VA.hS(S,true)}
VA.YB(S,23,true);return R},Kr:function(S){var R=null;VA.th(S,19);R=Zu.VI$($New(rL),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);VA.YB(S,54,true);VA.pQ(S,[130,128].slice(),true);R.IsStringIndex=VA.Js(S)==130;VA.YB(S,20,true);VA.YB(S,54,true);R.Type=VA.Yk(S);return R},X4:function(S){var R=null;VA.th(S,107);R=Zu.VI$($New(hm),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);VA.pQ(S,[25,83,15].slice(),true);if(VA.Js(S)==25){R.TypeParameters.push(VA.s4(S));VA.pQ(S,[83,15].slice(),true)}
if(VA.Js(S)==83){VA.hS(S,true);R.Extends.push(VA.FA(S));while(VA.Js(S)==24){VA.hS(S,true);R.Extends.push(VA.FA(S))}}
VA.th(S,15);R.Type=VA.va(S);VA.th(S,16);return R},aK:function(S){var R=null;R=Zu.VI$($New(DR),$AsIntf(S,"E7"));R.Type=VA.OO(S);if(S.NeedsSemicolon)VA.e1(S,[23,16].slice());return R},Ar:function(S){var R=null;var uT=[],uT=[73,82,81,89,125,87,107,102,23,16].slice();VA.th(S,125);R=Zu.VI$($New(xd),$AsIntf(S,"E7"));VA.Ok(S,[9].slice(),true);R.Name=VA.YL(S);VA.th(S,15);VA.pQ(S,uT,true);while(VA.Js(S)!=16){switch(VA.Js(S)){case 73:R.Classes.push(VA.OU(S));break;case 82:R.Exports.push(VA.JN(S));break;case 81:VA.mj(S);break;case 87:R.Functions.push(VA.kr(S));break;case 89:VA.TN(S);break;case 125:R.Modules.push(VA.Ar(S));break;case 107:R.Interfaces.push(VA.X4(S));break;case 102:R.Variables.push(VA.M1(S));break}
VA.pQ(S,uT,true)}
VA.th(S,16);return R},va:function(S){var R=null;var C1=[],C1=[9,8,92,17,78,19,16].slice();VA.th(S,15);R=Zu.VI$($New(rx),$AsIntf(S,"E7"));VA.Ok(S,C1,true);while(VA.Js(S)!=16){R.Members.push(VA.Sx(S));if(([23,24].indexOf(VA.Js(S))>=0))VA.Ok(S,C1,true)}
VA.th(S,16);return R},bO:function(S){var R=null;VA.Dy(S,[112,110,111,22].slice());R=Zu.VI$($New(s5),$AsIntf(S,"E7"));R.Name=VA.QC(S);R.IsRest=VA.Js(S)==22;if(R.IsRest){VA.hS(S,true);R.Name=VA.QC(S);if(VA.YB(S,54,false))R.Type=VA.Yk(S);VA.th(S,18);return R}
VA.Dy(S,[112,110,111].slice());switch(VA.Js(S)){case 112:R.AccessibilityModifier=0;VA.hS(S,false);break;case 110:R.AccessibilityModifier=1;VA.hS(S,false);break;case 111:R.AccessibilityModifier=2;VA.hS(S,false);break}
VA.Dy(S,[]);VA.pQ(S,[53,54,56,24,18].slice(),true);R.IsOptional=VA.Js(S)==53;if(R.IsOptional)VA.pQ(S,[54,56,24,18].slice(),true);if(VA.Js(S)==54)R.Type=VA.qM(S);VA.e1(S,[56,24,18].slice());if(VA.Js(S)==56){VA.hS(S,true);R.DefaultValue=VA.QC(S)}
VA.e1(S,[24,18].slice());return R},iD:function(S){var R=null;var vC=[],vC=[69,9,117,128,130,120,103,101,15,17].slice();var M6=null;VA.e1(S,vC);switch(VA.Js(S)){case 17:R=VA.qM(S);VA.th(S,18);VA.nq(S);break;case 69:R=t1.Ip($New(t1),$AsIntf(S,"E7"),VA.YL(S));if(VA.Js(S)==25){$As(R,t1).Arguments.push(VA.mT(S));VA.nq(S)}
break;case 9:R=t1.Ip($New(t1),$AsIntf(S,"E7"),S.wl.getTokenValue());VA.nq(S);break;case 117:R=Zu.VI$($New(aD),$AsIntf(S,"E7"));VA.nq(S);break;case 128:R=Zu.VI$($New(s9),$AsIntf(S,"E7"));VA.nq(S);break;case 103:R=null;VA.nq(S);break;case 101:R=Zu.VI$($New(Yb),$AsIntf(S,"E7"));$As(R,Yb).Type=VA.qM(S);break;case 130:R=Zu.VI$($New(Wc),$AsIntf(S,"E7"));VA.nq(S);break;case 120:R=Zu.VI$($New(uj),$AsIntf(S,"E7"));VA.nq(S);break;case 15:R=VA.va(S);VA.nq(S);break}
while(VA.Js(S)==19){M6=R;R=Zu.VI$($New(eq),$AsIntf(S,"E7"));$As(R,eq).Type=M6;VA.YB(S,20,true);VA.nq(S)}
return R},pQ:function(S,gZ,xh){var R=false;R=gZ.indexOf(VA.nq(S))>=0;if((!R)&&xh)VA.yI(S,0);return R},YB:function(S,qJ,nM){var R=false;R=VA.nq(S)==qJ;if((!R)&&nM)VA.yI(S,qJ);return R},nq:function(S){var R=0;R=S.wl.scan();return R},qM:function(S){var R=null;var w4=[],w4=[69,9,117,128,130,120,103,101,92,15,17].slice();var x8=null;VA.pQ(S,w4,true);if(VA.Js(S)==17)return VA.OO(S);if(VA.Js(S)==92)return VA.PQ(S);R=VA.iD(S);while(VA.Js(S)==47){if(!$Is(R,YS)){x8=R;R=Zu.VI$($New(YS),$AsIntf(S,"E7"));$As(R,YS).Types.push(x8)}
VA.pQ(S,w4,true);$As(R,YS).Types.push(VA.iD(S))}
return R},U8:function(S){var R=null;VA.th(S,132);R=Zu.VI$($New(IM),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);VA.pQ(S,[25,56].slice(),true);if(VA.Js(S)==25){R.TypeParameters.push(VA.s4(S));VA.YB(S,56,true)}
R.Type=VA.qM(S);VA.th(S,23);return R},Yk:function(S){var R=null;VA.th(S,54);R=VA.qM(S);return R},mT:function(S){var R=null;VA.th(S,25);R=Zu.VI$($New(NO),$AsIntf(S,"E7"));R.Type=VA.qM(S);VA.th(S,27);return R},Sx:function(S){var R=null;var pv="",md=false;VA.Dy(S,[9,8,110,92,78,17,19].slice());if(VA.Js(S)==92)return VA.M7(S);if(VA.Js(S)==17)return VA.tp(S);if(VA.Js(S)==19)return VA.Kr(S);if(S.wl.isIdentifier()||([9,8,78].indexOf(S.wl.getToken())>=0)){pv=VA.QC(S);VA.pQ(S,[25,53,54,17].slice(),true);if(VA.Js(S)==25){R.TypeArguments.push(VA.mT(S));VA.pQ(S,[53,54,17].slice(),true)}
md=VA.Js(S)==53;if(md)VA.pQ(S,[54,17].slice(),true);switch(VA.Js(S)){case 54:R=VA.xy(S);$As(R,CC).Nullable=md;break;case 17:R=VA.aK(S);break}
R.Name=pv}
return R},s4:function(S){var R=null;VA.th(S,25);R=Zu.VI$($New(LU),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);VA.pQ(S,[83,27].slice(),true);if(VA.Js(S)==83){R.ExtendsType=VA.qM(S);VA.th(S,27)}
return R},FA:function(S){var R=null;VA.Dy(S,[]);R=Zu.VI$($New(ao),$AsIntf(S,"E7"));R.Name=VA.YL(S);if(VA.Js(S)==25){R.Arguments.push(VA.mT(S));VA.nq(S)}
return R},M1:function(S){var R=null;VA.th(S,102);R=Zu.VI$($New(aL),$AsIntf(S,"E7"));VA.hS(S,true);R.Name=VA.QC(S);VA.YB(S,54,true);R.Type=VA.qM(S);return R},vr:function(S,Wg){var R="";S.wl=v.createScanner(0,true,0,Wg);S.fp=v.createSourceFile("main",Wg,0);try{VA.cm$(S)}catch($e){var a6=$W($e);console.error(a6.FMessage)}
R=VA.UR$(S);return R},Destroy:TObject.Destroy,UR$:function($){return $.ClassType.UR($)},cm$:function($){return $.ClassType.cm($)}};VA.$Intf={E7:[]}
function dR(I6){var R="";var BL=[];if(I6.length==0)return"Unknown";BL=(I6).split("\\");R=BL[(BL.length-1)];BL=(I6).split("\/");R=BL[(BL.length-1)];R=StrReplace(R,"-","_");R=$StrSet(R,1,(R.charAt(0)).toUpperCase());return R};var wb=["Warning","Error","Message"];function Copy$l(s,d){d.k=s.k;d.N=s.N;return d}
function Clone$l($){return{k:$.k,N:$.N}}
var p1=["vPublic","vProtected","vPrivate"];var Zu={$ClassName:"TCustomDeclaration",$Parent:TObject,$Init:function($){TObject.$Init($);$.US=null},WU:function(S){++BN},VI:function(S,kc){S.US=kc;return S},kk:function(S){--BN},b2:function(S){var R="";R=DupeString("  ",BN);return R},Destroy:TObject.Destroy,VI$:function($){return $.ClassType.VI.apply($.ClassType,arguments)},EF$:function($){return $.ClassType.EF($)}};var Y8={$ClassName:"TCustomType",$Parent:Zu,$Init:function($){Zu.$Init($)},Destroy:TObject.Destroy,VI:Zu.VI,EF:Zu.EF};var Zo={$ClassName:"TCustomNamedType",$Parent:Y8,$Init:function($){Y8.$Init($)},EF:function(S){var R="";R="J"+Zo.QA$(S);return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)},QA$:function($){return $.ClassType.QA($)}};var ZD={$ClassName:"TPredefinedType",$Parent:Zo,$Init:function($){Zo.$Init($)},EF:function(S){var R="";R=Zo.QA$(S);return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)},QA:Zo.QA};var aD={$ClassName:"TVariantType",$Parent:ZD,$Init:function($){ZD.$Init($)},QA:function(S){var R="";R="Variant";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF:ZD.EF,QA$:function($){return $.ClassType.QA($)}};var IU={$ClassName:"TNamedDeclaration",$Parent:Zu,$Init:function($){Zu.$Init($);$.Name=""},Destroy:TObject.Destroy,VI:Zu.VI,EF:Zu.EF};var aL={$ClassName:"TVariableDeclaration",$Parent:IU,$Init:function($){IU.$Init($);$.Type=null},EF:function(S){var R="";console.log("not implemented: TVariableDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var YS={$ClassName:"TUnionType",$Parent:Y8,$Init:function($){Y8.$Init($);$.Types=[]},EF:function(S){var R="";var E1=0;R="Variant {";var $t6;for(E1=0,$t6=(S.Types.length-1);E1<$t6;E1++){R+=Zu.EF$(S.Types[E1])+" or "}
R+=Zu.EF$(S.Types[(S.Types.length-1)])+"}";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var ao={$ClassName:"TTypeReference",$Parent:Zu,$Init:function($){Zu.$Init($);$.Name="";$.Arguments=[]},EF:function(S){var R="";var s7=0;R="J"+S.Name;if(S.Arguments.length>0){R+=" {"+Zu.EF$(S.Arguments[0]);var $t7;for(s7=0+1,$t7=S.Arguments.length;s7<$t7;s7++){R+=", "+Zu.EF$(S.Arguments[s7])}
R+="} "}
return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var LU={$ClassName:"TTypeParameter",$Parent:Zu,$Init:function($){Zu.$Init($);$.Name="";$.ExtendsType=null},EF:function(S){var R="";R=S.Name;if(S.ExtendsType)R+=" extends "+Zu.EF$(S.ExtendsType);return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var Yb={$ClassName:"TTypeOfType",$Parent:Zo,$Init:function($){Zo.$Init($);$.Type=null},QA:function(S){var R="";R="type of";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF:Zo.EF,QA$:function($){return $.ClassType.QA($)}};var NO={$ClassName:"TTypeArgument",$Parent:Zu,$Init:function($){Zu.$Init($);$.Type=null},EF:function(S){var R="";R=Zu.EF$(S.Type);return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var IM={$ClassName:"TTypeAlias",$Parent:IU,$Init:function($){IU.$Init($);$.Type=null;$.TypeParameters=[]},EF:function(S){var R="";R=S.Name+" = "+Zu.EF$(S.Type);return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var Wc={$ClassName:"TStringType",$Parent:ZD,$Init:function($){ZD.$Init($)},QA:function(S){var R="";R="String";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF:ZD.EF,QA$:function($){return $.ClassType.QA($)}};var s5={$ClassName:"TParameter",$Parent:IU,$Init:function($){IU.$Init($);$.DefaultValue="";$.IsRest=$.IsOptional=false;$.AccessibilityModifier=0;$.Type=null},EF:function(S){var R="";R=S.Name+": "+Zu.EF$(S.Type);if(S.DefaultValue!="")R+=" = "+S.DefaultValue;if(S.IsRest)R+=" {...}";return R},EU:function(S,ga){var R="";R=zs(S.Name);if(!ga){R+=": ";if(S.Type){R+=Zu.EF$(S.Type)}else R+="Variant"}
return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var rx={$ClassName:"TObjectType",$Parent:Y8,$Init:function($){Y8.$Init($);$.Members=[]},EF:function(S){var R="";var gr=0;var mM=null;var Ti=[];Zu.WU(S.ClassType);Ti=S.Members;var $t8;for(gr=0,$t8=Ti.length;gr<$t8;gr++){mM=Ti[gr];R+=Zu.EF$(mM)}
Zu.kk(S.ClassType);R+=Zu.b2(S.ClassType)+"end;";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var IZ={$ClassName:"TNamespaceDeclaration",$Parent:IU,$Init:function($){IU.$Init($)},Destroy:TObject.Destroy,VI:Zu.VI,EF:Zu.EF};var t1={$ClassName:"TNamedType",$Parent:Zo,$Init:function($){Zo.$Init($);$.Arguments=[];$.Ls=""},Ip:function(S,Cw,js){Zu.VI(S,Cw);S.Ls=js;return S},EF:function(S){var R="";var MO=0;var tU=null;R=Zo.EF(S);if(S.Arguments.length>0){var Vt=[];R+="{<";Vt=S.Arguments;var $t9;for(MO=0,$t9=Vt.length;MO<$t9;MO++){tU=Vt[MO];R+=Zu.EF$(tU)}
R+=">}"}
return R},QA:function(S){var R="";R=S.Ls;return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)},QA$:function($){return $.ClassType.QA($)}};var xd={$ClassName:"TModuleDeclaration",$Parent:IU,$Init:function($){IU.$Init($);$.Modules=[];$.Variables=[];$.Exports=[];$.Functions=[];$.Interfaces=[];$.Classes=[]},EF:function(S){var R="";var W7=0;var re=null,sv=0;var az=null,Gv=0;var zm=null;if(S.Classes.length+S.Interfaces.length>0){var or=[],dq=[];R+="type"+"\r\n";Zu.WU(S.ClassType);dq=S.Classes;var $tA;for(W7=0,$tA=dq.length;W7<$tA;W7++){re=dq[W7];R=R+Zu.EF$(re)}
or=S.Interfaces;var $tB;for(sv=0,$tB=or.length;sv<$tB;sv++){az=or[sv];R=R+Zu.EF$(az)}
Zu.kk(S.ClassType)}
if(S.Variables.length>0){var eR=[];R+="var"+"\r\n";Zu.WU(S.ClassType);eR=S.Variables;var $tC;for(Gv=0,$tC=eR.length;Gv<$tC;Gv++){zm=eR[Gv];R=R+Zu.EF$(zm)}
Zu.kk(S.ClassType)}
return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var Yq={$ClassName:"TCustomTypeMember",$Parent:IU,$Init:function($){IU.$Init($);$.TypeParameters=[];$.Visibility=0;$.IsStatic=false;$.TypeArguments=[]},VI:function(S,Xu){Zu.VI(S,Xu);S.Visibility=0;return S},Destroy:TObject.Destroy,VI$:function($){return $.ClassType.VI.apply($.ClassType,arguments)},EF:Zu.EF};var DR={$ClassName:"TMethodDeclaration",$Parent:Yq,$Init:function($){Yq.$Init($);$.Type=null},EF:function(S){var R="";var Iz="";var NT="";var cE=0,hC=0;var Rp=null,yX=0;var P8=[];cE=0;P8=S.Type.ParameterList;var $tD;for(hC=0,$tD=P8.length;hC<$tD;hC++){Rp=P8[hC];if(Rp.IsOptional)++cE}
Iz=Zu.b2(S.ClassType);Iz+=(S.Type.ResultType)?"function":"procedure";Iz+=" "+S.Name;NT=";"+((cE>0)?" overload;":"");NT+="\r\n";R="";var $tE;for(yX=0,$tE=cE;yX<=$tE;yX++){R+=Iz+tk.ZZ(S.Type,yX)+NT}
return R},Destroy:TObject.Destroy,VI:Yq.VI,EF$:function($){return $.ClassType.EF($)}};var hm={$ClassName:"TInterfaceDeclaration",$Parent:Zu,$Init:function($){Zu.$Init($);$.TypeParameters=[];$.Name="";$.Extends=[];$.Type=null},EF:function(S){var R="";var gJ=0;var op=null,lY=0;R+=Zu.b2(S.ClassType)+"J"+S.Name;if(S.TypeParameters.length>0){var Sj=[];R+="{<";Sj=S.TypeParameters;var $tF;for(gJ=0,$tF=Sj.length;gJ<$tF;gJ++){op=Sj[gJ];R+=Zu.EF$(op)}
R+=">}"}
R+=" = class external";if(S.Extends.length>0){R+="(";R+=Zu.EF$(S.Extends[0]);var $tG;for(lY=0+1,$tG=S.Extends.length;lY<$tG;lY++){R+=", "+Zu.EF$(S.Extends[lY])}
R+=")"}
R+="\r\n";R+=Zu.EF$(S.Type);R+="\r\n"+"\r\n";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var rL={$ClassName:"TIndexDeclaration",$Parent:Yq,$Init:function($){Yq.$Init($);$.IsStringIndex=false;$.Type=null},EF:function(S){var R="";R=Zu.b2(S.ClassType)+"\/\/ ";R+="property Item["+S.Name+": ";R+=(S.IsStringIndex)?"String":"Integer";R+="]: "+Zu.EF$(S.Type)+";"+"\r\n";return R},Destroy:TObject.Destroy,VI:Yq.VI,EF$:function($){return $.ClassType.EF($)}};var oI={$ClassName:"TImportDeclaration",$Parent:IU,$Init:function($){IU.$Init($)},EF:function(S){var R="";console.log("not implemented: TImportDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var tk={$ClassName:"TFunctionType",$Parent:Zo,$Init:function($){Zo.$Init($);$.ParameterList=[];$.ResultType=null},EF:function(S){var R="";var Dn=0;if(S.ParameterList.length>0){R="("+dg.ut(S.ParameterList[0],false);var $tH;for(Dn=0+1,$tH=S.ParameterList.length;Dn<$tH;Dn++){R+="; "+dg.ut(S.ParameterList[Dn],false)}
R+=")"}
if(S.ResultType)R+=": "+Zu.EF$(S.ResultType);return R},ZZ:function(S,nv){var R="";var df=false;var kb=0,p2=0;kb=0;if(S.ParameterList.length>0){if(!(S.ParameterList[0].IsOptional&&nv==0)){kb+=(S.ParameterList[0].IsOptional?1:0);df=1<S.ParameterList.length&&Zu.EF$(S.ParameterList[0].Type)==Zu.EF$(S.ParameterList[1].Type)&&((!S.ParameterList[0].IsOptional)||kb<nv);R="("+dg.ut(S.ParameterList[0],df);var $tI;for(p2=0+1,$tI=S.ParameterList.length;p2<$tI;p2++){if(S.ParameterList[p2].IsOptional&&kb>=nv)break;kb+=(S.ParameterList[p2].IsOptional?1:0);R+=(df)?", ":"; ";df=p2+1<S.ParameterList.length&&Zu.EF$(S.ParameterList[p2].Type)==Zu.EF$(S.ParameterList[p2+1].Type)&&((!S.ParameterList[p2].IsOptional)||kb<nv);R+=dg.ut(S.ParameterList[p2],df)}
R+=")"}}
if(S.ResultType)R+=": "+Zu.EF$(S.ResultType);return R},QA:function(S){var R="";R="function";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)},QA$:function($){return $.ClassType.QA($)}};var dg={$ClassName:"TFunctionParameter",$Parent:IU,$Init:function($){IU.$Init($);$.Type=null;$.IsOptional=false},EF:function(S){var R="";R=zs(S.Name)+": ";if(S.Type){R+=Zu.EF$(S.Type)}else R+="Variant";return R},ut:function(S,Nc){var R="";R=zs(S.Name);if(!Nc){R+=": ";if(S.Type){R+=Zu.EF$(S.Type)}else R+="Variant"}
return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var wv={$ClassName:"TFunctionDeclaration",$Parent:IU,$Init:function($){IU.$Init($);$.Type=null},EF:function(S){var R="";var R6="";var CQ="";var T2=0,Eu=0;var c3=null,pY=0;var MY=[];T2=0;MY=S.Type.ParameterList;var $tJ;for(Eu=0,$tJ=MY.length;Eu<$tJ;Eu++){c3=MY[Eu];if(c3.IsOptional)++T2}
R6=Zu.b2(S.ClassType);R6+=(S.Type.ResultType)?"function":"procedure";R6+=" "+S.Name;CQ=";"+((T2>0)?" overload;":"");CQ+="\r\n";R="";var $tK;for(pY=0,$tK=T2;pY<=$tK;pY++){R+=R6+tk.ZZ(S.Type,pY)+CQ}
return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var s9={$ClassName:"TFloatType",$Parent:ZD,$Init:function($){ZD.$Init($)},QA:function(S){var R="";R="Float";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF:ZD.EF,QA$:function($){return $.ClassType.QA($)}};var CC={$ClassName:"TFieldDeclaration",$Parent:Yq,$Init:function($){Yq.$Init($);$.Nullable=false;$.Type=null},EF:function(S){var R="";var T5=0;var cf=null;R=Zu.b2(S.ClassType)+zs(S.Name);if(S.TypeArguments.length>0){var JS=[];R+="{<";JS=S.TypeArguments;var $tL;for(T5=0,$tL=JS.length;T5<$tL;T5++){cf=JS[T5];R+=Zu.EF$(cf)}
R+=">}"}
R+=": "+Zu.EF$(S.Type)+";";if(S.Nullable)R+=" \/\/ nullable";R+="\r\n";return R},Destroy:TObject.Destroy,VI:Yq.VI,EF$:function($){return $.ClassType.EF($)}};var Ex={$ClassName:"TExportDeclaration",$Parent:IU,$Init:function($){IU.$Init($);$.RL=false},EF:function(S){var R="";R="";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var Kw={$ClassName:"TEnumerationItem",$Parent:Zu,$Init:function($){Zu.$Init($);$.Name=$.Value=""},EF:function(S){var R="";R=S.Name;return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var f7={$ClassName:"TEnumerationDeclaration",$Parent:IU,$Init:function($){IU.$Init($);$.Items=[]},EF:function(S){var R="";var jh=0;var SO=null;var Rv=[];R+=Zu.b2(S.ClassType)+"T"+S.Name+" = Variant;"+"\r\n";R+=Zu.b2(S.ClassType)+"T"+S.Name+"Helper = strict helper for T"+S.Name+"\r\n";Zu.WU(S.ClassType);Rv=S.Items;var $tM;for(jh=0,$tM=Rv.length;jh<$tM;jh++){SO=Rv[jh];R+=Zu.b2(S.ClassType)+"const "+zs(Zu.EF$(SO));if(SO.Value!=""){try{R+=" = "+(parseInt(SO.Value,10)).toString()+";"+"\r\n"}catch($e){R+=" = '"+SO.Value+"';"+"\r\n"}}else R+=" = '"+SO.Name+"';"+"\r\n"}
Zu.kk(S.ClassType);R+=Zu.b2(S.ClassType)+"end;"+"\r\n";R+="\r\n";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var Vq={$ClassName:"TDefinitionDeclaration",$Parent:IU,$Init:function($){IU.$Init($)},EF:function(S){var R="";console.log("not implemented: TDefinitionDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var as={$ClassName:"TConstructorType",$Parent:Zo,$Init:function($){Zo.$Init($);$.ResultType=null;$.ParameterList=[]},EF:function(S){var R="";var h8=0;if(S.ParameterList.length>0){R="("+dg.ut(S.ParameterList[0],false);var $tN;for(h8=0+1,$tN=S.ParameterList.length;h8<$tN;h8++){R+="; "+dg.ut(S.ParameterList[h8],false)}
R+=")"}
if(S.ResultType)R+=": "+Zu.EF$(S.ResultType);return R},QA:function(S){var R="";R="constructor";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)},QA$:function($){return $.ClassType.QA($)}};var Nm={$ClassName:"TConstructorDeclaration",$Parent:Yq,$Init:function($){Yq.$Init($);$.ParameterList=[];$.Type=null},EF:function(S){var R="";R=Zu.b2(S.ClassType)+"constructor Create";if(S.Type)R+=Zu.EF$(S.Type);R+=";"+"\r\n";return R},Destroy:TObject.Destroy,VI:Yq.VI,EF$:function($){return $.ClassType.EF($)}};var PX={$ClassName:"TClassDeclaration",$Parent:hm,$Init:function($){hm.$Init($);$.Implements=[];$.Members=[]},EF:function(S){var R="";var J7=0;var aH=0;var GS=null;var g9=[];R+=Zu.b2(S.ClassType)+"J"+S.Name+" = class external '"+S.Name+"'";if(S.Extends.length>0){R+="(";R+=Zu.EF$(S.Extends[0]);var $tO;for(J7=0+1,$tO=S.Extends.length;J7<$tO;J7++){R+=", "+Zu.EF$(S.Extends[J7])}
R+=")"}
R+="\r\n";Zu.WU(S.ClassType);g9=S.Members;var $tP;for(aH=0,$tP=g9.length;aH<$tP;aH++){GS=g9[aH];R+=Zu.EF$(GS)}
Zu.kk(S.ClassType);R+=Zu.b2(S.ClassType)+"end;"+"\r\n"+"\r\n";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var Lb={$ClassName:"TCallSignature",$Parent:Zu,$Init:function($){Zu.$Init($);$.ParameterList=[];$.Type=null;$.TypeParameters=[]},EF:function(S){var R="";var tt=0;var il=null,pK=0;R="";if(S.TypeParameters.length>0){var BB=[];R+="{<";BB=S.TypeParameters;var $tQ;for(tt=0,$tQ=BB.length;tt<$tQ;tt++){il=BB[tt];R+=Zu.EF$(il)}
R+=">}"}
if(S.ParameterList.length>0){R+="(";var $tR;for(pK=0,$tR=(S.ParameterList.length-1);pK<$tR;pK++){R+=s5.EU(S.ParameterList[pK],false)+"; "}
R+=s5.EU(S.ParameterList[(S.ParameterList.length-1)],false)+")"}
if(S.Type)R+=": "+Zu.EF$(S.Type);return R},ZY:function(S,yL){var R="";var Z5=false;var uK=0,vY=0;uK=0;if(S.ParameterList.length>0){if(!(S.ParameterList[0].IsOptional&&yL==0)){uK+=(S.ParameterList[0].IsOptional?1:0);Z5=1<S.ParameterList.length&&Zu.EF$(S.ParameterList[0].Type)==Zu.EF$(S.ParameterList[1].Type)&&((!S.ParameterList[0].IsOptional)||uK<yL);R="("+s5.EU(S.ParameterList[0],Z5);var $tS;for(vY=0+1,$tS=S.ParameterList.length;vY<$tS;vY++){if(S.ParameterList[vY].IsOptional&&uK>=yL)break;uK+=(S.ParameterList[vY].IsOptional?1:0);R+=(Z5)?", ":"; ";Z5=vY+1<S.ParameterList.length&&Zu.EF$(S.ParameterList[vY].Type)==Zu.EF$(S.ParameterList[vY+1].Type)&&((!S.ParameterList[vY].IsOptional)||uK<yL);R+=s5.EU(S.ParameterList[vY],Z5)}
R+=")"}}
if(S.Type)R+=": "+Zu.EF$(S.Type);return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var Tt={$ClassName:"TCallbackDeclaration",$Parent:Yq,$Init:function($){Yq.$Init($);$.Type=null},EF:function(S){var R="";R=Zu.b2(S.ClassType)+"callback "+S.Name;if(S.Type)R+=tk.ZZ(S.Type,S.Type.ParameterList.length);R+=";"+"\r\n";return R},Destroy:TObject.Destroy,VI:Yq.VI,EF$:function($){return $.ClassType.EF($)}};var uj={$ClassName:"TBooleanType",$Parent:ZD,$Init:function($){ZD.$Init($)},QA:function(S){var R="";R="Boolean";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF:ZD.EF,QA$:function($){return $.ClassType.QA($)}};var eq={$ClassName:"TArrayType",$Parent:Y8,$Init:function($){Y8.$Init($);$.Type=null},EF:function(S){var R="";R="array of "+Zu.EF$(S.Type);return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var yl={$ClassName:"TAmbientVariableDeclaration",$Parent:Zu,$Init:function($){Zu.$Init($);$.IsConst=false;$.AmbientBindingList=[]},EF:function(S){var R="";var U1=0;var NZ=null;var uv=[];uv=S.AmbientBindingList;var $tT;for(U1=0,$tT=uv.length;U1<$tT;U1++){NZ=uv[U1];R+=Zu.b2(S.ClassType)+Zu.EF$(NZ)}
R+=";"+"\r\n";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var x2={$ClassName:"TAmbientBodyElement",$Parent:Zu,$Init:function($){Zu.$Init($)},Destroy:TObject.Destroy,VI:Zu.VI,EF:Zu.EF};var yK={$ClassName:"TAmbientPropertyMemberDeclaration",$Parent:x2,$Init:function($){x2.$Init($);$.Visibility=0;$.IsStatic=false;$.Name=""},Destroy:TObject.Destroy,VI:Zu.VI,EF:Zu.EF};var LZ={$ClassName:"TAmbientPropertyMemberDeclarationProperty",$Parent:yK,$Init:function($){yK.$Init($);$.Type=null},EF:function(S){var R="";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var Mm={$ClassName:"TAmbientPropertyMemberDeclarationMethod",$Parent:yK,$Init:function($){yK.$Init($);$.CallSignature=null},EF:function(S){var R="";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var A8={$ClassName:"TAmbientModuleDeclaration",$Parent:Zu,$Init:function($){Zu.$Init($);$.Interfaces=[];$.Modules=[];$.Classes=[];$.Functions=[];$.TypeAliases=[];$.IdentifierPath="";$.Enums=[];$.Variables=[]},EF:function(S){var R="";var vh=0,cy=0;var mu=null,aM=0;var Sd=null,mL=0;var Hy=null,f1=0;var f2=null,X9=0;var ZG=null,ST=0;var hO=null,VM=0;var qP=null,zP=0;var g8=null,t3=0;var y5=null;var Tr=[],oB=[];R="\/\/"+S.IdentifierPath+"\r\n"+"\r\n";vh=0;oB=S.Variables;var $tU;for(cy=0,$tU=oB.length;cy<$tU;cy++){mu=oB[cy];if(mu.IsConst)++vh}
if(vh>0){var tj=[];R+="const"+"\r\n";Zu.WU(S.ClassType);tj=S.Variables;var $tV;for(aM=0,$tV=tj.length;aM<$tV;aM++){Sd=tj[aM];if(Sd.IsConst)R=R+Zu.EF$(Sd)}
Zu.kk(S.ClassType);R+="\r\n"}
if(S.Enums.length+S.Classes.length+S.Interfaces.length>0){var Vc=[],Os=[],v8=[],vB=[];R+="type"+"\r\n";Zu.WU(S.ClassType);Os=S.Enums;var $tW;for(mL=0,$tW=Os.length;mL<$tW;mL++){Hy=Os[mL];R+=Zu.EF$(Hy)}
Vc=S.Classes;var $tX;for(f1=0,$tX=Vc.length;f1<$tX;f1++){f2=Vc[f1];R+=Zu.EF$(f2)}
vB=S.Interfaces;var $tY;for(X9=0,$tY=vB.length;X9<$tY;X9++){ZG=vB[X9];R+=Zu.EF$(ZG)}
v8=S.TypeAliases;var $tZ;for(ST=0,$tZ=v8.length;ST<$tZ;ST++){hO=v8[ST];R+=Zu.EF$(hO)}
Zu.kk(S.ClassType)}
Tr=S.Modules;var $ta;for(VM=0,$ta=Tr.length;VM<$ta;VM++){qP=Tr[VM];R+=Zu.EF$(qP)}
if(S.Functions.length>0){var Eq=[];Eq=S.Functions;var $tb;for(zP=0,$tb=Eq.length;zP<$tb;zP++){g8=Eq[zP];R+=Zu.EF$(g8)}
R+="\r\n"}
if(S.Variables.length-vh>0){var qR=[];R+="var"+"\r\n";Zu.WU(S.ClassType);qR=S.Variables;var $tc;for(t3=0,$tc=qR.length;t3<$tc;t3++){y5=qR[t3];if(!y5.IsConst)R=R+Zu.EF$(y5)}
Zu.kk(S.ClassType);R+="\r\n"}
return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var SQ={$ClassName:"TAmbientFunctionDeclaration",$Parent:IU,$Init:function($){IU.$Init($);$.CallSignature=null},EF:function(S){var R="";var Ix="";var Kv="";var QN=0,ew=0;var q6=null,Hi=0;var fT=[];QN=0;fT=S.CallSignature.ParameterList;var $td;for(ew=0,$td=fT.length;ew<$td;ew++){q6=fT[ew];if(q6.IsOptional)++QN}
Ix=Zu.b2(S.ClassType);Ix+=(S.CallSignature.Type)?"function":"procedure";Ix+=" "+S.Name;Kv=";"+((QN>0)?" overload;":"");Kv+="\r\n";R="";var $te;for(Hi=0,$te=QN;Hi<=$te;Hi++){R+=Ix+Lb.ZY(S.CallSignature,Hi)+Kv}
return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var mQ={$ClassName:"TAmbientDeclaration",$Parent:IU,$Init:function($){IU.$Init($);$.Variables=[];$.Namespaces=[];$.Modules=[];$.Classes=[];$.Functions=[];$.Enums=[]},EF:function(S){var R="";var Mw=0;var dU=null,hY=0;var nc=null,Wq=0;var Yi=null,fL=0;var w1=null;var my=[],qg=[],mv=[];mv=S.Functions;var $tf;for(Mw=0,$tf=mv.length;Mw<$tf;Mw++){dU=mv[Mw];R+=Zu.EF$(dU)}
qg=S.Modules;var $tg;for(hY=0,$tg=qg.length;hY<$tg;hY++){nc=qg[hY];R+=Zu.EF$(nc)}
if(S.Classes.length>0){var zn=[];R+="type"+"\r\n";Zu.WU(S.ClassType);zn=S.Classes;var $th;for(Wq=0,$th=zn.length;Wq<$th;Wq++){Yi=zn[Wq];R=R+Zu.EF$(Yi)}
Zu.kk(S.ClassType)}
if(S.Variables.length>0){my=S.Variables;var $ti;for(fL=0,$ti=my.length;fL<$ti;fL++){w1=my[fL];R=R+Zu.EF$(w1)}}
return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var x1={$ClassName:"TAmbientConstructorDeclaration",$Parent:x2,$Init:function($){x2.$Init($);$.ParameterList=[]},EF:function(S){var R="";R=Zu.b2(S.ClassType)+"constructor";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var TB={$ClassName:"TAmbientClassDeclaration",$Parent:Zu,$Init:function($){Zu.$Init($);$.Members=[];$.Name="";$.Extends=[];$.Implements=[]},EF:function(S){var R="";return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var hl={$ClassName:"TAmbientBinding",$Parent:IU,$Init:function($){IU.$Init($);$.Type=null},EF:function(S){var R="";R=S.Name+": "+Zu.EF$(S.Type);return R},Destroy:TObject.Destroy,VI:Zu.VI,EF$:function($){return $.ClassType.EF($)}};var PR=["amPublic","amPrivate","amProtected"];function zs(ES){var R="";R=ES;if((["type","export","label","public","protected","private","abstract","default","const","constructor","property","function","class","interface","string","end","uses","div","object"].indexOf((ES).toLowerCase())>=0))R="&"+R;if((["length","include","exclude"].indexOf((ES).toLowerCase())>=0))R="_"+R;return R};var v=null;var v=require("typescript");var BN=0;var I=[],cp="",Q6="",dY=null;var dY=Pe();I=process.argv;I.splice(0,2);if(I.length==0){return"Usage: ts2pas inputfile [outputfile]"}
cp=I[0];Q6=I[0]+".pas";if(I.length==2)Q6=I[1];TG(cp,Q6);