#! /usr/bin/env node
/**
* ts2pas
* https://github.com/CWBudde/TS2Pas
*
* Copyright (c) 2016 Christian-W. Budde
* Licensed under the MIT license.
*/


var TObject={$ClassName:"TObject",$Parent:null,ClassName:function(s){return s.$ClassName},ClassType:function(s){return s},ClassParent:function(s){return s.$Parent},$Init:function(){},Create:function(s){return s},Destroy:function(s){for(var prop in s)if(s.hasOwnProperty(prop))delete s.prop},Destroy$:function(s){return s.ClassType.Destroy(s)},Free:function(s){if(s!==null)s.ClassType.Destroy(s)}}
function StrReplace(s,o,n){return o?s.replace(new RegExp(StrRegExp(o),"g"),n):s}
function StrRegExp(s){return s.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")}
function StrBefore(s,d){if(!d)return s;var p=s.indexOf(d);return(p<0)?s:s.substr(0,p)}
var Exception={$ClassName:"Exception",$Parent:TObject,$Init:function(){var FMessage=""},Create:function(s,Msg){s.FMessage=Msg;return s}}
function stringRepeat(s,n){if(n<1)return'';var r='';while(n>0){if(n&1)r+=s;n>>=1,s+=s};return r};function DupeString(s,n){return stringRepeat(s,n)}
function $W(e){return e.ClassType?e:Exception.Create($New(Exception),e.constructor.name+", "+e.message)}
function $StrSet(s,i,v,z){if(i<1)throw Exception.Create($New(Exception),"Lower bound exceeded! Index "+i.toString()+z);if(i>s.length)throw Exception.Create($New(Exception),"Upper bound exceeded! Index "+i.toString()+z);return s.substring(0,i-1)+v+s.substring(i)}
function $New(c){var i={ClassType:c};c.$Init(i);return i}
function $Is(o,c){if(o===null)return false;return $Inh(o.ClassType,c)};function $Inh(s,c){if(s===null)return false;while((s)&&(s!==c))s=s.$Parent;return(s)?true:false};function $Extend(base,sub,props){function F(){};F.prototype=base.prototype;sub.prototype=new F();sub.prototype.constructor=sub;for(var n in props){if(props.hasOwnProperty(n)){sub.prototype[n]=props[n]}}}
function $AsIntf(o,i){if(o===null)return null;var r=o.ClassType.$Intf[i].map(function(e){return function(){var arg=Array.prototype.slice.call(arguments);arg.splice(0,0,o);return e.apply(o,arg)}});r.O=o;return r};function $As(o,c){if((o===null)||$Is(o,c))return o;throw Exception.Create($New(Exception),"Cannot cast instance of type \""+o.ClassType.$ClassName+"\" to class \""+c.$ClassName+"\"")}
function JError(){}
$Extend(Object,JError,{});function Q2(j9){if(j9==StrBefore(j9,".d.ts"))j9+=".d.ts";ZW.readFile(j9,function(uW,Pw){var Sz="",x3=null;Sz=Pw.toString("utf8");x3=H.createSourceFile(j9,Sz,2,true);vm(x3)})};function dY(iF,MV){var zd="";zd=StrBefore(iF,".d.ts");if(iF==zd)iF+=".d.ts";ZW.readFile(iF,function(H7,UE){var ub="",EP=null,Re="";if(!UE)return;ub=UE.toString("utf8");EP=r4.t5($New(r4));EP.Name=zd;Re=r4.m8(EP,ub);ZW.writeFile(MV,Re,function(x5){});EP=null})};function K7(tn){dY(tn,StrBefore(tn,".d.ts")+".pas")};function vm(av){wK(av)};function wK(bg){var R=undefined;switch(bg.kind){case 9:console.log(bg.text);break;case 69:console.log(bg.text);break;case 151:console.log(bg.text);break;case 122:console.log("declare");break;case 135:console.log(bg.left);break;default:console.log(bg.kind)}
H.forEachChild(bg,wK);return R};function Copy$wG(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$wG($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Copy$bt(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$bt($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Copy$ou(s,d){d.persistent=s.persistent;return d}
function Clone$ou($){return{persistent:$.persistent}}
function Copy$W1(s,d){d.curr=s.curr;d.prev=s.prev;return d}
function Clone$W1($){return{curr:$.curr,prev:$.prev}}
function Copy$X5(s,d){d.curr=s.curr;d.prev=s.prev;return d}
function Clone$X5($){return{curr:$.curr,prev:$.prev}}
function Copy$PT(s,d){d.persistent=s.persistent;d.interval=s.interval;return d}
function Clone$PT($){return{persistent:$.persistent,interval:$.interval}}
function Copy$yQ(s,d){d.encoding=s.encoding;d.flag=s.flag;return d}
function Clone$yQ($){return{encoding:$.encoding,flag:$.flag}}
function Copy$Hm(s,d){d.encoding=s.encoding;d.flag=s.flag;return d}
function Clone$Hm($){return{encoding:$.encoding,flag:$.flag}}
function Copy$fg(s,d){d.flags=s.flags;d.encoding=s.encoding;d.string_=s.string_;return d}
function Clone$fg($){return{flags:$.flags,encoding:$.encoding,string_:$.string_}}
function Copy$Et(s,d){d.bufferSize=s.bufferSize;d.encoding=s.encoding;d.fd=s.fd;d.mode=s.mode;d.flags=s.flags;return d}
function Clone$Et($){return{bufferSize:$.bufferSize,encoding:$.encoding,fd:$.fd,mode:$.mode,flags:$.flags}}
function Copy$Kn(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$Kn($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Copy$sF(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$sF($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function kP(){var R=null;R=require("fs");return R};function pP(){var R=null;R=require("stream");return R};function Zd(){var R=null;R=require("events");return R};var r4={$ClassName:"TTranslator",$Parent:TObject,$Init:function($){TObject.$Init($);$.NeedsSemicolon=false;$.Name="";$.Z6=[];$.pn=[];$.bR=[];$.ru=[];$.J1=$.oB=null},e6:function(S){return S.J1.getTokenText()},LF:function(S){return S.J1.getToken()},Lc:function(S,ge){if(!(S.J1.isIdentifier()||ge.indexOf(r4.LF(S))>=0))r4.Tm(S,0)},XI:function(S,t4){if(!(t4.indexOf(r4.LF(S))>=0))r4.Tm(S,0)},fF:function(S,eB){if(r4.LF(S)!=eB)r4.Tm(S,eB)},Rx:function(S){var R="";var H4=0;var xe=null,h7=0;var qL=null,bF=0;var Av=null,XQ=0;var cp=null;var NN=[],qE=[],Dy=[];R="unit "+oS(S.Name)+";"+"\r\n"+"\r\n";R+="interface"+"\r\n"+"\r\n";Dy=S.pn;var $t1;for(H4=0,$t1=Dy.length;H4<$t1;H4++){xe=Dy[H4];R=R+op.xl$(xe)}
qE=S.ru;var $t2;for(h7=0,$t2=qE.length;h7<$t2;h7++){qL=qE[h7];R=R+op.xl$(qL)}
if(S.bR.length>0){var g7=[];R+="type"+"\r\n";op.nA(op);g7=S.bR;var $t3;for(bF=0,$t3=g7.length;bF<$t3;bF++){Av=g7[bF];R=R+op.xl$(Av)}
op.T9(op)}
NN=S.Z6;var $t4;for(XQ=0,$t4=NN.length;XQ<$t4;XQ++){cp=NN[XQ];R=R+op.xl$(cp)}
return R},t5:function(S){S.NeedsSemicolon=false;return S},Tm:function(S,cv){var pe=null,yY="";pe=H.getLineAndCharacterOfPosition(S.oB,S.J1.getTokenPos());yY=("Unknown token \""+r4.e6(S).toString()+"\" in this context ("+(pe.line+1).toString()+":"+(pe.character+1).toString()+")");if(cv>0)yY+=("; Expected ("+cv.toString()+")");console.trace("");throw Exception.Create($New(Exception),yY)},to:function(S){var R=null;r4.Lc(S,[]);R=op.OO$($New(Vs),$AsIntf(S,"IR"));R.Name=r4.e6(S);if(r4.Ar(S,54,false))R.Type=r4.CM(S);if(S.NeedsSemicolon)r4.XI(S,[23,24].slice());return R},pY:function(S,C9){do{C9.push(r4.to(S));if(r4.LF(S)==23)break;if(r4.LF(S)!=24)break;if(!r4.Gi(S,false))break}while(!(r4.LF(S)==23||(!S.J1.isIdentifier())||(!S.NeedsSemicolon)&&(!S.J1.isIdentifier())))},Rh:function(S){var R=null;var jd=0,ta=false;r4.Lc(S,[121,110,111,112,113].slice());if(r4.LF(S)==121)return r4.GH(S);jd=0;switch(r4.LF(S)){case 112:jd=0;r4.Pp(S,[113].slice(),true);break;case 111:jd=1;r4.Pp(S,[113].slice(),true);break;case 110:jd=2;r4.Pp(S,[113].slice(),true);break}
ta=r4.LF(S)==113;if(ta)r4.Gi(S,true);R=r4.Sm(S);$As(R,qj).IsStatic=ta;$As(R,qj).Visibility=jd;if(S.NeedsSemicolon)r4.XI(S,[23,16].slice());return R},cN:function(S){var R=null;var UP=[],UP=[121,110,111,112,113,16,23].slice();r4.fF(S,73);R=op.OO$($New(MI),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.BK(S,[83,106,15].slice(),true);if(r4.LF(S)==83){r4.Gi(S,true);R.Extends.push(r4.Rg(S))}
if(r4.LF(S)==106){r4.Gi(S,true);R.Implements.push(r4.NV(S));while(r4.LF(S)==24){r4.Gi(S,true);R.Implements.push(r4.NV(S))}}
r4.fF(S,15);r4.Pp(S,UP,false);while(r4.LF(S)!=16){R.Members.push(r4.Rh(S));if(r4.LF(S)==23)r4.Pp(S,UP,false)}
r4.fF(S,16);return R},GH:function(S){var R=null;r4.fF(S,121);r4.Ar(S,17,true);R=op.OO$($New(qF),$AsIntf(S,"IR"));while(r4.Gi(S,false)){R.ParameterList.push(r4.kn(S));r4.XI(S,[24,18,23].slice());if(r4.LF(S)==18)break}
r4.XI(S,[18,23].slice());if(r4.LF(S)!=23)r4.Ar(S,23,true);return R},J9:function(S){var R=null;r4.fF(S,122);R=op.OO$($New(yK),$AsIntf(S,"IR"));r4.BK(S,[102,108,74,87,73,81,125,126].slice(),true);switch(r4.LF(S)){case 102:case 108:case 74:R.Variables.push(r4.Pg(S));break;case 87:R.Functions.push(r4.be(S));break;case 73:R.Classes.push(r4.cN(S));break;case 81:R.Enums.push(r4.E2(S));break;case 125:R.Modules.push(r4.no(S));break;case 126:R.Namespaces.push(r4.KN(S));break}
return R},E2:function(S){var R=null;R=r4.kO(S);return R},be:function(S){var R=null;r4.fF(S,87);R=op.OO$($New(mV),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.BK(S,[17,25].slice(),true);R.CallSignature=r4.kU(S);if(S.NeedsSemicolon)r4.XI(S,[23].slice());return R},no:function(S){var R=null;var gY=[],gY=[82,102,108,74,132,87,73,107,81,125,89,16,23].slice();var G9=false,RJ=null;r4.fF(S,125);R=op.OO$($New(ZH),$AsIntf(S,"IR"));r4.Pp(S,[9].slice(),true);R.IdentifierPath=r4.NV(S);r4.fF(S,15);r4.BK(S,gY,true);while(r4.LF(S)!=16){G9=r4.LF(S)==82;if(G9){r4.BK(S,gY.concat([77,56]),true);if(r4.LF(S)==77){G9=false;r4.Gi(S,false);r4.Ar(S,23,false);r4.BK(S,gY,true)}
if(r4.LF(S)==56){G9=false;r4.Gi(S,false);r4.Ar(S,23,false);r4.BK(S,gY,true)}}
switch(r4.LF(S)){case 102:case 108:R.Variables.push(r4.Pg(S));break;case 74:r4.Pp(S,[81].slice(),false);if(r4.LF(S)==81){R.Enums.push(r4.E2(S))}else{RJ=op.OO$($New(ey),$AsIntf(S,"IR"));RJ.IsConst=true;r4.pY(S,RJ.AmbientBindingList);R.Variables.push(RJ)}
r4.BK(S,gY,true);break;case 132:R.TypeAliases.push(r4.El(S));r4.BK(S,gY,true);break;case 87:R.Functions.push(r4.be(S));break;case 73:R.Classes.push(r4.Km(S));r4.BK(S,gY,true);break;case 125:R.Modules.push(r4.no(S));r4.BK(S,gY,true);break;case 107:R.Interfaces.push(r4.Yd(S));r4.BK(S,gY,true);break;case 89:r4.Ay(S);if(!S.NeedsSemicolon)r4.BK(S,gY,true);break;case 81:r4.kO(S);r4.BK(S,gY,true);break}
if(r4.LF(S)==23)r4.BK(S,gY,true)}
r4.fF(S,16);return R},KN:function(S){var R=null;console.log("not implemented: ReadAmbientNamespaceDeclaration");return R},Sm:function(S){var R=null;var zq="";r4.Lc(S,[]);zq=r4.e6(S);r4.BK(S,[54,17,23].slice(),true);if(r4.LF(S)==17){R=r4.xs(S)}else R=r4.cF(S);R.Name=zq;if(S.NeedsSemicolon)r4.Lc(S,[23,16,24].slice());return R},xs:function(S){var R=null;r4.fF(S,17);R=op.OO$($New(FJ),$AsIntf(S,"IR"));R.CallSignature=r4.kU(S);r4.XI(S,[18,23].slice());if(r4.LF(S)!=23)r4.Ar(S,23,true);return R},cF:function(S){var R=null;R=op.OO$($New(Pu),$AsIntf(S,"IR"));if(r4.LF(S)==54)R.Type=r4.kC(S);return R},Pg:function(S){var R=null;r4.XI(S,[102,108,74].slice());R=op.OO$($New(ey),$AsIntf(S,"IR"));R.IsConst=r4.LF(S)==74;r4.Gi(S,true);r4.pY(S,R.AmbientBindingList);return R},kU:function(S){var R=null;r4.XI(S,[17,25].slice());R=op.OO$($New(v9),$AsIntf(S,"IR"));if(r4.LF(S)==25){do{R.TypeParameters.push(r4.ka(S))}while(!(r4.LF(S)!=24));r4.Ar(S,17,true)}
r4.fF(S,17);r4.Pp(S,[112,110,111,22,18].slice(),true);while(r4.LF(S)!=18){R.ParameterList.push(r4.dH(S));if(r4.LF(S)==24)r4.Pp(S,[22].slice(),false)}
r4.XI(S,[18].slice());r4.BK(S,[54,23].slice(),true);if(r4.LF(S)==54)R.Type=r4.kC(S);return R},Km:function(S){var R=null;var TZ=[],TZ=[83,106,15,25].slice();r4.fF(S,73);R=op.OO$($New(ph),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.BK(S,TZ,true);if(r4.LF(S)==25){TZ.push(25);do{R.TypeParameters.push(r4.ka(S))}while(!(r4.LF(S)!=24));r4.fF(S,27);r4.BK(S,TZ,true)}
if(r4.LF(S)==83){r4.Gi(S,true);R.Extends.push(r4.Rg(S))}
if(r4.LF(S)==106){r4.Gi(S,true);R.Implements.push(r4.NV(S));while(r4.LF(S)==24){r4.Gi(S,true);R.Implements.push(r4.NV(S))}}
r4.fF(S,15);r4.ct(S,R);return R},Ft:function(S){var R=null;var NU=[],lH="",li=false;r4.Lc(S,[92,9,82].slice());lH=r4.e6(S);r4.BK(S,[25,53,54,17].slice(),true);if(r4.LF(S)==25){NU.push(r4.ka(S));r4.BK(S,[53,54,17].slice(),true)}
li=r4.LF(S)==53;if(li)r4.Ar(S,54,true);switch(r4.LF(S)){case 54:R=r4.iX(S);$As(R,qQ).Nullable=li;break;case 17:if((lH).toLowerCase()=="constructor"){R=r4.jh(S)}else R=r4.W5(S);break}
R.Name=lH;R.TypeParameters=NU;if(S.NeedsSemicolon)r4.XI(S,[23,24,16].slice());return R},ct:function(S,qt){var Tp=[],Tp=[92,9,82,16,23].slice();var EO=0,C6=false,DH=null;r4.fF(S,15);r4.Pp(S,Tp,false);while(r4.LF(S)!=16){EO=0;switch(r4.LF(S)){case 112:EO=0;r4.Pp(S,[92].slice(),true);break;case 111:EO=1;r4.Pp(S,[92].slice(),true);break;case 110:EO=2;r4.Pp(S,[92].slice(),true);break}
C6=r4.LF(S)==113;if(C6)r4.Pp(S,[92,17].slice(),true);DH=r4.Ft(S);DH.Visibility=EO;DH.IsStatic=C6;qt.Members.push(DH);if(r4.LF(S)==23)r4.Pp(S,Tp,false)}},jh:function(S){var R=null;R=op.OO$($New(ss),$AsIntf(S,"IR"));R.Type=r4.Tt(S);if(S.NeedsSemicolon)r4.XI(S,[23,16].slice());return R},mE:function(S){var R=null;r4.fF(S,92);R=op.OO$($New(ss),$AsIntf(S,"IR"));if(r4.Gi(S,false)){r4.Ar(S,17,false)}
r4.fF(S,17);r4.Pp(S,[112,110,111,22,18].slice(),true);while(r4.LF(S)!=18){R.ParameterList.push(r4.dH(S));if(r4.LF(S)==24)r4.Pp(S,[22].slice(),false)}
r4.fF(S,18);r4.Ar(S,54,true);R.Type=r4.CM(S);return R},ua:function(S){var R=null;r4.fF(S,92);R=op.OO$($New(Ux),$AsIntf(S,"IR"));r4.Ar(S,17,true);while(r4.Pp(S,[22].slice(),false)){R.ParameterList.push(r4.kn(S));r4.XI(S,[24,18,23].slice());if(r4.LF(S)==18)break}
r4.XI(S,[18,23].slice());if(r4.BK(S,[54,34].slice(),false))R.ResultType=r4.kC(S);return R},ll:function(S){var fL=[],fL=[82,122,107,125,89,1].slice();r4.BK(S,fL,true);while(r4.LF(S)!=1){switch(r4.LF(S)){case 82:r4.BK(S,fL,true);continue;break;case 122:S.Z6.push(r4.J9(S));break;case 107:S.bR.push(r4.Yd(S));break;case 125:S.ru.push(r4.BY(S));break;case 89:S.pn.push(r4.Ay(S));break}
if(([16,23].indexOf(r4.LF(S))>=0))r4.BK(S,fL,true)}},kO:function(S){var R=null;r4.fF(S,81);R=op.OO$($New(pf),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.Ar(S,15,true);r4.Pp(S,[16].slice(),true);if(r4.LF(S)!=16){do{R.Items.push(r4.TN(S));if(r4.LF(S)==16)break}while(!(!r4.Gi(S,false)))}
r4.fF(S,16);return R},TN:function(S){var R=null;r4.Lc(S,[]);R=op.OO$($New(GY),$AsIntf(S,"IR"));R.Name=r4.e6(S);if(r4.Ar(S,56,false)){r4.Ar(S,8,true);R.Value=r4.e6(S);r4.SX(S)}
r4.XI(S,[24,16].slice());return R},mA:function(S){var R=null;r4.fF(S,82);R=op.OO$($New(DP),$AsIntf(S,"IR"));r4.Pp(S,[77].slice(),true);R.Bp=r4.LF(S)==82||(r4.e6(S)).toLowerCase()=="default";if(R.Bp)r4.Gi(S,true);R.Name=r4.e6(S);r4.Ar(S,23,true);return R},iX:function(S){var R=null;R=op.OO$($New(qQ),$AsIntf(S,"IR"));R.Type=r4.kC(S);if(S.NeedsSemicolon)r4.Lc(S,[23,16,24].slice());return R},xg:function(S){var R=null;r4.fF(S,87);R=op.OO$($New(MP),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.Ar(S,17,true);R.Type=r4.Tt(S);return R},kn:function(S){var R=null;var go=false;var JC=[],JC=[53,24,54,18].slice();r4.Lc(S,[22].slice());go=r4.LF(S)==22;if(go)r4.Gi(S,true);R=op.OO$($New(NE),$AsIntf(S,"IR"));R.Name=r4.e6(S);r4.BK(S,JC,true);R.IsOptional=r4.LF(S)==53;JC.push(53);if(R.IsOptional)r4.BK(S,JC,true);if(r4.LF(S)==54)R.Type=r4.kC(S);return R},Tt:function(S){var R=null;r4.fF(S,17);R=op.OO$($New(NI),$AsIntf(S,"IR"));while(r4.Pp(S,[22].slice(),false)){R.ParameterList.push(r4.kn(S));r4.XI(S,[24,18,23].slice());if(r4.LF(S)==18)break}
r4.XI(S,[18,23].slice());if(r4.BK(S,[54,34].slice(),false))R.ResultType=r4.kC(S);return R},Pp:function(S,an,Gq){var R=false;r4.SX(S);R=S.J1.isIdentifier()||an.indexOf(r4.LF(S))>=0;if((!R)&&Gq)r4.Tm(S,0);return R},Gi:function(S,c1){var R=false;r4.SX(S);R=S.J1.isIdentifier();if((!R)&&c1)r4.Tm(S,69);return R},NV:function(S){var R="";r4.Lc(S,[9].slice());R=r4.e6(S);while(r4.Ar(S,21,false)){r4.Gi(S,true);R+="."+r4.e6(S)}
return R},Ay:function(S){var R=null;r4.fF(S,89);R=op.OO$($New(W8),$AsIntf(S,"IR"));r4.Pp(S,[37,9].slice(),true);switch(r4.LF(S)){case 37:R.Name="*";r4.Ar(S,116,true);r4.Gi(S,true);r4.Ar(S,133,true);r4.Ar(S,9,true);break;case 9:R.Name=S.J1.getTokenValue();break;default:R.Name=r4.e6(S);r4.Ar(S,56,true);r4.Gi(S,true)}
r4.Ar(S,23,true);return R},j5:function(S){var R=null;r4.fF(S,19);R=op.OO$($New(Kk),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.Ar(S,54,true);r4.BK(S,[130,128].slice(),true);R.IsStringIndex=r4.LF(S)==130;r4.Ar(S,20,true);r4.Ar(S,54,true);R.Type=r4.CM(S);return R},Yd:function(S){var R=null;r4.fF(S,107);R=op.OO$($New(ZK),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.BK(S,[25,83,15].slice(),true);if(r4.LF(S)==25){do{R.TypeParameters.push(r4.ka(S))}while(!(r4.LF(S)!=24));r4.BK(S,[83,15].slice(),true)}
if(r4.LF(S)==83){r4.Gi(S,true);R.Extends.push(r4.Rg(S));while(r4.LF(S)==24){r4.Gi(S,true);R.Extends.push(r4.Rg(S))}}
r4.fF(S,15);R.Type=r4.k9(S);r4.fF(S,16);return R},W5:function(S){var R=null;R=op.OO$($New(wE),$AsIntf(S,"IR"));R.Type=r4.Tt(S);if(S.NeedsSemicolon)r4.XI(S,[23,16].slice());return R},BY:function(S){var R=null;var kE=[],kE=[73,82,81,89,125,87,107,102,23,16].slice();r4.fF(S,125);R=op.OO$($New(aX),$AsIntf(S,"IR"));r4.Pp(S,[9].slice(),true);R.Name=r4.NV(S);r4.fF(S,15);r4.BK(S,kE,true);while(r4.LF(S)!=16){switch(r4.LF(S)){case 73:R.Classes.push(r4.Km(S));break;case 82:R.Exports.push(r4.mA(S));break;case 81:r4.kO(S);break;case 87:R.Functions.push(r4.xg(S));break;case 89:r4.Ay(S);break;case 125:R.Modules.push(r4.BY(S));break;case 107:R.Interfaces.push(r4.Yd(S));break;case 102:R.Variables.push(r4.zo(S));break}
r4.BK(S,kE,true)}
r4.fF(S,16);return R},k9:function(S){var R=null;var tm=[],tm=[9,8,92,25,17,19,16,90,78].slice();r4.fF(S,15);R=op.OO$($New(WB),$AsIntf(S,"IR"));r4.Pp(S,tm,true);while(r4.LF(S)!=16){R.Members.push(r4.Bw(S));if(([23,24].indexOf(r4.LF(S))>=0))r4.Pp(S,tm,true)}
r4.fF(S,16);return R},dH:function(S){var R=null;r4.Lc(S,[112,110,111,22].slice());R=op.OO$($New(kj),$AsIntf(S,"IR"));R.Name=r4.e6(S);R.IsRest=r4.LF(S)==22;if(R.IsRest){r4.Gi(S,true);R.Name=r4.e6(S);if(r4.Ar(S,54,false))R.Type=r4.CM(S);r4.fF(S,18);return R}
r4.Lc(S,[112,110,111].slice());switch(r4.LF(S)){case 112:R.AccessibilityModifier=0;r4.Gi(S,false);break;case 110:R.AccessibilityModifier=1;r4.Gi(S,false);break;case 111:R.AccessibilityModifier=2;r4.Gi(S,false);break}
r4.Lc(S,[]);r4.BK(S,[53,54,56,24,18].slice(),true);R.IsOptional=r4.LF(S)==53;if(R.IsOptional)r4.BK(S,[54,56,24,18].slice(),true);if(r4.LF(S)==54)R.Type=r4.kC(S);r4.XI(S,[56,24,18].slice());if(r4.LF(S)==56){r4.Gi(S,true);R.DefaultValue=r4.e6(S)}
r4.XI(S,[24,18].slice());return R},Yx:function(S){var R=null;var hg=[],hg=[69,9,117,128,130,120,103,101,15,17,19].slice();var um=null;r4.XI(S,hg);switch(r4.LF(S)){case 17:R=r4.kC(S);r4.fF(S,18);r4.SX(S);break;case 69:R=zO.p2($New(zO),$AsIntf(S,"IR"),r4.NV(S));if(r4.LF(S)==25){do{$As(R,zO).Arguments.push(r4.fa(S))}while(!(r4.LF(S)!=24));r4.fF(S,27);r4.SX(S)}
break;case 9:R=zO.p2($New(zO),$AsIntf(S,"IR"),S.J1.getTokenValue());r4.SX(S);break;case 117:R=op.OO$($New(Pt),$AsIntf(S,"IR"));r4.SX(S);break;case 128:R=op.OO$($New(Fv),$AsIntf(S,"IR"));r4.SX(S);break;case 103:R=null;r4.SX(S);break;case 101:R=op.OO$($New(TX),$AsIntf(S,"IR"));$As(R,TX).Type=r4.kC(S);break;case 130:R=op.OO$($New(ap),$AsIntf(S,"IR"));r4.SX(S);break;case 120:R=op.OO$($New(Vl),$AsIntf(S,"IR"));r4.SX(S);break;case 15:R=r4.k9(S);r4.SX(S);break;case 19:R=r4.dR(S);r4.SX(S);break}
while(r4.LF(S)==19){um=R;R=op.OO$($New(Uy),$AsIntf(S,"IR"));$As(R,Uy).Type=um;r4.Ar(S,20,true);r4.SX(S)}
return R},BK:function(S,e1,Ep){var R=false;R=e1.indexOf(r4.SX(S))>=0;if((!R)&&Ep)r4.Tm(S,0);return R},Ar:function(S,e2,i3){var R=false;R=r4.SX(S)==e2;if((!R)&&i3)r4.Tm(S,e2);return R},SX:function(S){var R=0;R=S.J1.scan();return R},dR:function(S){var R=null;r4.fF(S,19);R=op.OO$($New(eJ),$AsIntf(S,"IR"));do{R.Types.push(r4.kC(S))}while(!(r4.LF(S)==20));r4.fF(S,20);return R},kC:function(S){var R=null;var uI=[],uI=[69,9,117,128,130,120,103,101,92,15,17,19].slice();var iG=null;r4.BK(S,uI,true);if(r4.LF(S)==17)return r4.Tt(S);if(r4.LF(S)==92)return r4.ua(S);R=r4.Yx(S);while(r4.LF(S)==47){if(!$Is(R,zX)){iG=R;R=op.OO$($New(zX),$AsIntf(S,"IR"));$As(R,zX).Types.push(iG)}
r4.BK(S,uI,true);$As(R,zX).Types.push(r4.Yx(S))}
return R},El:function(S){var R=null;r4.fF(S,132);R=op.OO$($New(HK),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.BK(S,[25,56].slice(),true);if(r4.LF(S)==25){R.TypeParameters.push(r4.ka(S));r4.Ar(S,56,true)}
R.Type=r4.kC(S);r4.fF(S,23);return R},CM:function(S){var R=null;r4.fF(S,54);R=r4.kC(S);return R},fa:function(S){var R=null;r4.XI(S,[25,24].slice());R=op.OO$($New(Wc),$AsIntf(S,"IR"));R.Type=r4.kC(S);r4.XI(S,[27,24].slice());return R},Bw:function(S){var R=null;var Qy=[],xW=[],xW=[9,8,110,92,78,25,17,19,90,78].slice();var vO="",f9=false;r4.Lc(S,xW);if(r4.LF(S)==92)return r4.mE(S);if(([17,25].indexOf(r4.LF(S))>=0))return r4.kU(S);if(r4.LF(S)==19)return r4.j5(S);if(S.J1.isIdentifier()||([9,8,78,90].indexOf(S.J1.getToken())>=0)){vO=r4.e6(S);r4.BK(S,[25,53,54,17].slice(),true);if(r4.LF(S)==25){do{Qy.push(r4.fa(S))}while(!(r4.LF(S)!=24));r4.BK(S,[53,54,17].slice(),true)}
f9=r4.LF(S)==53;if(f9)r4.BK(S,[54,17].slice(),true);switch(r4.LF(S)){case 54:R=r4.iX(S);$As(R,qQ).Nullable=f9;break;case 17:R=r4.W5(S);break}
R.TypeArguments=Qy;R.Name=vO}
return R},ka:function(S){var R=null;r4.XI(S,[25,24].slice());R=op.OO$($New(Ri),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.BK(S,[83,27,24].slice(),true);if(r4.LF(S)==83){R.ExtendsType=r4.kC(S);r4.XI(S,[27,24].slice())}
return R},Rg:function(S){var R=null;r4.Lc(S,[]);R=op.OO$($New(CL),$AsIntf(S,"IR"));R.Name=r4.NV(S);if(r4.LF(S)==25){R.Arguments.push(r4.fa(S));r4.SX(S)}
return R},zo:function(S){var R=null;r4.fF(S,102);R=op.OO$($New(Hj),$AsIntf(S,"IR"));r4.Gi(S,true);R.Name=r4.e6(S);r4.Ar(S,54,true);R.Type=r4.kC(S);return R},m8:function(S,OD){var R="";S.J1=H.createScanner(0,true,0,OD);S.oB=H.createSourceFile("main",OD,0);try{r4.ll$(S)}catch($e){var bq=$W($e);console.error(bq.FMessage)}
R=r4.Rx$(S);return R},Destroy:TObject.Destroy,Rx$:function($){return $.ClassType.Rx($)},ll$:function($){return $.ClassType.ll($)}};r4.$Intf={IR:[]}
function oS(YH){var R="";var Bi=[];if(YH.length==0)return"Unknown";Bi=(YH).split("\\");R=Bi[(Bi.length-1)];Bi=(YH).split("\/");R=Bi[(Bi.length-1)];R=StrReplace(R,"-","_");R=$StrSet(R,1,(R.charAt(0)).toUpperCase());return R};var VY=["Warning","Error","Message"];function Copy$u(s,d){d.V=s.V;d.r=s.r;return d}
function Clone$u($){return{V:$.V,r:$.r}}
var Cb=["vPublic","vProtected","vPrivate"];var op={$ClassName:"TCustomDeclaration",$Parent:TObject,$Init:function($){TObject.$Init($);$.em=null},nA:function(S){++dQ},OO:function(S,PI){S.em=PI;return S},T9:function(S){--dQ},iq:function(S){var R="";R=DupeString("  ",dQ);return R},Destroy:TObject.Destroy,OO$:function($){return $.ClassType.OO.apply($.ClassType,arguments)},xl$:function($){return $.ClassType.xl($)}};var d9={$ClassName:"TCustomType",$Parent:op,$Init:function($){op.$Init($)},Destroy:TObject.Destroy,OO:op.OO,xl:op.xl};var i8={$ClassName:"TCustomNamedType",$Parent:d9,$Init:function($){d9.$Init($)},xl:function(S){var R="";R="J"+i8.lG$(S);return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)},lG$:function($){return $.ClassType.lG($)}};var Oy={$ClassName:"TPredefinedType",$Parent:i8,$Init:function($){i8.$Init($)},xl:function(S){var R="";R=i8.lG$(S);return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)},lG:i8.lG};var Pt={$ClassName:"TVariantType",$Parent:Oy,$Init:function($){Oy.$Init($)},lG:function(S){var R="";R="Variant";return R},Destroy:TObject.Destroy,OO:op.OO,xl:Oy.xl,lG$:function($){return $.ClassType.lG($)}};var Zf={$ClassName:"TNamedDeclaration",$Parent:op,$Init:function($){op.$Init($);$.Name=""},Destroy:TObject.Destroy,OO:op.OO,xl:op.xl};var Hj={$ClassName:"TVariableDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($);$.Type=null},xl:function(S){var R="";console.log("not implemented: TVariableDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var zX={$ClassName:"TUnionType",$Parent:d9,$Init:function($){d9.$Init($);$.Types=[]},xl:function(S){var R="";var rQ=0;var GP=null;R="Variant {";var $t5;for(rQ=0,$t5=(S.Types.length-1);rQ<$t5;rQ++){R+=op.xl$(S.Types[rQ])+" or "}
GP=S.Types[(S.Types.length-1)];R+=(GP)?op.xl$(GP):"void";R+="}";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var CL={$ClassName:"TTypeReference",$Parent:op,$Init:function($){op.$Init($);$.Name="";$.Arguments=[]},xl:function(S){var R="";var T4=0;R="J"+S.Name;if(S.Arguments.length>0){R+=" {"+op.xl$(S.Arguments[0]);var $t6;for(T4=0+1,$t6=S.Arguments.length;T4<$t6;T4++){R+=", "+op.xl$(S.Arguments[T4])}
R+="} "}
return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var Ri={$ClassName:"TTypeParameter",$Parent:op,$Init:function($){op.$Init($);$.Name="";$.ExtendsType=null},xl:function(S){var R="";R=S.Name;if(S.ExtendsType)R+=" extends "+op.xl$(S.ExtendsType);return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var TX={$ClassName:"TTypeOfType",$Parent:i8,$Init:function($){i8.$Init($);$.Type=null},lG:function(S){var R="";R="type of";return R},Destroy:TObject.Destroy,OO:op.OO,xl:i8.xl,lG$:function($){return $.ClassType.lG($)}};var Wc={$ClassName:"TTypeArgument",$Parent:op,$Init:function($){op.$Init($);$.Type=null},xl:function(S){var R="";if(S.Type){R=op.xl$(S.Type)}else R="Variant";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var HK={$ClassName:"TTypeAlias",$Parent:Zf,$Init:function($){Zf.$Init($);$.Type=null;$.TypeParameters=[]},xl:function(S){var R="";R=S.Name+" = "+op.xl$(S.Type);return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var eJ={$ClassName:"TTupleType",$Parent:d9,$Init:function($){d9.$Init($);$.Types=[]},xl:function(S){var R="";R="TupletType";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var ap={$ClassName:"TStringType",$Parent:Oy,$Init:function($){Oy.$Init($)},lG:function(S){var R="";R="String";return R},Destroy:TObject.Destroy,OO:op.OO,xl:Oy.xl,lG$:function($){return $.ClassType.lG($)}};var kj={$ClassName:"TParameter",$Parent:Zf,$Init:function($){Zf.$Init($);$.DefaultValue="";$.IsRest=$.IsOptional=false;$.AccessibilityModifier=0;$.Type=null},xl:function(S){var R="";R=S.Name+": "+op.xl$(S.Type);if(S.DefaultValue!="")R+=" = "+S.DefaultValue;if(S.IsRest)R+=" {...}";return R},fX:function(S,Tn){var R="";R=Xe(S.Name);if(!Tn){R+=": ";if(S.Type){R+=op.xl$(S.Type)}else R+="Variant"}
return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var WB={$ClassName:"TObjectType",$Parent:d9,$Init:function($){d9.$Init($);$.Members=[]},xl:function(S){var R="";var oy=0;var X4=null;var gm=[];op.nA(S.ClassType);gm=S.Members;var $t7;for(oy=0,$t7=gm.length;oy<$t7;oy++){X4=gm[oy];R+=op.xl$(X4)}
op.T9(S.ClassType);R+=op.iq(S.ClassType)+"end;";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var qX={$ClassName:"TNamespaceDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($)},Destroy:TObject.Destroy,OO:op.OO,xl:op.xl};var zO={$ClassName:"TNamedType",$Parent:i8,$Init:function($){i8.$Init($);$.Arguments=[];$.GC=""},p2:function(S,NT,aH){op.OO(S,NT);S.GC=aH;return S},xl:function(S){var R="";var FD=0;var Jz=null;R=i8.xl(S);if(S.Arguments.length>0){var ql=[];R+="{<";ql=S.Arguments;var $t8;for(FD=0,$t8=ql.length;FD<$t8;FD++){Jz=ql[FD];R+=op.xl$(Jz)}
R+=">}"}
return R},lG:function(S){var R="";R=S.GC;return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)},lG$:function($){return $.ClassType.lG($)}};var aX={$ClassName:"TModuleDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($);$.Modules=[];$.Variables=[];$.Exports=[];$.Functions=[];$.Interfaces=[];$.Classes=[]},xl:function(S){var R="";var Gx=0;var Gk=null,OQ=0;var Js=null,Jd=0;var HN=null;R="";if(S.Classes.length+S.Interfaces.length>0){var z7=[],js=[];R+="type"+"\r\n";op.nA(S.ClassType);js=S.Classes;var $t9;for(Gx=0,$t9=js.length;Gx<$t9;Gx++){Gk=js[Gx];R=R+op.xl$(Gk)}
z7=S.Interfaces;var $tA;for(OQ=0,$tA=z7.length;OQ<$tA;OQ++){Js=z7[OQ];R=R+op.xl$(Js)}
op.T9(S.ClassType)}
if(S.Variables.length>0){var tz=[];R+="var"+"\r\n";op.nA(S.ClassType);tz=S.Variables;var $tB;for(Jd=0,$tB=tz.length;Jd<$tB;Jd++){HN=tz[Jd];R=R+op.xl$(HN)}
op.T9(S.ClassType)}
return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var P6={$ClassName:"TCustomTypeMember",$Parent:Zf,$Init:function($){Zf.$Init($);$.TypeParameters=[];$.Visibility=0;$.IsStatic=false;$.TypeArguments=[]},OO:function(S,vD){op.OO(S,vD);S.Visibility=0;return S},Destroy:TObject.Destroy,OO$:function($){return $.ClassType.OO.apply($.ClassType,arguments)},xl:op.xl};var Xy={$ClassName:"TClassTypeMember",$Parent:P6,$Init:function($){P6.$Init($);$.Visibility=0;$.IsStatic=false},Destroy:TObject.Destroy,OO:P6.OO,xl:op.xl};var wE={$ClassName:"TMethodDeclaration",$Parent:Xy,$Init:function($){Xy.$Init($);$.Type=null},xl:function(S){var R="";var Mj="";var GS="";var fo=0,Y6=0;var Gd=null,rF=0;var Bm=[];fo=0;Bm=S.Type.ParameterList;var $tC;for(Y6=0,$tC=Bm.length;Y6<$tC;Y6++){Gd=Bm[Y6];if(Gd.IsOptional)++fo}
Mj=op.iq(S.ClassType);Mj+=(S.Type.ResultType)?"function":"procedure";Mj+=" "+S.Name;GS=";"+((fo>0)?" overload;":"");GS+="\r\n";R="";var $tD;for(rF=0,$tD=fo;rF<=$tD;rF++){R+=Mj+NI.EX(S.Type,rF)+GS}
return R},Destroy:TObject.Destroy,OO:P6.OO,xl$:function($){return $.ClassType.xl($)}};var ZK={$ClassName:"TInterfaceDeclaration",$Parent:op,$Init:function($){op.$Init($);$.TypeParameters=[];$.Name="";$.Extends=[];$.Type=null},xl:function(S){var R="";var Fe=0;var a3=null,jF=0;R+=op.iq(S.ClassType)+"J"+S.Name;if(S.TypeParameters.length>0){var sS=[];R+="{<";sS=S.TypeParameters;var $tE;for(Fe=0,$tE=sS.length;Fe<$tE;Fe++){a3=sS[Fe];R+=op.xl$(a3)}
R+=">}"}
R+=" = class external";if(S.Extends.length>0){R+="(";R+=op.xl$(S.Extends[0]);var $tF;for(jF=0+1,$tF=S.Extends.length;jF<$tF;jF++){R+=", "+op.xl$(S.Extends[jF])}
R+=")"}
R+="\r\n";R+=op.xl$(S.Type);R+="\r\n"+"\r\n";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var Kk={$ClassName:"TIndexDeclaration",$Parent:Xy,$Init:function($){Xy.$Init($);$.IsStringIndex=false;$.Type=null},xl:function(S){var R="";R=op.iq(S.ClassType)+"\/\/ ";R+="property Item["+S.Name+": ";R+=(S.IsStringIndex)?"String":"Integer";R+="]: "+op.xl$(S.Type)+";"+"\r\n";return R},Destroy:TObject.Destroy,OO:P6.OO,xl$:function($){return $.ClassType.xl($)}};var W8={$ClassName:"TImportDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($)},xl:function(S){var R="";console.log("not implemented: TImportDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var NI={$ClassName:"TFunctionType",$Parent:i8,$Init:function($){i8.$Init($);$.ParameterList=[];$.ResultType=null},xl:function(S){var R="";var rh=0;if(S.ParameterList.length>0){R="("+NE.K6(S.ParameterList[0],false);var $tG;for(rh=0+1,$tG=S.ParameterList.length;rh<$tG;rh++){R+="; "+NE.K6(S.ParameterList[rh],false)}
R+=")"}
if(S.ResultType)R+=": "+op.xl$(S.ResultType);return R},EX:function(S,gg){var R="";var AB=false;var dW=0,kI=0;dW=0;if(S.ParameterList.length>0){if(!(S.ParameterList[0].IsOptional&&gg==0)){dW+=(S.ParameterList[0].IsOptional?1:0);AB=S.ParameterList.length>=2&&qh(S.ParameterList[0],S.ParameterList[1])&&((!S.ParameterList[0].IsOptional)||dW<gg);R="("+NE.K6(S.ParameterList[0],AB);var $tH;for(kI=0+1,$tH=S.ParameterList.length;kI<$tH;kI++){if(S.ParameterList[kI].IsOptional&&dW>=gg)break;dW+=(S.ParameterList[kI].IsOptional?1:0);R+=(AB)?", ":"; ";AB=kI+1<S.ParameterList.length&&qh(S.ParameterList[0],S.ParameterList[1])&&((!S.ParameterList[kI].IsOptional)||dW<gg);R+=NE.K6(S.ParameterList[kI],AB)}
R+=")"}}
if(S.ResultType)R+=": "+op.xl$(S.ResultType);return R},lG:function(S){var R="";R="function";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)},lG$:function($){return $.ClassType.lG($)}};var NE={$ClassName:"TFunctionParameter",$Parent:Zf,$Init:function($){Zf.$Init($);$.Type=null;$.IsOptional=false},xl:function(S){var R="";R=Xe(S.Name)+": ";if(S.Type){R+=op.xl$(S.Type)}else R+="Variant";return R},K6:function(S,sQ){var R="";R=Xe(S.Name);if(!sQ){R+=": ";if(S.Type){R+=op.xl$(S.Type)}else R+="Variant"}
return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var MP={$ClassName:"TFunctionDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($);$.Type=null},xl:function(S){var R="";var Zy="";var Rz="";var lP=0,iD=0;var W4=null,iE=0;var IF=[];lP=0;IF=S.Type.ParameterList;var $tI;for(iD=0,$tI=IF.length;iD<$tI;iD++){W4=IF[iD];if(W4.IsOptional)++lP}
Zy=op.iq(S.ClassType);Zy+=(S.Type.ResultType)?"function":"procedure";Zy+=" "+S.Name;Rz=";"+((lP>0)?" overload;":"");Rz+="\r\n";R="";var $tJ;for(iE=0,$tJ=lP;iE<=$tJ;iE++){R+=Zy+NI.EX(S.Type,iE)+Rz}
return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var Fv={$ClassName:"TFloatType",$Parent:Oy,$Init:function($){Oy.$Init($)},lG:function(S){var R="";R="Float";return R},Destroy:TObject.Destroy,OO:op.OO,xl:Oy.xl,lG$:function($){return $.ClassType.lG($)}};var qQ={$ClassName:"TFieldDeclaration",$Parent:Xy,$Init:function($){Xy.$Init($);$.Nullable=false;$.Type=null},xl:function(S){var R="";var SG=0;var LK=null;R=op.iq(S.ClassType)+Xe(S.Name);if(S.TypeArguments.length>0){var Od=[];R+="{<";Od=S.TypeArguments;var $tK;for(SG=0,$tK=Od.length;SG<$tK;SG++){LK=Od[SG];R+=op.xl$(LK)}
R+=">}"}
R+=": "+op.xl$(S.Type)+";";if(S.Nullable)R+=" \/\/ nullable";R+="\r\n";return R},Destroy:TObject.Destroy,OO:P6.OO,xl$:function($){return $.ClassType.xl($)}};var DP={$ClassName:"TExportDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($);$.Bp=false},xl:function(S){var R="";R="";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var GY={$ClassName:"TEnumerationItem",$Parent:op,$Init:function($){op.$Init($);$.Name=$.Value=""},xl:function(S){var R="";R=S.Name;return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var pf={$ClassName:"TEnumerationDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($);$.Items=[]},xl:function(S){var R="";var TK=0;var Ml=null;var tc=[];R+=op.iq(S.ClassType)+"T"+S.Name+" = Variant;"+"\r\n";R+=op.iq(S.ClassType)+"T"+S.Name+"Helper = strict helper for T"+S.Name+"\r\n";op.nA(S.ClassType);tc=S.Items;var $tL;for(TK=0,$tL=tc.length;TK<$tL;TK++){Ml=tc[TK];R+=op.iq(S.ClassType)+"const "+Xe(op.xl$(Ml));if(Ml.Value!=""){try{R+=" = "+(parseInt(Ml.Value,10)).toString()+";"+"\r\n"}catch($e){R+=" = '"+Ml.Value+"';"+"\r\n"}}else R+=" = '"+Ml.Name+"';"+"\r\n"}
op.T9(S.ClassType);R+=op.iq(S.ClassType)+"end;"+"\r\n";R+="\r\n";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var BD={$ClassName:"TDefinitionDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($)},xl:function(S){var R="";console.log("not implemented: TDefinitionDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var Ux={$ClassName:"TConstructorType",$Parent:i8,$Init:function($){i8.$Init($);$.ResultType=null;$.ParameterList=[]},xl:function(S){var R="";var RC=0;if(S.ParameterList.length>0){R="("+NE.K6(S.ParameterList[0],false);var $tM;for(RC=0+1,$tM=S.ParameterList.length;RC<$tM;RC++){R+="; "+NE.K6(S.ParameterList[RC],false)}
R+=")"}
if(S.ResultType)R+=": "+op.xl$(S.ResultType);return R},lG:function(S){var R="";R="constructor";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)},lG$:function($){return $.ClassType.lG($)}};var ss={$ClassName:"TConstructorDeclaration",$Parent:Xy,$Init:function($){Xy.$Init($);$.ParameterList=[];$.Type=null},xl:function(S){var R="";R=op.iq(S.ClassType)+"constructor Create";if(S.Type)R+=op.xl$(S.Type);R+=";"+"\r\n";return R},Destroy:TObject.Destroy,OO:P6.OO,xl$:function($){return $.ClassType.xl($)}};var ph={$ClassName:"TClassDeclaration",$Parent:ZK,$Init:function($){ZK.$Init($);$.Implements=[];$.Members=[]},xl:function(S){var R="";var qa=0;var vd=0;var QG=null;var L2=[];R+=op.iq(S.ClassType)+"J"+S.Name+" = class external '"+S.Name+"'";if(S.Extends.length>0){R+="(";R+=op.xl$(S.Extends[0]);var $tN;for(qa=0+1,$tN=S.Extends.length;qa<$tN;qa++){R+=", "+op.xl$(S.Extends[qa])}
R+=")"}
R+="\r\n";op.nA(S.ClassType);L2=S.Members;var $tO;for(vd=0,$tO=L2.length;vd<$tO;vd++){QG=L2[vd];R+=op.xl$(QG)}
op.T9(S.ClassType);R+=op.iq(S.ClassType)+"end;"+"\r\n"+"\r\n";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var v9={$ClassName:"TCallSignature",$Parent:P6,$Init:function($){P6.$Init($);$.ParameterList=[];$.Type=null;$.TypeParameters=[]},xl:function(S){var R="";var kl=0;var AO=null,lN=0;R="";if(S.TypeParameters.length>0){var OF=[];R+="{<";OF=S.TypeParameters;var $tP;for(kl=0,$tP=OF.length;kl<$tP;kl++){AO=OF[kl];R+=op.xl$(AO)}
R+=">}"}
if(S.ParameterList.length>0){R+="(";var $tQ;for(lN=0,$tQ=(S.ParameterList.length-1);lN<$tQ;lN++){R+=kj.fX(S.ParameterList[lN],false)+"; "}
R+=kj.fX(S.ParameterList[(S.ParameterList.length-1)],false)+")"}
if(S.Type)R+=": "+op.xl$(S.Type);return R},hT:function(S,gt){var R="";var z1=false;var kX=0,m3=0;kX=0;if(S.ParameterList.length>0){if(!(S.ParameterList[0].IsOptional&&gt==0)){kX+=(S.ParameterList[0].IsOptional?1:0);z1=S.ParameterList.length>=2&&ZL(S.ParameterList[0],S.ParameterList[1])&&((!S.ParameterList[0].IsOptional)||kX<gt);R="("+kj.fX(S.ParameterList[0],z1);var $tR;for(m3=0+1,$tR=S.ParameterList.length;m3<$tR;m3++){if(S.ParameterList[m3].IsOptional&&kX>=gt)break;kX+=(S.ParameterList[m3].IsOptional?1:0);R+=(z1)?", ":"; ";z1=m3+1<S.ParameterList.length&&ZL(S.ParameterList[m3],S.ParameterList[m3+1])&&((!S.ParameterList[m3].IsOptional)||kX<gt);R+=kj.fX(S.ParameterList[m3],z1)}
R+=")"}}
if(S.Type)R+=": "+op.xl$(S.Type);return R},Destroy:TObject.Destroy,OO:P6.OO,xl$:function($){return $.ClassType.xl($)}};var Vl={$ClassName:"TBooleanType",$Parent:Oy,$Init:function($){Oy.$Init($)},lG:function(S){var R="";R="Boolean";return R},Destroy:TObject.Destroy,OO:op.OO,xl:Oy.xl,lG$:function($){return $.ClassType.lG($)}};var Uy={$ClassName:"TArrayType",$Parent:d9,$Init:function($){d9.$Init($);$.Type=null},xl:function(S){var R="";R="array of "+op.xl$(S.Type);return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var ey={$ClassName:"TAmbientVariableDeclaration",$Parent:op,$Init:function($){op.$Init($);$.IsConst=false;$.AmbientBindingList=[]},xl:function(S){var R="";var vq=0;var q8=null;var CS=[];CS=S.AmbientBindingList;var $tS;for(vq=0,$tS=CS.length;vq<$tS;vq++){q8=CS[vq];R+=op.iq(S.ClassType)+op.xl$(q8)}
R+=";"+"\r\n";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var tv={$ClassName:"TAmbientBodyElement",$Parent:op,$Init:function($){op.$Init($)},Destroy:TObject.Destroy,OO:op.OO,xl:op.xl};var qj={$ClassName:"TAmbientPropertyMemberDeclaration",$Parent:tv,$Init:function($){tv.$Init($);$.Visibility=0;$.IsStatic=false;$.Name=""},Destroy:TObject.Destroy,OO:op.OO,xl:op.xl};var Pu={$ClassName:"TAmbientPropertyMemberDeclarationProperty",$Parent:qj,$Init:function($){qj.$Init($);$.Type=null},xl:function(S){var R="";R=op.iq(S.ClassType);if(S.IsStatic)R+="class var ";R+=Xe(S.Name);R+=": "+((S.Type)?op.xl$(S.Type):"Variant");R+=";"+"\r\n";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var FJ={$ClassName:"TAmbientPropertyMemberDeclarationMethod",$Parent:qj,$Init:function($){qj.$Init($);$.CallSignature=null},xl:function(S){var R="";var rk="";var vy="";var cP=0,Ij=0;var Nm=null,SO=0;var Cp=[];cP=0;Cp=S.CallSignature.ParameterList;var $tT;for(Ij=0,$tT=Cp.length;Ij<$tT;Ij++){Nm=Cp[Ij];if(Nm.IsOptional)++cP}
rk=op.iq(S.ClassType);rk+=(S.CallSignature.Type)?"function":"procedure";rk+=" "+Xe(S.Name);vy=";"+((cP>0)?" overload;":"");vy+="\r\n";R="";var $tU;for(SO=0,$tU=cP;SO<=$tU;SO++){R+=rk+v9.hT(S.CallSignature,SO)+vy}
return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var ZH={$ClassName:"TAmbientModuleDeclaration",$Parent:op,$Init:function($){op.$Init($);$.Interfaces=[];$.Modules=[];$.Classes=[];$.Functions=[];$.TypeAliases=[];$.IdentifierPath="";$.Enums=[];$.Variables=[]},xl:function(S){var R="";var Du=0,pT=0;var Nz=null,y5=0;var nR=null,Df=0;var yd=null,X6=0;var ke=null,kK=0;var lu=null,Vv=0;var Rf=null,us=0;var om=null,PZ=0;var Q1=null,Yg=0;var bB=null;var Ch=[],Ik=[];R="\/\/"+S.IdentifierPath+"\r\n"+"\r\n";Du=0;Ik=S.Variables;var $tV;for(pT=0,$tV=Ik.length;pT<$tV;pT++){Nz=Ik[pT];if(Nz.IsConst)++Du}
if(Du>0){var x9=[];R+="const"+"\r\n";op.nA(S.ClassType);x9=S.Variables;var $tW;for(y5=0,$tW=x9.length;y5<$tW;y5++){nR=x9[y5];if(nR.IsConst)R=R+op.xl$(nR)}
op.T9(S.ClassType);R+="\r\n"}
if(S.Enums.length+S.Classes.length+S.Interfaces.length>0){var KE=[],sD=[],Z2=[],kR=[];R+="type"+"\r\n";op.nA(S.ClassType);sD=S.Enums;var $tX;for(Df=0,$tX=sD.length;Df<$tX;Df++){yd=sD[Df];R+=op.xl$(yd)}
KE=S.Classes;var $tY;for(X6=0,$tY=KE.length;X6<$tY;X6++){ke=KE[X6];R+=op.xl$(ke)}
kR=S.Interfaces;var $tZ;for(kK=0,$tZ=kR.length;kK<$tZ;kK++){lu=kR[kK];R+=op.xl$(lu)}
Z2=S.TypeAliases;var $ta;for(Vv=0,$ta=Z2.length;Vv<$ta;Vv++){Rf=Z2[Vv];R+=op.xl$(Rf)}
op.T9(S.ClassType)}
Ch=S.Modules;var $tb;for(us=0,$tb=Ch.length;us<$tb;us++){om=Ch[us];R+=op.xl$(om)}
if(S.Functions.length>0){var Rq=[];Rq=S.Functions;var $tc;for(PZ=0,$tc=Rq.length;PZ<$tc;PZ++){Q1=Rq[PZ];R+=op.xl$(Q1)}
R+="\r\n"}
if(S.Variables.length-Du>0){var y1=[];R+="var"+"\r\n";op.nA(S.ClassType);y1=S.Variables;var $td;for(Yg=0,$td=y1.length;Yg<$td;Yg++){bB=y1[Yg];if(!bB.IsConst)R=R+op.xl$(bB)}
op.T9(S.ClassType);R+="\r\n"}
return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var mV={$ClassName:"TAmbientFunctionDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($);$.CallSignature=null},xl:function(S){var R="";var EY="";var Ev="";var xL=0,fZ=0;var Qi=null,se=0;var RZ=[];xL=0;RZ=S.CallSignature.ParameterList;var $te;for(fZ=0,$te=RZ.length;fZ<$te;fZ++){Qi=RZ[fZ];if(Qi.IsOptional)++xL}
EY=op.iq(S.ClassType);EY+=(S.CallSignature.Type)?"function":"procedure";EY+=" "+S.Name;Ev=";"+((xL>0)?" overload;":"");Ev+="\r\n";R="";var $tf;for(se=0,$tf=xL;se<=$tf;se++){R+=EY+v9.hT(S.CallSignature,se)+Ev}
return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var yK={$ClassName:"TAmbientDeclaration",$Parent:Zf,$Init:function($){Zf.$Init($);$.Variables=[];$.Namespaces=[];$.Modules=[];$.Classes=[];$.Functions=[];$.Enums=[]},xl:function(S){var R="";var aJ=0;var zj=null,AX=0;var S6=null,T1=0;var wR=null,TV=0;var j6=null;var M8=[],eM=[],iQ=[];iQ=S.Functions;var $tg;for(aJ=0,$tg=iQ.length;aJ<$tg;aJ++){zj=iQ[aJ];R+=op.xl$(zj)}
eM=S.Modules;var $th;for(AX=0,$th=eM.length;AX<$th;AX++){S6=eM[AX];R+=op.xl$(S6)}
if(S.Classes.length>0){var k1=[];R+="type"+"\r\n";op.nA(S.ClassType);k1=S.Classes;var $ti;for(T1=0,$ti=k1.length;T1<$ti;T1++){wR=k1[T1];R=R+op.xl$(wR)}
op.T9(S.ClassType)}
if(S.Variables.length>0){M8=S.Variables;var $tj;for(TV=0,$tj=M8.length;TV<$tj;TV++){j6=M8[TV];R=R+op.xl$(j6)}}
return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var qF={$ClassName:"TAmbientConstructorDeclaration",$Parent:tv,$Init:function($){tv.$Init($);$.ParameterList=[]},xl:function(S){var R="";var lf=0;R=op.iq(S.ClassType)+"constructor Create";if(S.ParameterList.length>0){R+="(";var $tk;for(lf=0,$tk=(S.ParameterList.length-1);lf<$tk;lf++){R+=NE.K6(S.ParameterList[lf],false)+"; "}
R+=NE.K6(S.ParameterList[(S.ParameterList.length-1)],false)+")";R+=")"}
R+=";"+"\r\n";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var MI={$ClassName:"TAmbientClassDeclaration",$Parent:op,$Init:function($){op.$Init($);$.Members=[];$.Name="";$.Extends=[];$.Implements=[]},xl:function(S){var R="";var ag=0;var mX=0,VQ=0;var p6=null,mL=0;var f3=[];R+=op.iq(S.ClassType)+"J"+S.Name+" = class external '"+S.Name+"'";if(S.Extends.length>0){R+="(";R+=op.xl$(S.Extends[0]);var $tl;for(ag=0+1,$tl=S.Extends.length;ag<$tl;ag++){R+=", "+op.xl$(S.Extends[ag])}
R+=")"}
R+="\r\n";mX=0;op.nA(S.ClassType);f3=S.Members;var $tm;for(VQ=0,$tm=f3.length;VQ<$tm;VQ++){p6=f3[VQ];mL=($Is(p6,qj))?$As(p6,qj).Visibility:0;if(mX!=mL){op.T9(S.ClassType);R+=op.iq(S.ClassType);switch(mL){case 0:R+="public"+"\r\n";break;case 1:R+="protected"+"\r\n";break;case 2:R+="private"+"\r\n";break}
op.nA(S.ClassType);mX=mL}
R+=op.xl$(p6)}
op.T9(S.ClassType);R+=op.iq(S.ClassType)+"end;"+"\r\n"+"\r\n";return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var Vs={$ClassName:"TAmbientBinding",$Parent:Zf,$Init:function($){Zf.$Init($);$.Type=null},xl:function(S){var R="";R=S.Name+": "+op.xl$(S.Type);return R},Destroy:TObject.Destroy,OO:op.OO,xl$:function($){return $.ClassType.xl($)}};var JY=["amPublic","amPrivate","amProtected"];function ZL(Hr,Am){var R=false;R=(!(Hr.Type!==null)!=!(Hr.Type!==null));if(R&&(Hr.Type!==null))R=op.xl$(Hr.Type)==op.xl$(Am.Type);return R};function qh(Cl,mH){var R=false;R=(!(Cl.Type!==null)!=!(Cl.Type!==null));if(R&&(Cl.Type!==null))R=op.xl$(Cl.Type)==op.xl$(mH.Type);return R};function Xe(rB){var R="";R=rB;if((["type","export","label","public","protected","private","abstract","default","const","constructor","property","function","class","interface","string","end","uses","div","object"].indexOf((rB).toLowerCase())>=0))R="&"+R;if((["length","include","exclude"].indexOf((rB).toLowerCase())>=0))R="_"+R;return R};var H=null;var H=require("typescript");var dQ=0;var U=[],QL="",Ct="",ZW=null;var ZW=kP();U=process.argv;U.splice(0,2);if(U.length==0){return"Usage: ts2pas inputfile [outputfile]"}
QL=U[0];Ct=U[0]+".pas";if(U.length==2)Ct=U[1];dY(QL,Ct);
