#! /usr/bin/env node
/**
* ts2pas
* https://github.com/CWBudde/TS2Pas
*
* Copyright (c) 2016 Christian-W. Budde
* Licensed under the MIT license.
*/


var TObject={$ClassName:"TObject",$Parent:null,ClassName:function(s){return s.$ClassName},ClassType:function(s){return s},ClassParent:function(s){return s.$Parent},$Init:function(){},Create:function(s){return s},Destroy:function(s){for(var prop in s)if(s.hasOwnProperty(prop))delete s.prop},Destroy$:function(s){return s.ClassType.Destroy(s)},Free:function(s){if(s!==null)s.ClassType.Destroy(s)}}
function StrReplace(s,o,n){return o?s.replace(new RegExp(StrRegExp(o),"g"),n):s}
function StrRegExp(s){return s.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")}
function StrBefore(s,d){if(!d)return s;var p=s.indexOf(d);return(p<0)?s:s.substr(0,p)}
function StrAfter(s,d){if(!d)return"";var p=s.indexOf(d);return(p<0)?"":s.substr(p+d.length)}
var Exception={$ClassName:"Exception",$Parent:TObject,$Init:function(){var FMessage=""},Create:function(s,Msg){s.FMessage=Msg;return s}}
function stringRepeat(s,n){if(n<1)return'';var r='';while(n>0){if(n&1)r+=s;n>>=1,s+=s};return r};function DupeString(s,n){return stringRepeat(s,n)}
function $W(e){return e.ClassType?e:Exception.Create($New(Exception),e.constructor.name+", "+e.message)}
function $StrSet(s,i,v,z){if(i<1)throw Exception.Create($New(Exception),"Lower bound exceeded! Index "+i.toString()+z);if(i>s.length)throw Exception.Create($New(Exception),"Upper bound exceeded! Index "+i.toString()+z);return s.substring(0,i-1)+v+s.substring(i)}
function $New(c){var i={ClassType:c};c.$Init(i);return i}
function $Is(o,c){if(o===null)return false;return $Inh(o.ClassType,c)};function $Inh(s,c){if(s===null)return false;while((s)&&(s!==c))s=s.$Parent;return(s)?true:false};function $Extend(base,sub,props){function F(){};F.prototype=base.prototype;sub.prototype=new F();sub.prototype.constructor=sub;for(var n in props){if(props.hasOwnProperty(n)){sub.prototype[n]=props[n]}}}
function $AsIntf(o,i){if(o===null)return null;var r=o.ClassType.$Intf[i].map(function(e){return function(){var arg=Array.prototype.slice.call(arguments);arg.splice(0,0,o);return e.apply(o,arg)}});r.O=o;return r};function $As(o,c){if((o===null)||$Is(o,c))return o;throw Exception.Create($New(Exception),"Cannot cast instance of type \""+o.ClassType.$ClassName+"\" to class \""+c.$ClassName+"\"")}
function JError(){}
$Extend(Object,JError,{});function Mr(ng,Ua){var hE="";hE=StrBefore(ng,".d.ts");if(ng==hE)ng+=".d.ts";B5.readFile(ng,function(Z1,fK){var E9="",bd=null,jU="";if(!fK)return;E9=fK.toString("utf8");bd=f6.v9($New(f6));bd.Name=hE;jU=f6.Vg(bd,E9);B5.writeFile(Ua,jU,function(I5){});bd=null})};function qS(cl){Mr(cl,StrBefore(cl,".d.ts")+".pas")};function ja(){var hb=function(){for(var r=[],i=0;i<42;i++)r.push("");return r}(),cy=0;var QF="";hb=["abs\/abs.d.ts","absolute\/absolute.d.ts","accounting\/accounting.d.ts","acc-wizard\/acc-wizard.d.ts","amazon-product-api\/amazon-product-api.d.ts","amcharts\/AmCharts.d.ts","amplifyjs\/amplifyjs.d.ts","box2d\/box2dweb.d.ts","browserify\/browserify.d.ts","d3\/d3.d.ts","devextreme\/devextreme.d.ts","dojo\/dijit.d.ts","dojo\/dojo.d.ts","easeljs\/easeljs.d.ts","ember\/ember.d.ts","express\/express.d.ts","fabricjs\/fabricjs.d.ts","gruntjs\/gruntjs.d.ts","hapi\/hapi.d.ts","jquery\/jquery.d.ts","jquerymobile\/jquerymobile.d.ts","kendo-ui\/kendo-ui.d.ts","leapmotionTS\/LeapMotionTS.d.ts","linq\/linq.d.ts","matter-js\/matter-js.d.ts","office-js\/office-js.d.ts","openlayers\/openlayers.d.ts","phantom\/phantom.d.ts","phantomjs\/phantomjs.d.ts","phonegap\/phonegap.d.ts","plottable\/plottable.d.ts","preloadjs\/preloadjs.d.ts","socket.io\/socket.io.d.ts","soundjs\/soundjs.d.ts","titanium\/titanium.d.ts","tweenjs\/tweenjs.d.ts","typescript\/typescript.d.ts","ui-grid\/ui-grid.d.ts","webix\/webix.d.ts","winjs\/winjs.d.ts","winrt\/winrt.d.ts","youtube\/youtube.d.ts"];for(cy=0;cy<=41;cy++){QF=hb[cy];kM("\/DefinitelyTyped\/DefinitelyTyped\/master\/"+QF)}};function ib(SK){if(SK==StrBefore(SK,".d.ts"))SK+=".d.ts";B5.readFile(SK,function(qD,ik){var wO="",x3=null;wO=ik.toString("utf8");x3=Z.createSourceFile(SK,wO,2,true);tg(x3)})};function kM(a5){var ez=null,Vy=null,LF=null,U4=null;ez=e9();Vy=new Object();Vy.hostname="raw.githubusercontent.com";Vy.path=a5;console.log("Fetching: "+a5);LF=f6.v9($New(f6));U4=ez.get(Vy,function(RG){var yZ="",r4S=[],eQ="",tS="";yZ="";r4S=(a5).split("\/");eQ=StrBefore(r4S[(r4S.length-1)],".d.ts");tS=eQ+".pas";RG.on("data",function(cp){yZ+=String(cp)});RG.on("end",function(nu){var eV="";console.log("Translating: "+eQ);LF.Name=eQ;eV=f6.Vg(LF,yZ);console.log("Writing: "+tS);B5.writeFile(tS,eV,function(cu){})})});U4.on("error",function(S7){console.log("Error: ",S7)})};function tg(La){O6(La)};function O6(dY){var R=undefined;switch(dY.kind){case 9:console.log(dY.text);break;case 69:console.log(dY.text);break;case 151:console.log(dY.text);break;case 122:console.log("declare");break;case 135:console.log(dY.left);break;default:console.log(dY.kind)}
Z.forEachChild(dY,O6);return R};function Copy$pf(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$pf($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Copy$t7(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$t7($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Copy$Vl(s,d){d.persistent=s.persistent;return d}
function Clone$Vl($){return{persistent:$.persistent}}
function Copy$Q3(s,d){d.curr=s.curr;d.prev=s.prev;return d}
function Clone$Q3($){return{curr:$.curr,prev:$.prev}}
function Copy$aX(s,d){d.curr=s.curr;d.prev=s.prev;return d}
function Clone$aX($){return{curr:$.curr,prev:$.prev}}
function Copy$v4(s,d){d.persistent=s.persistent;d.interval=s.interval;return d}
function Clone$v4($){return{persistent:$.persistent,interval:$.interval}}
function Copy$ED(s,d){d.encoding=s.encoding;d.flag=s.flag;return d}
function Clone$ED($){return{encoding:$.encoding,flag:$.flag}}
function Copy$DM(s,d){d.encoding=s.encoding;d.flag=s.flag;return d}
function Clone$DM($){return{encoding:$.encoding,flag:$.flag}}
function Copy$FR(s,d){d.flags=s.flags;d.encoding=s.encoding;d.string_=s.string_;return d}
function Clone$FR($){return{flags:$.flags,encoding:$.encoding,string_:$.string_}}
function Copy$OF(s,d){d.bufferSize=s.bufferSize;d.encoding=s.encoding;d.fd=s.fd;d.mode=s.mode;d.flags=s.flags;return d}
function Clone$OF($){return{bufferSize:$.bufferSize,encoding:$.encoding,fd:$.fd,mode:$.mode,flags:$.flags}}
function Copy$ei(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$ei($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function Copy$s1(s,d){d.encoding=s.encoding;d.mode=s.mode;d.flag=s.flag;return d}
function Clone$s1($){return{encoding:$.encoding,mode:$.mode,flag:$.flag}}
function r0W(){var R=null;R=require("fs");return R};function U3(){var R=null;R=require("stream");return R};function Er(){var R=null;R=require("events");return R};function e9(){var R=null;R=require("https");return R};var I8={$ClassName:"TServer_address_result_object_tls",$Parent:TObject,$Init:function($){TObject.$Init($);$.port=0;$.family=$.address=""},Destroy:TObject.Destroy};var Ki={$ClassName:"TServer_addContext_credentials_object",$Parent:TObject,$Init:function($){TObject.$Init($);$.key=$.cert=$.ca=""},Destroy:TObject.Destroy};function HB(){var R=null;R=require("tls");return R};var m4={$ClassName:"TClearTextStream_getCipher_object",$Parent:TObject,$Init:function($){TObject.$Init($);$.name=$.version=""},Destroy:TObject.Destroy};var Ar={$ClassName:"TClearTextStream_address_object",$Parent:TObject,$Init:function($){TObject.$Init($);$.port=0;$.family=$.address=""},Destroy:TObject.Destroy};function Jz(){var R=null;R=require("crypto");return R};function Copy$jg(s,d){d.allowHalfOpen=s.allowHalfOpen;return d}
function Clone$jg($){return{allowHalfOpen:$.allowHalfOpen}}
function Copy$TB(s,d){d.allowHalfOpen=s.allowHalfOpen;return d}
function Clone$TB($){return{allowHalfOpen:$.allowHalfOpen}}
function Copy$Vp(s,d){d.allowHalfOpen=s.allowHalfOpen;return d}
function Clone$Vp($){return{allowHalfOpen:$.allowHalfOpen}}
function ww(){var R=null;R=require("net");return R};function Copy$jY(s,d){d.fd=s.fd;d.type=s.type;d.allowHalfOpen=s.allowHalfOpen;return d}
function Clone$jY($){return{fd:$.fd,type:$.type,allowHalfOpen:$.allowHalfOpen}}
var PN={$ClassName:"JServerAddressResult",$Parent:TObject,$Init:function($){TObject.$Init($);$.port=0;$.family=$.address=""},Destroy:TObject.Destroy};function Rq(){var R=null;R=require("http");return R};var qb=["Warning","Error","Message"];function Copy$r(s,d){d.x=s.x;d.V=s.V;return d}
function Clone$r($){return{x:$.x,V:$.V}}
var f6={$ClassName:"TTranslator",$Parent:TObject,$Init:function($){TObject.$Init($);$.NeedsSemicolon=false;$.Name="";$.QU=[];$.DT=[];$.uW=[];$.li=[];$.tn=$.kg=null},XW:function(S){return S.tn.getTokenText()},yB:function(S){return S.tn.getToken()},tO:function(S,nI){if(!(S.tn.isIdentifier()||nI.indexOf(f6.yB(S))>=0))f6.HO(S,0)},Qj:function(S,vx){if(!(vx.indexOf(f6.yB(S))>=0))f6.HO(S,0)},gf:function(S,QO){if(f6.yB(S)!=QO)f6.HO(S,QO)},kP:function(S){var R="";var l6=0;var wD=null,pi=0;var kB=null,hI=0;var B9=null,uc=0;var HA=null;var wW=[],Cr=[],C3=[];R="unit "+Lu(S.Name)+";"+"\r\n"+"\r\n";R+="interface"+"\r\n"+"\r\n";C3=S.DT;var $t1;for(l6=0,$t1=C3.length;l6<$t1;l6++){wD=C3[l6];R=R+qq.Bs$(wD)}
Cr=S.li;var $t2;for(pi=0,$t2=Cr.length;pi<$t2;pi++){kB=Cr[pi];R=R+qq.Bs$(kB)}
if(S.uW.length>0){var SI=[];R+="type"+"\r\n";qq.JU(qq);SI=S.uW;var $t3;for(hI=0,$t3=SI.length;hI<$t3;hI++){B9=SI[hI];R=R+qq.Bs$(B9)}
qq.VT(qq)}
wW=S.QU;var $t4;for(uc=0,$t4=wW.length;uc<$t4;uc++){HA=wW[uc];R=R+qq.Bs$(HA)}
return R},v9:function(S){S.NeedsSemicolon=false;return S},HO:function(S,X7){var Mgv=null,bv="";Mgv=Z.getLineAndCharacterOfPosition(S.kg,S.tn.getTokenPos());bv=("Unknown token \""+f6.XW(S).toString()+"\" in this context ("+(Mgv.line+1).toString()+":"+(Mgv.character+1).toString()+")");if(X7>0)bv+=("; Expected ("+X7.toString()+")");console.trace("Error in "+S.Name);throw Exception.Create($New(Exception),bv)},YN:function(S){var R=null;f6.tO(S,[]);R=qq.ue$($New(YY),$AsIntf(S,"lJ"));R.Name=f6.XW(S);if(f6.qW(S,54,false))R.Type=f6.Hv(S);if(S.NeedsSemicolon)f6.Qj(S,[23,24].slice());return R},Cx:function(S,HeT){do{HeT.push(f6.YN(S));if(f6.yB(S)==23)break;if(f6.yB(S)!=24)break;if(!f6.Gm(S,false))break}while(!(f6.yB(S)==23||(!S.tn.isIdentifier())||(!S.NeedsSemicolon)&&(!S.tn.isIdentifier())))},dZ:function(S){var R=null;var fV=0,Xa=false;f6.tO(S,[121,110,111,112,113].slice());if(f6.yB(S)==121)return f6.UD(S);fV=0;switch(f6.yB(S)){case 112:fV=0;f6.SH(S,[113].slice(),true);break;case 111:fV=1;f6.SH(S,[113].slice(),true);break;case 110:fV=2;f6.SH(S,[113].slice(),true);break}
Xa=f6.yB(S)==113;if(Xa)f6.Gm(S,true);R=f6.xQ(S);$As(R,jL).IsStatic=Xa;$As(R,jL).Visibility=fV;if(S.NeedsSemicolon)f6.Qj(S,[23,16].slice());return R},xv:function(S){var R=null;var C9=[],C9=[121,110,111,112,113,16,23].slice();f6.gf(S,73);R=qq.ue$($New(L7),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.OM(S,[83,106,15,25].slice(),true);if(f6.yB(S)==83){f6.Gm(S,true);R.Extends.push(f6.rV(S))}
if(f6.yB(S)==106){f6.Gm(S,true);R.Implements.push(f6.Gx(S));while(f6.yB(S)==24){f6.Gm(S,true);R.Implements.push(f6.Gx(S))}}
if(f6.yB(S)==25){do{f6.nf(S)}while(!(f6.yB(S)!=24));f6.OM(S,[15].slice(),true)}
f6.gf(S,15);f6.SH(S,C9,false);while(f6.yB(S)!=16){R.Members.push(f6.dZ(S));if(f6.yB(S)==23)f6.SH(S,C9,false)}
f6.gf(S,16);return R},UD:function(S){var R=null;f6.gf(S,121);f6.qW(S,17,true);R=qq.ue$($New(Yv),$AsIntf(S,"lJ"));while(f6.Gm(S,false)){R.ParameterList.push(f6.sJ(S));f6.Qj(S,[24,18,23].slice());if(f6.yB(S)==18)break}
f6.Qj(S,[18,23].slice());if(f6.yB(S)!=23)f6.qW(S,23,true);return R},Sa:function(S){var R=null;f6.gf(S,122);R=qq.ue$($New(co),$AsIntf(S,"lJ"));f6.OM(S,[102,108,74,87,73,81,125,126].slice(),true);switch(f6.yB(S)){case 102:case 108:case 74:R.Variables.push(f6.ij(S));break;case 87:R.Functions.push(f6.Ik(S));break;case 73:R.Classes.push(f6.xv(S));break;case 81:R.Enums.push(f6.ab(S));break;case 125:R.Modules.push(f6.LQ(S));break;case 126:R.Namespaces.push(f6.Co(S));break}
return R},ab:function(S){var R=null;R=f6.mj(S);return R},Ik:function(S){var R=null;f6.gf(S,87);R=qq.ue$($New(tV),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.OM(S,[17,25].slice(),true);R.CallSignature=f6.pb(S);if(S.NeedsSemicolon)f6.Qj(S,[23].slice());return R},LQ:function(S){var R=null;var zT=[],zT=[82,102,108,74,132,87,73,107,81,125,126,89,16,23].slice();var xr=false,lt=null;f6.gf(S,125);R=qq.ue$($New(gG),$AsIntf(S,"lJ"));f6.SH(S,[9].slice(),true);R.IdentifierPath=f6.Gx(S);f6.gf(S,15);f6.OM(S,zT,true);while(f6.yB(S)!=16){xr=f6.yB(S)==82;if(xr){f6.OM(S,zT.concat([77,56]),true);if(f6.yB(S)==77){xr=false;f6.Gm(S,false);f6.OM(S,zT,true)}
if(f6.yB(S)==56){xr=false;f6.Gm(S,false);f6.OM(S,zT,true)}}
switch(f6.yB(S)){case 102:case 108:R.Variables.push(f6.ij(S));break;case 74:f6.SH(S,[81].slice(),false);if(f6.yB(S)==81){R.Enums.push(f6.ab(S))}else{lt=qq.ue$($New(l2),$AsIntf(S,"lJ"));lt.IsConst=true;f6.Cx(S,lt.AmbientBindingList);R.Variables.push(lt)}
f6.OM(S,zT,true);break;case 132:R.TypeAliases.push(f6.iM(S));break;case 87:R.Functions.push(f6.Ik(S));break;case 126:R.Namespaces.push(f6.jZ(S));f6.OM(S,zT,true);break;case 73:R.Classes.push(f6.YH(S));f6.OM(S,zT,true);break;case 125:R.Modules.push(f6.LQ(S));f6.OM(S,zT,true);break;case 107:R.Interfaces.push(f6.P6(S));f6.OM(S,zT,true);break;case 89:f6.t8(S);if(!S.NeedsSemicolon)f6.OM(S,zT,true);break;case 81:f6.mj(S);f6.OM(S,zT,true);break}
if(f6.yB(S)==23)f6.OM(S,zT,true)}
f6.gf(S,16);return R},Co:function(S){var R=null;var xP=[],xP=[73,122,82,81,89,87,107,102,23,16].slice();var zE=false;f6.gf(S,126);f6.SH(S,[9].slice(),true);R=qq.ue$($New(nJ),$AsIntf(S,"lJ"));R.Name=f6.Gx(S);f6.gf(S,15);f6.OM(S,xP,true);while(f6.yB(S)!=16){zE=f6.yB(S)==82;if(zE)f6.OM(S,xP,true);switch(f6.yB(S)){case 73:R.Classes.push(f6.xv(S));break;case 81:f6.mj(S);break;case 87:R.Functions.push(f6.Ik(S));break;case 89:f6.t8(S);break;case 107:R.Interfaces.push(f6.P6(S));break;case 102:R.Variables.push(f6.ij(S));break}
f6.OM(S,xP,true)}
f6.gf(S,16);return R},xQ:function(S){var R=null;var Aa="";f6.tO(S,[]);Aa=f6.XW(S);f6.OM(S,[54,17,23].slice(),true);if(f6.yB(S)==17){R=f6.wo(S)}else R=f6.Pc(S);R.Name=Aa;if(S.NeedsSemicolon)f6.tO(S,[23,16,24].slice());return R},wo:function(S){var R=null;f6.gf(S,17);R=qq.ue$($New(eJ),$AsIntf(S,"lJ"));R.CallSignature=f6.pb(S);f6.Qj(S,[18,23,112,111,110].slice());if(f6.yB(S)!=23)f6.qW(S,23,true);return R},Pc:function(S){var R=null;R=qq.ue$($New(Tf),$AsIntf(S,"lJ"));if(f6.yB(S)==54)R.Type=f6.Xv(S);return R},ij:function(S){var R=null;f6.Qj(S,[102,108,74].slice());R=qq.ue$($New(l2),$AsIntf(S,"lJ"));R.IsConst=f6.yB(S)==74;f6.Gm(S,true);f6.Cx(S,R.AmbientBindingList);return R},pb:function(S){var R=null;f6.Qj(S,[17,25].slice());R=qq.ue$($New(EH),$AsIntf(S,"lJ"));if(f6.yB(S)==25){do{R.TypeParameters.push(f6.nf(S))}while(!(f6.yB(S)!=24));f6.qW(S,17,true)}
f6.gf(S,17);f6.SH(S,[112,110,111,22,18].slice(),true);while(f6.yB(S)!=18){R.ParameterList.push(f6.Vu(S));if(f6.yB(S)==24)f6.SH(S,[22].slice(),false)}
f6.Qj(S,[18].slice());f6.OM(S,[54,23].slice(),true);if(f6.yB(S)==54)R.Type=f6.Xv(S);return R},YH:function(S){var R=null;var iT=[],iT=[83,106,15,25].slice();f6.gf(S,73);R=qq.ue$($New(Pu),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.OM(S,iT,true);if(f6.yB(S)==25){iT.push(25);do{R.TypeParameters.push(f6.nf(S))}while(!(f6.yB(S)!=24));f6.gf(S,27);f6.OM(S,iT,true)}
if(f6.yB(S)==83){f6.Gm(S,true);R.Extends.push(f6.rV(S))}
if(f6.yB(S)==106){f6.Gm(S,true);R.Implements.push(f6.rV(S));while(f6.yB(S)==24){f6.Gm(S,true);R.Implements.push(f6.rV(S))}}
f6.gf(S,15);f6.DV(S,R);return R},FU:function(S){var R=null;var LH=[],SW=[],SW=[72,75,76,77,78,82,85,88,105].slice();var y5="",LT=false;f6.tO(S,[92,9,19].concat(SW));if(f6.yB(S)==19)return f6.tT(S);y5=f6.XW(S);f6.OM(S,[25,53,54,17,23].slice(),true);if(f6.yB(S)==25){do{LH.push(f6.nf(S))}while(!(f6.yB(S)!=24));f6.OM(S,[53,54,17,23].slice(),true)}
LT=f6.yB(S)==53;if(LT)f6.OM(S,[54,23].slice(),true);switch(f6.yB(S)){case 54:case 23:R=f6.cw(S);$As(R,ro).Nullable=LT;break;case 17:if((y5).toLowerCase()=="constructor"){R=f6.yM(S)}else R=f6.xk(S);break}
R.Name=y5;R.TypeParameters=LH;if(S.NeedsSemicolon)f6.Qj(S,[23,24,16].slice());return R},DV:function(S,re){var Qa=[],Qa=[92,9,82,16,23,19].slice();var ME=0,Z6=false,WI=null;f6.gf(S,15);f6.SH(S,Qa,false);while(f6.yB(S)!=16){ME=0;switch(f6.yB(S)){case 112:ME=0;f6.SH(S,[92].slice(),true);break;case 111:ME=1;f6.SH(S,[92].slice(),true);break;case 110:ME=2;f6.SH(S,[92].slice(),true);break}
Z6=f6.yB(S)==113;if(Z6)f6.SH(S,[92,17].slice(),true);WI=f6.FU(S);WI.Visibility=ME;WI.IsStatic=Z6;re.Members.push(WI);if(f6.yB(S)==23)f6.SH(S,Qa,false)}},yM:function(S){var R=null;R=qq.ue$($New(my),$AsIntf(S,"lJ"));R.Type=f6.Xs(S);if(S.NeedsSemicolon)f6.Qj(S,[23,16].slice());return R},tc:function(S){var R=null;f6.gf(S,92);R=qq.ue$($New(my),$AsIntf(S,"lJ"));f6.OM(S,[17,25].slice(),true);if(f6.yB(S)==25){do{R.TypeParameters.push(f6.nf(S))}while(!(f6.yB(S)!=24));f6.OM(S,[17].slice(),true)}
f6.gf(S,17);f6.SH(S,[112,110,111,22,18].slice(),true);while(f6.yB(S)!=18){R.ParameterList.push(f6.Vu(S));if(f6.yB(S)==24)f6.SH(S,[22].slice(),false)}
f6.gf(S,18);f6.qW(S,54,true);R.Type=f6.Hv(S);return R},EU:function(S){var R=null;f6.gf(S,92);R=qq.ue$($New(O1),$AsIntf(S,"lJ"));f6.qW(S,17,true);while(f6.SH(S,[22].slice(),false)){R.ParameterList.push(f6.sJ(S));f6.Qj(S,[24,18,23].slice());if(f6.yB(S)==18)break}
f6.Qj(S,[18,23].slice());if(f6.OM(S,[54,34].slice(),false))R.ResultType=f6.Xv(S);return R},zu:function(S){var yw=[],yw=[82,122,107,125,89,1].slice();f6.OM(S,yw,true);while(f6.yB(S)!=1){switch(f6.yB(S)){case 82:f6.OM(S,yw,true);continue;break;case 122:S.QU.push(f6.Sa(S));break;case 107:S.uW.push(f6.P6(S));break;case 125:S.li.push(f6.YP(S));break;case 89:S.DT.push(f6.t8(S));break}
if(([16,23].indexOf(f6.yB(S))>=0))f6.OM(S,yw,true)}},mj:function(S){var R=null;var ZJ=[],ZJ=[81,77,78,89,96].slice();f6.gf(S,81);R=qq.ue$($New(dd),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.qW(S,15,true);f6.SH(S,[16].concat(ZJ),true);if(f6.yB(S)!=16){do{R.Items.push(f6.BK(S));if(f6.yB(S)==16)break}while(!(!f6.SH(S,ZJ,false)))}
f6.gf(S,16);return R},BK:function(S){var R=null;var SR=[],SR=[81,77,78,89,96].slice();f6.tO(S,SR);R=qq.ue$($New(CR),$AsIntf(S,"lJ"));R.Name=f6.XW(S);if(f6.qW(S,56,false)){f6.qW(S,8,true);R.Value=f6.XW(S);f6.Vm(S)}
f6.Qj(S,[24,16].slice());return R},xp:function(S){var R=null;f6.gf(S,82);R=qq.ue$($New(Wb),$AsIntf(S,"lJ"));f6.SH(S,[77].slice(),true);R.RI=f6.yB(S)==82||(f6.XW(S)).toLowerCase()=="default";if(R.RI)f6.Gm(S,true);R.Name=f6.XW(S);f6.qW(S,23,true);return R},w9:function(S){var R=null;f6.gf(S,87);R=qq.ue$($New(ih),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.OM(S,[17].slice(),true);R.Type=f6.Xs(S);return R},sJ:function(S){var R=null;var XG=false;var nZ=[],nZ=[53,24,54,18].slice();f6.tO(S,[22].slice());XG=f6.yB(S)==22;if(XG)f6.Gm(S,true);R=qq.ue$($New(Zg),$AsIntf(S,"lJ"));R.Name=f6.XW(S);f6.OM(S,nZ,true);R.IsOptional=f6.yB(S)==53;nZ.push(53);if(R.IsOptional)f6.OM(S,nZ,true);if(f6.yB(S)==54)R.Type=f6.Xv(S);return R},Xs:function(S){var R=null;f6.gf(S,17);R=qq.ue$($New(Da),$AsIntf(S,"lJ"));while(f6.SH(S,[22].slice(),false)){R.ParameterList.push(f6.sJ(S));f6.Qj(S,[24,18,23].slice());if(f6.yB(S)==18)break}
f6.Qj(S,[18,23].slice());if(f6.OM(S,[54,34].slice(),false))R.ResultType=f6.Xv(S);return R},SH:function(S,eM,sp){var R=false;f6.Vm(S);R=S.tn.isIdentifier()||eM.indexOf(f6.yB(S))>=0;if((!R)&&sp)f6.HO(S,0);return R},Gm:function(S,Fy){var R=false;f6.Vm(S);R=S.tn.isIdentifier();if((!R)&&Fy)f6.HO(S,69);return R},Gx:function(S){var R="";f6.tO(S,[9,97].slice());R=f6.XW(S);while(f6.qW(S,21,false)){f6.Gm(S,true);R+="."+f6.XW(S)}
return R},t8:function(S){var R=null;f6.gf(S,89);R=qq.ue$($New(Eg),$AsIntf(S,"lJ"));f6.SH(S,[37,9].slice(),true);switch(f6.yB(S)){case 37:R.Name="*";f6.qW(S,116,true);f6.Gm(S,true);f6.qW(S,133,true);f6.qW(S,9,true);break;case 9:R.Name=S.tn.getTokenValue();break;default:R.Name=f6.XW(S);f6.qW(S,56,true);f6.SH(S,[127].slice(),true);if(f6.yB(S)==127){f6.qW(S,17,false);f6.qW(S,9,false);f6.qW(S,18,false)}}
f6.qW(S,23,true);return R},tT:function(S){var R=null;f6.gf(S,19);R=qq.ue$($New(Bm),$AsIntf(S,"lJ"));R.IndexSignature=f6.TG(S);if(S.NeedsSemicolon)f6.tO(S,[23,16,24].slice());return R},TG:function(S){var R=null;f6.gf(S,19);R=qq.ue$($New(s8),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.qW(S,54,true);f6.OM(S,[130,128].slice(),true);R.IsStringIndex=f6.yB(S)==130;f6.qW(S,20,true);f6.qW(S,54,true);R.Type=f6.Hv(S);return R},P6:function(S){var R=null;f6.gf(S,107);R=qq.ue$($New(HD),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.OM(S,[25,83,15].slice(),true);if(f6.yB(S)==25){do{R.TypeParameters.push(f6.nf(S))}while(!(f6.yB(S)!=24));f6.OM(S,[83,15].slice(),true)}
if(f6.yB(S)==83){f6.Gm(S,true);R.Extends.push(f6.rV(S));while(f6.yB(S)==24){f6.Gm(S,true);R.Extends.push(f6.rV(S))}}
f6.gf(S,15);R.Type=f6.qC(S);f6.gf(S,16);return R},xk:function(S){var R=null;R=qq.ue$($New(dL),$AsIntf(S,"lJ"));R.CallSignature=f6.pb(S);if(S.NeedsSemicolon)f6.Qj(S,[23,16].slice());return R},YP:function(S){var R=null;var WT=[],WT=[73,82,81,89,125,87,107,102,23,16].slice();f6.gf(S,125);R=qq.ue$($New(vq),$AsIntf(S,"lJ"));f6.SH(S,[9].slice(),true);R.Name=f6.Gx(S);f6.gf(S,15);f6.OM(S,WT,true);while(f6.yB(S)!=16){switch(f6.yB(S)){case 73:R.Classes.push(f6.YH(S));break;case 82:R.Exports.push(f6.xp(S));break;case 81:f6.mj(S);break;case 87:R.Functions.push(f6.w9(S));break;case 89:f6.t8(S);break;case 125:R.Modules.push(f6.YP(S));break;case 107:R.Interfaces.push(f6.P6(S));break;case 102:R.Variables.push(f6.N5(S));break}
f6.OM(S,WT,true)}
f6.gf(S,16);return R},jZ:function(S){var R=null;var qn=[],qn=[73,122,82,81,89,87,107,23,16].slice();f6.gf(S,126);f6.SH(S,[9].slice(),true);R=qq.ue$($New(x1),$AsIntf(S,"lJ"));R.Name=f6.Gx(S);f6.gf(S,15);f6.OM(S,qn,true);while(f6.yB(S)!=16){switch(f6.yB(S)){case 73:R.Classes.push(f6.YH(S));break;case 81:f6.mj(S);break;case 87:R.Functions.push(f6.w9(S));break;case 89:f6.t8(S);break;case 107:R.Interfaces.push(f6.P6(S));break}
f6.OM(S,qn,true)}
f6.gf(S,16);return R},qC:function(S){var R=null;var L1=[],L1=[9,8,92,25,17,19,16].slice();var AZ=[],AZ=[72,73,75,77,78,82,85,86,89,90].slice();f6.gf(S,15);R=qq.ue$($New(yn),$AsIntf(S,"lJ"));f6.SH(S,L1.concat(AZ),true);while(f6.yB(S)!=16){R.Members.push(f6.xA(S));if(([23,24].indexOf(f6.yB(S))>=0))f6.SH(S,L1.concat(AZ),true)}
f6.gf(S,16);return R},Vu:function(S){var R=null;f6.tO(S,[112,110,111,22].slice());R=qq.ue$($New(hk),$AsIntf(S,"lJ"));R.Name=f6.XW(S);R.IsRest=f6.yB(S)==22;if(R.IsRest){f6.Gm(S,true);R.Name=f6.XW(S);if(f6.qW(S,54,false))R.Type=f6.Hv(S);f6.gf(S,18);return R}
f6.tO(S,[112,110,111].slice());switch(f6.yB(S)){case 112:R.AccessibilityModifier=0;f6.Gm(S,false);break;case 110:R.AccessibilityModifier=1;f6.Gm(S,false);break;case 111:R.AccessibilityModifier=2;f6.Gm(S,false);break}
f6.tO(S,[]);f6.OM(S,[53,54,56,24,18].slice(),true);R.IsOptional=f6.yB(S)==53;if(R.IsOptional)f6.OM(S,[54,56,24,18].slice(),true);if(f6.yB(S)==54)R.Type=f6.Xv(S);f6.Qj(S,[56,24,18].slice());if(f6.yB(S)==56){f6.Gm(S,true);R.DefaultValue=f6.XW(S)}
f6.Qj(S,[24,18].slice());return R},tr:function(S){var R=null;var UZ=[],UZ=[69,9,117,128,130,120,103,101,97,15,17,19].slice();var Fm=null;f6.Qj(S,UZ);switch(f6.yB(S)){case 17:R=f6.Xv(S);f6.gf(S,18);f6.Vm(S);break;case 69:case 97:R=ld.wd($New(ld),$AsIntf(S,"lJ"),f6.Gx(S));if(f6.yB(S)==25){do{$As(R,ld).Arguments.push(f6.a3(S))}while(!(f6.yB(S)!=24));f6.gf(S,27);f6.Vm(S)}
break;case 9:R=ld.wd($New(ld),$AsIntf(S,"lJ"),S.tn.getTokenValue());f6.Vm(S);break;case 117:R=qq.ue$($New(X9),$AsIntf(S,"lJ"));f6.Vm(S);break;case 128:R=qq.ue$($New(EI),$AsIntf(S,"lJ"));f6.Vm(S);break;case 103:R=null;f6.Vm(S);break;case 101:R=qq.ue$($New(ew),$AsIntf(S,"lJ"));$As(R,ew).Type=f6.Xv(S);break;case 130:R=qq.ue$($New(o5),$AsIntf(S,"lJ"));f6.Vm(S);break;case 120:R=qq.ue$($New(mq),$AsIntf(S,"lJ"));f6.Vm(S);break;case 15:R=f6.qC(S);f6.Vm(S);break;case 19:R=f6.ci(S);f6.Vm(S);break}
while(f6.yB(S)==19){Fm=R;R=qq.ue$($New(kr),$AsIntf(S,"lJ"));$As(R,kr).Type=Fm;f6.qW(S,20,true);f6.Vm(S)}
return R},cw:function(S){var R=null;f6.Qj(S,[54,23].slice());R=qq.ue$($New(ro),$AsIntf(S,"lJ"));if(f6.yB(S)==23)return R;R.Type=f6.Xv(S);if(S.NeedsSemicolon)f6.tO(S,[23,16,24].slice());return R},OM:function(S,m9,Is){var R=false;R=m9.indexOf(f6.Vm(S))>=0;if((!R)&&Is)f6.HO(S,0);return R},qW:function(S,E6,Hg){var R=false;R=f6.Vm(S)==E6;if((!R)&&Hg)f6.HO(S,E6);return R},Vm:function(S){var R=0;R=S.tn.scan();return R},ci:function(S){var R=null;f6.gf(S,19);R=qq.ue$($New(XK),$AsIntf(S,"lJ"));do{R.Types.push(f6.Xv(S))}while(!(f6.yB(S)==20));f6.gf(S,20);return R},Xv:function(S){var R=null;var m7=[],m7=[69,9,117,128,130,120,103,101,97,92,15,17,19].slice();var la=0,u3=false,GK=null;la=S.tn.getTextPos();f6.OM(S,m7,true);if(f6.yB(S)==17){u3=true;f6.SH(S,m7.concat([112,111,110]),false);if(!([112,111,110].indexOf(f6.yB(S))>=0)){if(S.tn.isIdentifier()){f6.OM(S,[25,47,54,24,53,21,19,18].slice(),true);u3=([54,53,24,18].indexOf(f6.yB(S))>=0)}}
S.tn.setTextPos(la);f6.OM(S,m7,true);if(u3)return f6.Xs(S)}
if(f6.yB(S)==92)return f6.EU(S);R=f6.tr(S);while(f6.yB(S)==47){if(!$Is(R,EZ)){GK=R;R=qq.ue$($New(EZ),$AsIntf(S,"lJ"));$As(R,EZ).Types.push(GK)}
f6.OM(S,m7,true);$As(R,EZ).Types.push(f6.tr(S))}
return R},iM:function(S){var R=null;f6.gf(S,132);R=qq.ue$($New(O3),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.OM(S,[25,56].slice(),true);if(f6.yB(S)==25){R.TypeParameters.push(f6.nf(S));f6.qW(S,56,true)}
R.Type=f6.Xv(S);if(S.NeedsSemicolon)f6.gf(S,23);return R},Hv:function(S){var R=null;f6.gf(S,54);R=f6.Xv(S);return R},a3:function(S){var R=null;f6.Qj(S,[25,24].slice());R=qq.ue$($New(kK),$AsIntf(S,"lJ"));R.Type=f6.Xv(S);f6.Qj(S,[27,24].slice());return R},xA:function(S){var R=null;var vm=[],ZB=[],ZB=[9,8,110,92,25,17,19].slice();var qK=[],qK=[72,73,75,77,78,82,85,86,89,90].slice();var Im="",Fb=false;f6.tO(S,ZB.concat(qK));if(f6.yB(S)==92)return f6.tc(S);if(([17,25].indexOf(f6.yB(S))>=0))return f6.pb(S);if(f6.yB(S)==19)return f6.TG(S);if(S.tn.isIdentifier()||[9,8].concat(qK).indexOf(S.tn.getToken())>=0){Im=f6.XW(S);f6.OM(S,[25,53,54,17].slice(),true);Fb=f6.yB(S)==53;if(Fb)f6.OM(S,[54,17,25].slice(),true);switch(f6.yB(S)){case 54:R=f6.cw(S);$As(R,ro).Nullable=Fb;break;case 17:case 25:R=f6.xk(S);break}
R.TypeArguments=vm;R.Name=Im}
return R},nf:function(S){var R=null;f6.Qj(S,[25,24].slice());R=qq.ue$($New(Kc),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.OM(S,[83,27,24].slice(),true);if(f6.yB(S)==83){R.ExtendsType=f6.Xv(S);f6.Qj(S,[27,24].slice())}
return R},rV:function(S){var R=null;f6.tO(S,[]);R=qq.ue$($New(V6),$AsIntf(S,"lJ"));R.Name=f6.Gx(S);if(f6.yB(S)==25){do{R.Arguments.push(f6.a3(S))}while(!(f6.yB(S)!=24));f6.Vm(S)}
return R},N5:function(S){var R=null;f6.gf(S,102);R=qq.ue$($New(uA),$AsIntf(S,"lJ"));f6.Gm(S,true);R.Name=f6.XW(S);f6.qW(S,54,true);R.Type=f6.Xv(S);return R},Vg:function(S,mf){var R="";S.tn=Z.createScanner(0,true,0,mf);S.kg=Z.createSourceFile("main",mf,0);try{f6.zu$(S)}catch($e){var bs=$W($e);console.error(bs.FMessage)}
R=f6.kP$(S);return R},Destroy:TObject.Destroy,kP$:function($){return $.ClassType.kP($)},zu$:function($){return $.ClassType.zu($)}};f6.$Intf={lJ:[]}
function Lu(MV){var R="";var tN=[];if(MV.length==0)return"Unknown";tN=(MV).split("\\");R=tN[(tN.length-1)];tN=(MV).split("\/");R=tN[(tN.length-1)];R=StrReplace(R,"-","_");R=$StrSet(R,1,(R.charAt(0)).toUpperCase());return R};var y3=["vPublic","vProtected","vPrivate"];var qq={$ClassName:"TCustomDeclaration",$Parent:TObject,$Init:function($){TObject.$Init($);$.io=null},JU:function(S){++Ay},r8:function(S,HL3){Hb.push(HL3)},ue:function(S,S8){S.io=S8;return S},VT:function(S){--Ay},ah:function(S){Hb.pop()},sB:function(S){var R="";R=DupeString("  ",Ay);return R},w8:function(S){var R="";var f1=0;R="";if(Hb.length>0){R+=Hb[0];var $t5;for(f1=0+1,$t5=Hb.length;f1<$t5;f1++){R+="."+Hb[f1]}}
return R},Destroy:TObject.Destroy,ue$:function($){return $.ClassType.ue.apply($.ClassType,arguments)},Bs$:function($){return $.ClassType.Bs($)}};var Be={$ClassName:"TCustomType",$Parent:qq,$Init:function($){qq.$Init($)},Destroy:TObject.Destroy,ue:qq.ue,Bs:qq.Bs};var nM={$ClassName:"TCustomNamedType",$Parent:Be,$Init:function($){Be.$Init($)},Bs:function(S){var R="";R="J"+nM.ip$(S);return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)},ip$:function($){return $.ClassType.ip($)}};var Tw={$ClassName:"TPredefinedType",$Parent:nM,$Init:function($){nM.$Init($)},Bs:function(S){var R="";R=nM.ip$(S);return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)},ip:nM.ip};var X9={$ClassName:"TVariantType",$Parent:Tw,$Init:function($){Tw.$Init($)},ip:function(S){var R="";R="Variant";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs:Tw.Bs,ip$:function($){return $.ClassType.ip($)}};var BL={$ClassName:"TNamedDeclaration",$Parent:qq,$Init:function($){qq.$Init($);$.Name=""},Destroy:TObject.Destroy,ue:qq.ue,Bs:qq.Bs};var uA={$ClassName:"TVariableDeclaration",$Parent:BL,$Init:function($){BL.$Init($);$.Type=null},Bs:function(S){var R="";console.log("not implemented: TVariableDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var EZ={$ClassName:"TUnionType",$Parent:Be,$Init:function($){Be.$Init($);$.Types=[]},Bs:function(S){var R="";var gA=0;var sG=null;R="Variant {";var $t6;for(gA=0,$t6=(S.Types.length-1);gA<$t6;gA++){R+=qq.Bs$(S.Types[gA])+" or "}
sG=S.Types[(S.Types.length-1)];R+=(sG)?qq.Bs$(sG):"void";R+="}";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var V6={$ClassName:"TTypeReference",$Parent:qq,$Init:function($){qq.$Init($);$.Name="";$.Arguments=[]},Bs:function(S){var R="";var ks=0;R="J"+S.Name;if(S.Arguments.length>0){R+=" {"+qq.Bs$(S.Arguments[0]);var $t7;for(ks=0+1,$t7=S.Arguments.length;ks<$t7;ks++){R+=", "+qq.Bs$(S.Arguments[ks])}
R+="} "}
return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var Kc={$ClassName:"TTypeParameter",$Parent:qq,$Init:function($){qq.$Init($);$.Name="";$.ExtendsType=null},Bs:function(S){var R="";R=S.Name;if(S.ExtendsType)R+=" extends "+qq.Bs$(S.ExtendsType);return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var ew={$ClassName:"TTypeOfType",$Parent:nM,$Init:function($){nM.$Init($);$.Type=null},ip:function(S){var R="";R="type of";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs:nM.Bs,ip$:function($){return $.ClassType.ip($)}};var kK={$ClassName:"TTypeArgument",$Parent:qq,$Init:function($){qq.$Init($);$.Type=null},Bs:function(S){var R="";if(S.Type){R=qq.Bs$(S.Type)}else R="Variant";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var O3={$ClassName:"TTypeAlias",$Parent:BL,$Init:function($){BL.$Init($);$.Type=null;$.TypeParameters=[]},Bs:function(S){var R="";R=qq.sB(S.ClassType)+S.Name+" = "+qq.Bs$(S.Type)+";"+"\r\n";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var XK={$ClassName:"TTupleType",$Parent:Be,$Init:function($){Be.$Init($);$.Types=[]},Bs:function(S){var R="";R="TupletType";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var o5={$ClassName:"TStringType",$Parent:Tw,$Init:function($){Tw.$Init($)},ip:function(S){var R="";R="String";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs:Tw.Bs,ip$:function($){return $.ClassType.ip($)}};var e8={$ClassName:"TCustomTypeMember",$Parent:BL,$Init:function($){BL.$Init($);$.TypeParameters=[];$.Visibility=0;$.IsStatic=false;$.TypeArguments=[]},ue:function(S,Qc){qq.ue(S,Qc);S.Visibility=0;return S},Destroy:TObject.Destroy,ue$:function($){return $.ClassType.ue.apply($.ClassType,arguments)},Bs:qq.Bs};var bO={$ClassName:"TClassTypeMember",$Parent:e8,$Init:function($){e8.$Init($);$.Visibility=0;$.IsStatic=false},Destroy:TObject.Destroy,ue:e8.ue,Bs:qq.Bs};var ro={$ClassName:"TPropertyMemberDeclaration",$Parent:bO,$Init:function($){bO.$Init($);$.Nullable=false;$.Type=null},Bs:function(S){var R="";var xG=0;var Na=null;R=qq.sB(S.ClassType)+rF(S.Name);if(S.TypeArguments.length>0){var lV=[];R+="{<";lV=S.TypeArguments;var $t8;for(xG=0,$t8=lV.length;xG<$t8;xG++){Na=lV[xG];R+=qq.Bs$(Na)}
R+=">}"}
R+=": ";if(S.Type){if($Is(S.Type,yn))R+="record"+"\r\n";R+=qq.Bs$(S.Type)}else R+="Variant";R+=";";if(S.Nullable)R+=" \/\/ nullable";R+="\r\n";return R},Destroy:TObject.Destroy,ue:e8.ue,Bs$:function($){return $.ClassType.Bs($)}};var hk={$ClassName:"TParameter",$Parent:BL,$Init:function($){BL.$Init($);$.DefaultValue="";$.IsRest=$.IsOptional=false;$.AccessibilityModifier=0;$.Type=null},Bs:function(S){var R="";R=S.Name+": ";if(S.Type){if($Is(S.Type,yn))R+="record"+"\r\n";R+=qq.Bs$(S.Type)}else R+="Variant";if(S.DefaultValue!="")R+=" = "+S.DefaultValue;if(S.IsRest)R+=" {...}";return R},Px:function(S,gV){var R="";var Fx=null;R=rF(S.Name);if(!gV){R+=": ";if(S.Type){if($Is(S.Type,yn))R+="record"+"\r\n";if($Is(S.Type,Da)){Fx=$As(S.Type,Da).ResultType;R+=(Fx)?"function":"procedure"}
R+=qq.Bs$(S.Type)}else R+="Variant"}
return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var yn={$ClassName:"TObjectType",$Parent:Be,$Init:function($){Be.$Init($);$.Members=[]},Bs:function(S){var R="";var Yh=0;var ss=null,N8=null;var PV=[];qq.JU(S.ClassType);PV=S.Members;var $t9;for(Yh=0,$t9=PV.length;Yh<$t9;Yh++){ss=PV[Yh];if($Is(ss,EH)){R+=qq.sB(S.ClassType);N8=$As(ss,EH).Type;R+=(N8)?"function":"procedure";R+=qq.Bs$(ss)+"\r\n"}else R+=qq.Bs$(ss)}
qq.VT(S.ClassType);R+=qq.sB(S.ClassType)+"end;";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var x1={$ClassName:"TNamespaceDeclaration",$Parent:BL,$Init:function($){BL.$Init($);$.Namespaces=[];$.Interfaces=[];$.Classes=[];$.Functions=[];$.TypeAliases=[];$.Enums=[]},Bs:function(S){var R="";var rB=0;var oj=null,cd=0;var dI=null,tB=0;var qi=null,no=0;var Ds=null,hH=0;var Wg=null;var vZ=[];qq.r8(S.ClassType,S.Name);if(S.Enums.length+S.Classes.length+S.Interfaces.length>0){var mT=[],Hl=[],BR=[];R+="type"+"\r\n";qq.JU(S.ClassType);BR=S.Enums;var $tA;for(rB=0,$tA=BR.length;rB<$tA;rB++){oj=BR[rB];R+=qq.Bs$(oj)}
Hl=S.Classes;var $tB;for(cd=0,$tB=Hl.length;cd<$tB;cd++){dI=Hl[cd];R+=qq.Bs$(dI)}
mT=S.Interfaces;var $tC;for(tB=0,$tC=mT.length;tB<$tC;tB++){qi=mT[tB];R+=qq.Bs$(qi)}
qq.VT(S.ClassType)}
if(S.Functions.length>0){var Ae=[];Ae=S.Functions;var $tD;for(no=0,$tD=Ae.length;no<$tD;no++){Ds=Ae[no];R+=qq.Bs$(Ds)}
R+="\r\n"}
vZ=S.Namespaces;var $tE;for(hH=0,$tE=vZ.length;hH<$tE;hH++){Wg=vZ[hH];R+=qq.Bs$(Wg)}
R+="\r\n";qq.ah(S.ClassType);return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var ld={$ClassName:"TNamedType",$Parent:nM,$Init:function($){nM.$Init($);$.Arguments=[];$.vl=""},wd:function(S,mQ,Sg){qq.ue(S,mQ);S.vl=Sg;return S},Bs:function(S){var R="";var IF=0;var u1=null;R=nM.Bs(S);if(S.Arguments.length>0){var bN=[];R+="{<";bN=S.Arguments;var $tF;for(IF=0,$tF=bN.length;IF<$tF;IF++){u1=bN[IF];R+=qq.Bs$(u1)}
R+=">}"}
return R},ip:function(S){var R="";R=S.vl;return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)},ip$:function($){return $.ClassType.ip($)}};var vq={$ClassName:"TModuleDeclaration",$Parent:BL,$Init:function($){BL.$Init($);$.Modules=[];$.Variables=[];$.Exports=[];$.Functions=[];$.Interfaces=[];$.Classes=[]},Bs:function(S){var R="";var Ph=0;var d4=null,GC=0;var xI=null,sx=0;var Qe=null;R="";if(S.Classes.length+S.Interfaces.length>0){var KI=[],lM=[];R+="type"+"\r\n";qq.JU(S.ClassType);lM=S.Classes;var $tG;for(Ph=0,$tG=lM.length;Ph<$tG;Ph++){d4=lM[Ph];R=R+qq.Bs$(d4)}
KI=S.Interfaces;var $tH;for(GC=0,$tH=KI.length;GC<$tH;GC++){xI=KI[GC];R=R+qq.Bs$(xI)}
qq.VT(S.ClassType)}
if(S.Variables.length>0){var Ey=[];R+="var"+"\r\n";qq.JU(S.ClassType);Ey=S.Variables;var $tI;for(sx=0,$tI=Ey.length;sx<$tI;sx++){Qe=Ey[sx];R=R+qq.Bs$(Qe)}
qq.VT(S.ClassType)}
return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var dL={$ClassName:"TMethodDeclaration",$Parent:bO,$Init:function($){bO.$Init($);$.CallSignature=null},Bs:function(S){var R="";var xn="";var aI="";var iW=0,Li=0;var jt=null,UL=0;var O5=[];iW=0;O5=S.CallSignature.ParameterList;var $tJ;for(Li=0,$tJ=O5.length;Li<$tJ;Li++){jt=O5[Li];if(jt.IsOptional)++iW}
xn=qq.sB(S.ClassType);xn+=(S.CallSignature.Type)?"function":"procedure";xn+=" "+S.Name;aI=(iW>0)?" overload;":"";aI+="\r\n";R="";var $tK;for(UL=0,$tK=iW;UL<=$tK;UL++){R+=xn+EH.mN(S.CallSignature,UL)+aI}
return R},Destroy:TObject.Destroy,ue:e8.ue,Bs$:function($){return $.ClassType.Bs($)}};var HD={$ClassName:"TInterfaceDeclaration",$Parent:qq,$Init:function($){qq.$Init($);$.TypeParameters=[];$.Name="";$.Extends=[];$.Type=null},Bs:function(S){var R="";var U7=0;var T1=null,wb=0;R+=qq.sB(S.ClassType)+"J"+S.Name;if(S.TypeParameters.length>0){var lG=[];R+="{<";lG=S.TypeParameters;var $tL;for(U7=0,$tL=lG.length;U7<$tL;U7++){T1=lG[U7];R+=qq.Bs$(T1)}
R+=">}"}
R+=" = class external";if(S.Extends.length>0){R+="(";R+=qq.Bs$(S.Extends[0]);var $tM;for(wb=0+1,$tM=S.Extends.length;wb<$tM;wb++){R+=", "+qq.Bs$(S.Extends[wb])}
R+=")"}
R+="\r\n";R+=qq.Bs$(S.Type);R+="\r\n"+"\r\n";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var s8={$ClassName:"TIndexSignature",$Parent:e8,$Init:function($){e8.$Init($);$.IsStringIndex=false;$.Type=null},Bs:function(S){var R="";R=qq.sB(S.ClassType)+"\/\/ ";R+="property Item["+S.Name+": ";R+=(S.IsStringIndex)?"String":"Integer";R+="]: "+qq.Bs$(S.Type)+";"+"\r\n";return R},Destroy:TObject.Destroy,ue:e8.ue,Bs$:function($){return $.ClassType.Bs($)}};var Bm={$ClassName:"TIndexMemberDeclaration",$Parent:bO,$Init:function($){bO.$Init($);$.IndexSignature=null},Bs:function(S){var R="";R=qq.Bs$(S.IndexSignature)+";"+"\r\n";return R},Destroy:TObject.Destroy,ue:e8.ue,Bs$:function($){return $.ClassType.Bs($)}};var Eg={$ClassName:"TImportDeclaration",$Parent:BL,$Init:function($){BL.$Init($)},Bs:function(S){var R="";console.log("not implemented: TImportDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var Da={$ClassName:"TFunctionType",$Parent:nM,$Init:function($){nM.$Init($);$.ParameterList=[];$.ResultType=null},Bs:function(S){var R="";var f3=0;if(S.ParameterList.length>0){R="("+Zg.r3(S.ParameterList[0],false);var $tN;for(f3=0+1,$tN=S.ParameterList.length;f3<$tN;f3++){R+="; "+Zg.r3(S.ParameterList[f3],false)}
R+=")"}
if(S.ResultType)R+=": "+qq.Bs$(S.ResultType);return R},Ov:function(S,Fe){var R="";var zJ=false;var Xc=0,UT=0;Xc=0;if(S.ParameterList.length>0){if(!(S.ParameterList[0].IsOptional&&Fe==0)){Xc+=(S.ParameterList[0].IsOptional?1:0);zJ=S.ParameterList.length>=2&&eT(S.ParameterList[0],S.ParameterList[1])&&((!S.ParameterList[0].IsOptional)||Xc<Fe);R="("+Zg.r3(S.ParameterList[0],zJ);var $tO;for(UT=0+1,$tO=S.ParameterList.length;UT<$tO;UT++){if(S.ParameterList[UT].IsOptional&&Xc>=Fe)break;Xc+=(S.ParameterList[UT].IsOptional?1:0);R+=(zJ)?", ":"; ";zJ=UT+1<S.ParameterList.length&&eT(S.ParameterList[0],S.ParameterList[1])&&((!S.ParameterList[UT].IsOptional)||Xc<Fe);R+=Zg.r3(S.ParameterList[UT],zJ)}
R+=")"}}
if(S.ResultType)R+=": "+qq.Bs$(S.ResultType);return R},ip:function(S){var R="";R="function";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)},ip$:function($){return $.ClassType.ip($)}};var Zg={$ClassName:"TFunctionParameter",$Parent:BL,$Init:function($){BL.$Init($);$.Type=null;$.IsOptional=false},Bs:function(S){var R="";R=rF(S.Name)+": ";if(S.Type){if($Is(S.Type,yn))R+="record"+"\r\n";R+=qq.Bs$(S.Type)}else R+="Variant";return R},r3:function(S,zn){var R="";R=rF(S.Name);if(!zn){R+=": ";if(S.Type){if($Is(S.Type,yn))R+="record"+"\r\n";R+=qq.Bs$(S.Type)}else R+="Variant"}
return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var ih={$ClassName:"TFunctionDeclaration",$Parent:BL,$Init:function($){BL.$Init($);$.Type=null},Bs:function(S){var R="";var wY="";var dl="";var jv=0,OK=0;var Ci=null,iX=0;var xz=[];jv=0;xz=S.Type.ParameterList;var $tP;for(OK=0,$tP=xz.length;OK<$tP;OK++){Ci=xz[OK];if(Ci.IsOptional)++jv}
wY=qq.sB(S.ClassType);wY+=(S.Type.ResultType)?"function":"procedure";wY+=" "+rF(S.Name);dl=";"+((jv>0)?" overload;":"");dl+="\r\n";R="";var $tQ;for(iX=0,$tQ=jv;iX<=$tQ;iX++){R+=wY+Da.Ov(S.Type,iX)+dl}
return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var EI={$ClassName:"TFloatType",$Parent:Tw,$Init:function($){Tw.$Init($)},ip:function(S){var R="";R="Float";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs:Tw.Bs,ip$:function($){return $.ClassType.ip($)}};var Wb={$ClassName:"TExportDeclaration",$Parent:BL,$Init:function($){BL.$Init($);$.RI=false},Bs:function(S){var R="";R="";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var CR={$ClassName:"TEnumerationItem",$Parent:qq,$Init:function($){qq.$Init($);$.Name=$.Value=""},Bs:function(S){var R="";R=S.Name;return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var dd={$ClassName:"TEnumerationDeclaration",$Parent:BL,$Init:function($){BL.$Init($);$.Items=[]},Bs:function(S){var R="";var bZ=0;var tv=null;var Gy=[];R+=qq.sB(S.ClassType)+"T"+S.Name+" = Variant;"+"\r\n";R+=qq.sB(S.ClassType)+"T"+S.Name+"Helper = strict helper for T"+S.Name+"\r\n";qq.JU(S.ClassType);Gy=S.Items;var $tR;for(bZ=0,$tR=Gy.length;bZ<$tR;bZ++){tv=Gy[bZ];R+=qq.sB(S.ClassType)+"const "+rF(qq.Bs$(tv));if(tv.Value!=""){try{R+=" = "+(parseInt(tv.Value,10)).toString()+";"+"\r\n"}catch($e){R+=" = '"+tv.Value+"';"+"\r\n"}}else R+=" = '"+tv.Name+"';"+"\r\n"}
qq.VT(S.ClassType);R+=qq.sB(S.ClassType)+"end;"+"\r\n";R+="\r\n";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var oW={$ClassName:"TDefinitionDeclaration",$Parent:BL,$Init:function($){BL.$Init($)},Bs:function(S){var R="";console.log("not implemented: TDefinitionDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var O1={$ClassName:"TConstructorType",$Parent:nM,$Init:function($){nM.$Init($);$.ResultType=null;$.ParameterList=[]},Bs:function(S){var R="";var Ii=0;if(S.ParameterList.length>0){R="("+Zg.r3(S.ParameterList[0],false);var $tS;for(Ii=0+1,$tS=S.ParameterList.length;Ii<$tS;Ii++){R+="; "+Zg.r3(S.ParameterList[Ii],false)}
R+=")"}
if(S.ResultType)R+=": "+qq.Bs$(S.ResultType);return R},ip:function(S){var R="";R="constructor";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)},ip$:function($){return $.ClassType.ip($)}};var my={$ClassName:"TConstructorDeclaration",$Parent:bO,$Init:function($){bO.$Init($);$.ParameterList=[];$.Type=null},Bs:function(S){var R="";R=qq.sB(S.ClassType)+"constructor Create";if(S.Type)R+=qq.Bs$(S.Type);R+=";"+"\r\n";return R},Destroy:TObject.Destroy,ue:e8.ue,Bs$:function($){return $.ClassType.Bs($)}};var Pu={$ClassName:"TClassDeclaration",$Parent:HD,$Init:function($){HD.$Init($);$.Implements=[];$.Members=[]},Bs:function(S){var R="";var Bp=0;var FS=0;var bf=null;var Y3=[];R+=qq.sB(S.ClassType)+"J"+S.Name+" = class external '"+S.Name+"'";if(S.Extends.length>0){R+="(";R+=qq.Bs$(S.Extends[0]);var $tT;for(Bp=0+1,$tT=S.Extends.length;Bp<$tT;Bp++){R+=", "+qq.Bs$(S.Extends[Bp])}
R+=")"}
R+="\r\n";qq.JU(S.ClassType);Y3=S.Members;var $tU;for(FS=0,$tU=Y3.length;FS<$tU;FS++){bf=Y3[FS];R+=qq.Bs$(bf)}
qq.VT(S.ClassType);R+=qq.sB(S.ClassType)+"end;"+"\r\n"+"\r\n";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var EH={$ClassName:"TCallSignature",$Parent:e8,$Init:function($){e8.$Init($);$.ParameterList=[];$.Type=null;$.TypeParameters=[]},Bs:function(S){var R="";var y58=0;var Kus=null,MF=0;R="";if(S.TypeParameters.length>0){var ZL=[];R+="{<";ZL=S.TypeParameters;var $tV;for(y58=0,$tV=ZL.length;y58<$tV;y58++){Kus=ZL[y58];R+=qq.Bs$(Kus)}
R+=">}"}
if(S.ParameterList.length>0){R+="(";var $tW;for(MF=0,$tW=(S.ParameterList.length-1);MF<$tW;MF++){R+=hk.Px(S.ParameterList[MF],false)+"; "}
R+=hk.Px(S.ParameterList[(S.ParameterList.length-1)],false)+")"}
if(S.Type)R+=": "+qq.Bs$(S.Type);R+=";";return R},mN:function(S,ZE){var R="";var bw=false;var LX=0,kV=0;LX=0;if(S.ParameterList.length>0){if(!(S.ParameterList[0].IsOptional&&ZE==0)){LX+=(S.ParameterList[0].IsOptional?1:0);bw=S.ParameterList.length>=2&&Qv(S.ParameterList[0],S.ParameterList[1])&&((!S.ParameterList[0].IsOptional)||LX<ZE);R="("+hk.Px(S.ParameterList[0],bw);var $tX;for(kV=0+1,$tX=S.ParameterList.length;kV<$tX;kV++){if(S.ParameterList[kV].IsOptional&&LX>=ZE)break;LX+=(S.ParameterList[kV].IsOptional?1:0);R+=(bw)?", ":"; ";bw=kV+1<S.ParameterList.length&&Qv(S.ParameterList[kV],S.ParameterList[kV+1])&&((!S.ParameterList[kV].IsOptional)||LX<ZE);R+=hk.Px(S.ParameterList[kV],bw)}
R+=")"}}
if(S.Type)R+=": "+qq.Bs$(S.Type);return R},Destroy:TObject.Destroy,ue:e8.ue,Bs$:function($){return $.ClassType.Bs($)}};var mq={$ClassName:"TBooleanType",$Parent:Tw,$Init:function($){Tw.$Init($)},ip:function(S){var R="";R="Boolean";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs:Tw.Bs,ip$:function($){return $.ClassType.ip($)}};var kr={$ClassName:"TArrayType",$Parent:Be,$Init:function($){Be.$Init($);$.Type=null},Bs:function(S){var R="";R="array of "+qq.Bs$(S.Type);return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var l2={$ClassName:"TAmbientVariableDeclaration",$Parent:qq,$Init:function($){qq.$Init($);$.IsConst=false;$.AmbientBindingList=[]},Bs:function(S){var R="";var B4=0;var mi=null;var tZ=[];tZ=S.AmbientBindingList;var $tY;for(B4=0,$tY=tZ.length;B4<$tY;B4++){mi=tZ[B4];R+=qq.sB(S.ClassType)+qq.Bs$(mi)}
R+=";"+"\r\n";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var np={$ClassName:"TAmbientBodyElement",$Parent:qq,$Init:function($){qq.$Init($)},Destroy:TObject.Destroy,ue:qq.ue,Bs:qq.Bs};var jL={$ClassName:"TAmbientPropertyMemberDeclaration",$Parent:np,$Init:function($){np.$Init($);$.Visibility=0;$.IsStatic=false;$.Name=""},Destroy:TObject.Destroy,ue:qq.ue,Bs:qq.Bs};var Tf={$ClassName:"TAmbientPropertyMemberDeclarationProperty",$Parent:jL,$Init:function($){jL.$Init($);$.Type=null},Bs:function(S){var R="";R=qq.sB(S.ClassType);if(S.IsStatic)R+="class var ";R+=rF(S.Name);R+=": "+((S.Type)?qq.Bs$(S.Type):"Variant");R+=";"+"\r\n";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var eJ={$ClassName:"TAmbientPropertyMemberDeclarationMethod",$Parent:jL,$Init:function($){jL.$Init($);$.CallSignature=null},Bs:function(S){var R="";var mU="";var nb="";var KM=0,j7=0;var oJ=null,ol=0;var RS=[];KM=0;RS=S.CallSignature.ParameterList;var $tZ;for(j7=0,$tZ=RS.length;j7<$tZ;j7++){oJ=RS[j7];if(oJ.IsOptional)++KM}
mU=qq.sB(S.ClassType);mU+=(S.CallSignature.Type)?"function":"procedure";mU+=" "+rF(S.Name);nb=(KM>0)?" overload;":"";nb+="\r\n";R="";var $ta;for(ol=0,$ta=KM;ol<=$ta;ol++){R+=mU+EH.mN(S.CallSignature,ol)+nb}
return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var nJ={$ClassName:"TAmbientNamespaceDeclaration",$Parent:BL,$Init:function($){BL.$Init($);$.Namespaces=[];$.Variables=[];$.Interfaces=[];$.Enums=[];$.Functions=[];$.Classes=[]},Bs:function(S){var R="";var VHN=0,vr=0;var Ac=null,tX=0;var kZ=null,Vj=0;var aF=null,uX=0;var Mx=null,ox=0;var Vw=null,dP=0;var CA=null,yC=0;var oy=null,Qz=0;var uR=null;var YG=[],ym=[];qq.r8(S.ClassType,S.Name);VHN=0;ym=S.Variables;var $tb;for(vr=0,$tb=ym.length;vr<$tb;vr++){Ac=ym[vr];if(Ac.IsConst)++VHN}
if(VHN>0){var SB=[];R+="const"+"\r\n";qq.JU(S.ClassType);SB=S.Variables;var $tc;for(tX=0,$tc=SB.length;tX<$tc;tX++){kZ=SB[tX];if(kZ.IsConst)R=R+qq.Bs$(kZ)}
qq.VT(S.ClassType);R+="\r\n"}
if(S.Enums.length+S.Classes.length+S.Interfaces.length>0){var Zt=[],oU=[],UB=[];R+="type"+"\r\n";qq.JU(S.ClassType);UB=S.Enums;var $td;for(Vj=0,$td=UB.length;Vj<$td;Vj++){aF=UB[Vj];R+=qq.Bs$(aF)}
oU=S.Classes;var $te;for(uX=0,$te=oU.length;uX<$te;uX++){Mx=oU[uX];R+=qq.Bs$(Mx)}
Zt=S.Interfaces;var $tf;for(ox=0,$tf=Zt.length;ox<$tf;ox++){Vw=Zt[ox];R+=qq.Bs$(Vw)}
qq.VT(S.ClassType)}
if(S.Functions.length>0){var IXH=[];IXH=S.Functions;var $tg;for(dP=0,$tg=IXH.length;dP<$tg;dP++){CA=IXH[dP];R+=qq.Bs$(CA)}
R+="\r\n"}
if(S.Variables.length-VHN>0){var RX=[];R+="var"+"\r\n";qq.JU(S.ClassType);RX=S.Variables;var $th;for(yC=0,$th=RX.length;yC<$th;yC++){oy=RX[yC];if(!oy.IsConst)R=R+qq.Bs$(oy)}
qq.VT(S.ClassType);R+="\r\n"}
YG=S.Namespaces;var $ti;for(Qz=0,$ti=YG.length;Qz<$ti;Qz++){uR=YG[Qz];R+=qq.Bs$(uR)}
R+="\r\n";qq.ah(S.ClassType);return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var gG={$ClassName:"TAmbientModuleDeclaration",$Parent:qq,$Init:function($){qq.$Init($);$.Interfaces=[];$.Namespaces=[];$.Modules=[];$.Classes=[];$.Functions=[];$.TypeAliases=[];$.IdentifierPath="";$.Enums=[];$.Variables=[]},Bs:function(S){var R="";var dh=0,Su=0;var Ld=null,cm=0;var YI=null,Ye=0;var ye=null,dG=0;var zA=null,MB=0;var Qt=null,jx=0;var BB=null,Ul=0;var D2=null,IM=0;var V3=null,mB=0;var Cs=null,aN=0;var dU=null;var sbV=[],fw=[],ge=[];R="\/\/"+S.IdentifierPath+"\r\n"+"\r\n";dh=0;sbV=S.Variables;var $tj;for(Su=0,$tj=sbV.length;Su<$tj;Su++){Ld=sbV[Su];if(Ld.IsConst)++dh}
if(dh>0){var uT=[];R+="const"+"\r\n";qq.JU(S.ClassType);uT=S.Variables;var $tk;for(cm=0,$tk=uT.length;cm<$tk;cm++){YI=uT[cm];if(YI.IsConst)R=R+qq.Bs$(YI)}
qq.VT(S.ClassType);R+="\r\n"}
if(S.Enums.length+S.Classes.length+S.Interfaces.length>0){var WL=[],N2=[],Mw=[],av=[];R+="type"+"\r\n";qq.JU(S.ClassType);N2=S.Enums;var $tl;for(Ye=0,$tl=N2.length;Ye<$tl;Ye++){ye=N2[Ye];R+=qq.Bs$(ye)}
WL=S.Classes;var $tm;for(dG=0,$tm=WL.length;dG<$tm;dG++){zA=WL[dG];R+=qq.Bs$(zA)}
av=S.Interfaces;var $tn;for(MB=0,$tn=av.length;MB<$tn;MB++){Qt=av[MB];R+=qq.Bs$(Qt)}
Mw=S.TypeAliases;var $to;for(jx=0,$to=Mw.length;jx<$to;jx++){BB=Mw[jx];R+=qq.Bs$(BB)}
qq.VT(S.ClassType)}
fw=S.Modules;var $tp;for(Ul=0,$tp=fw.length;Ul<$tp;Ul++){D2=fw[Ul];R+=qq.Bs$(D2)}
if(S.Functions.length>0){var Edk=[];Edk=S.Functions;var $tq;for(IM=0,$tq=Edk.length;IM<$tq;IM++){V3=Edk[IM];R+=qq.Bs$(V3)}
R+="\r\n"}
if(S.Variables.length-dh>0){var fQ=[];R+="var"+"\r\n";qq.JU(S.ClassType);fQ=S.Variables;var $tr;for(mB=0,$tr=fQ.length;mB<$tr;mB++){Cs=fQ[mB];if(!Cs.IsConst)R=R+qq.Bs$(Cs)}
qq.VT(S.ClassType);R+="\r\n"}
ge=S.Namespaces;var $ts;for(aN=0,$ts=ge.length;aN<$ts;aN++){dU=ge[aN];R+=qq.Bs$(dU)}
R+="\r\n";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var tV={$ClassName:"TAmbientFunctionDeclaration",$Parent:BL,$Init:function($){BL.$Init($);$.CallSignature=null},Bs:function(S){var R="";var cD="";var Uz="";var mF=0,ba=0;var eK=null,gn=0;var u8=[];mF=0;u8=S.CallSignature.ParameterList;var $tt;for(ba=0,$tt=u8.length;ba<$tt;ba++){eK=u8[ba];if(eK.IsOptional)++mF}
cD=qq.sB(S.ClassType);cD+=(S.CallSignature.Type)?"function":"procedure";cD+=" "+rF(S.Name);Uz=";"+((mF>0)?" overload;":"");if(qq.w8(S.ClassType)!="")Uz+=" external '"+qq.w8(S.ClassType)+"."+S.Name+"'";Uz+="\r\n";R="";var $tu;for(gn=0,$tu=mF;gn<=$tu;gn++){R+=cD+EH.mN(S.CallSignature,gn)+Uz}
return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var nH={$ClassName:"TAmbientEnumerationDeclaration",$Parent:dd,$Init:function($){dd.$Init($)},Destroy:TObject.Destroy,ue:qq.ue,Bs:dd.Bs};var co={$ClassName:"TAmbientDeclaration",$Parent:BL,$Init:function($){BL.$Init($);$.Variables=[];$.Namespaces=[];$.Modules=[];$.Classes=[];$.Functions=[];$.Enums=[]},Bs:function(S){var R="";var XY=0;var Pb=null,Yw=0;var AE=null,ls=0;var eD=null,Zr=0;var W3=null,Rb=0;var hM=null;var Qh=[],AR=[],Wo=[],Wz=[];AR=S.Functions;var $tv;for(XY=0,$tv=AR.length;XY<$tv;XY++){Pb=AR[XY];R+=qq.Bs$(Pb)}
Qh=S.Modules;var $tw;for(Yw=0,$tw=Qh.length;Yw<$tw;Yw++){AE=Qh[Yw];R+=qq.Bs$(AE)}
if(S.Classes.length>0){var GG=[];R+="type"+"\r\n";qq.JU(S.ClassType);GG=S.Classes;var $tx;for(ls=0,$tx=GG.length;ls<$tx;ls++){eD=GG[ls];R+=qq.Bs$(eD)}
qq.VT(S.ClassType)}
if(S.Variables.length>0){Wz=S.Variables;var $ty;for(Zr=0,$ty=Wz.length;Zr<$ty;Zr++){W3=Wz[Zr];R+=qq.Bs$(W3)}}
Wo=S.Namespaces;var $tz;for(Rb=0,$tz=Wo.length;Rb<$tz;Rb++){hM=Wo[Rb];R+=qq.Bs$(hM)}
return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var Yv={$ClassName:"TAmbientConstructorDeclaration",$Parent:np,$Init:function($){np.$Init($);$.ParameterList=[]},Bs:function(S){var R="";var gU=0;R=qq.sB(S.ClassType)+"constructor Create";if(S.ParameterList.length>0){R+="(";var $t01;for(gU=0,$t01=(S.ParameterList.length-1);gU<$t01;gU++){R+=Zg.r3(S.ParameterList[gU],false)+"; "}
R+=Zg.r3(S.ParameterList[(S.ParameterList.length-1)],false)+")";R+=")"}
R+=";"+"\r\n";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var L7={$ClassName:"TAmbientClassDeclaration",$Parent:qq,$Init:function($){qq.$Init($);$.Members=[];$.Name="";$.Extends=[];$.Implements=[]},Bs:function(S){var R="";var pH=0;var us=0,vE=0;var bq=null,q1=0;var fb=[];R+=qq.sB(S.ClassType)+"J"+S.Name+" = class external '"+S.Name+"'";if(S.Extends.length>0){R+="(";R+=qq.Bs$(S.Extends[0]);var $t11;for(pH=0+1,$t11=S.Extends.length;pH<$t11;pH++){R+=", "+qq.Bs$(S.Extends[pH])}
R+=")"}
R+="\r\n";us=0;qq.JU(S.ClassType);fb=S.Members;var $t21;for(vE=0,$t21=fb.length;vE<$t21;vE++){bq=fb[vE];q1=($Is(bq,jL))?$As(bq,jL).Visibility:0;if(us!=q1){qq.VT(S.ClassType);R+=qq.sB(S.ClassType);switch(q1){case 0:R+="public"+"\r\n";break;case 1:R+="protected"+"\r\n";break;case 2:R+="private"+"\r\n";break}
qq.JU(S.ClassType);us=q1}
R+=qq.Bs$(bq)}
qq.VT(S.ClassType);R+=qq.sB(S.ClassType)+"end;"+"\r\n"+"\r\n";return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var YY={$ClassName:"TAmbientBinding",$Parent:BL,$Init:function($){BL.$Init($);$.Type=null},Bs:function(S){var R="";R=S.Name+": "+qq.Bs$(S.Type);return R},Destroy:TObject.Destroy,ue:qq.ue,Bs$:function($){return $.ClassType.Bs($)}};var im=["amPublic","amPrivate","amProtected"];function Qv(zR,ot){var R=false;R=(!(zR.Type!==null)!=!(zR.Type!==null));if(R&&(zR.Type!==null))R=qq.Bs$(zR.Type)==qq.Bs$(ot.Type);return R};function eT(kz,Yt){var R=false;R=(!(kz.Type!==null)!=!(kz.Type!==null));if(R&&(kz.Type!==null))R=qq.Bs$(kz.Type)==qq.Bs$(Yt.Type);return R};function rF(byz){var R="";R=byz;if((["abstract","class","const","constructor","default","div","end","export","external","function","interface","label","object","private","property","protected","public","string","type","uses"].indexOf((byz).toLowerCase())>=0))R="&"+R;if((["length","include","exclude"].indexOf((byz).toLowerCase())>=0))R="_"+R;return R};var Z=null;var Z=require("typescript");var Ay=0;var Hb=[];var W=[],Di="",Yo="",B5=null;var B5=r0W();W=process.argv;W.splice(0,2);if(W.length==0){return"Usage: ts2pas inputfile [outputfile]"}
Di=W[0];if(((Di).indexOf("https:\/\/github.com\\")>=0)){kM(StrAfter(Di,"https:\/\/github.com\\"))}else{Yo=W[0]+".pas";if(W.length==2)Yo=W[1];Mr(Di,Yo)}
