#! /usr/bin/env node
/**
* ts2pas
* https://github.com/CWBudde/TS2Pas
*
* Copyright (c) 2016 Christian-W. Budde
* Licensed under the MIT license.
*/


var TObject={$ClassName:"TObject",$Parent:null,ClassName:function(s){return s.$ClassName},ClassType:function(s){return s},ClassParent:function(s){return s.$Parent},$Init:function(s){},Create:function(s){return s},Destroy:function(s){for(var prop in s)if(s.hasOwnProperty(prop))delete s[prop]},Destroy$:function(s){return s.ClassType.Destroy(s)},Free:function(s){if(s!==null)s.ClassType.Destroy(s)}}
function StrReplace(s,o,n){return o?s.replace(new RegExp(StrRegExp(o),"g"),n):s}
function StrRegExp(s){return s.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")}
function StrBefore(s,d){if(!d)return s;var p=s.indexOf(d);return(p<0)?s:s.substr(0,p)}
function StrAfter(s,d){if(!d)return"";var p=s.indexOf(d);return(p<0)?"":s.substr(p+d.length)}
var Exception={$ClassName:"Exception",$Parent:TObject,$Init:function(s){FMessage=""},Create:function(s,Msg){s.FMessage=Msg;return s}}
function stringRepeat(s,n){if(n<1)return'';var r='';while(n>0){if(n&1)r+=s;n>>=1,s+=s};return r};function DupeString(s,n){return stringRepeat(s,n)}
function $W(e){return e.ClassType?e:Exception.Create($New(Exception),e.constructor.name+", "+e.message)}
function $StrSet(s,i,v,z){if(i<1)throw Exception.Create($New(Exception),"Lower bound exceeded! Index "+i.toString()+z);if(i>s.length)throw Exception.Create($New(Exception),"Upper bound exceeded! Index "+i.toString()+z);return s.substring(0,i-1)+v+s.substring(i)}
function $New(c){var i={ClassType:c};c.$Init(i);return i}
function $Is(o,c){if(o===null)return false;return $Inh(o.ClassType,c)};function $Inh(s,c){if(s===null)return false;while((s)&&(s!==c))s=s.$Parent;return(s)?true:false};function $Extend(base,sub,props){function F(){};F.prototype=base.prototype;sub.prototype=new F();sub.prototype.constructor=sub;for(var n in props){if(props.hasOwnProperty(n)){sub.prototype[n]=props[n]}}}
function $AsIntf(o,i){if(o===null)return null;var r=o.ClassType.$Intf[i].map(function(e){return function(){var arg=Array.prototype.slice.call(arguments);arg.splice(0,0,o);return e.apply(o,arg)}});r.O=o;return r};function $As(o,c){if((o===null)||$Is(o,c))return o;throw Exception.Create($New(Exception),"Cannot cast instance of type \""+o.ClassType.$ClassName+"\" to class \""+c.$ClassName+"\"")}
function JError(){}
$Extend(Object,JError,{});function B7(rE,kt){var R=false;var oF="",Dr=null,eq="",NI=null,hI="";oF=StrBefore(rE,".d.ts");if(rE==oF)rE+=".d.ts";Dr=mD.readFileSync(rE);if(!Dr)return R;eq=Dr.toString("utf8");NI=bd.fh($New(bd));NI.Name=oF;hI=bd.HR(NI,eq);R=hI!="";if(hI.length>5)mD.writeFileSync(kt,hI);NI=null;return R};function w1(lM){var v4=null,CK=null,AE=null,bc=null;v4=sD();CK=new Object();CK.hostname="raw.githubusercontent.com";CK.path=lM;console.log("Fetching: "+lM);AE=bd.fh($New(bd));bc=v4.get(CK,function(zg){var FV="",FC=[],ox="",cz="";FV="";FC=(lM).split("\/");ox=StrBefore(FC[(FC.length-1)],".d.ts");cz=ox+".pas";zg.on("data",function(H4){FV+=String(H4)});zg.on("end",function(Xb){var vl="";console.log("Translating: "+ox);AE.Name=ox;vl=bd.HR(AE,FV);console.log("Writing: "+cz);if(vl.length>5)mD.writeFile(cz,vl,function(Wx){})})});bc.on("error",function(DG){console.log("Error: ",DG)})};function Copy$Sk(s,d){return d}
function Clone$Sk($){return{}}
function Copy$vq(s,d){return d}
function Clone$vq($){return{}}
function Copy$tV(s,d){return d}
function Clone$tV($){return{}}
function Copy$zy(s,d){return d}
function Clone$zy($){return{}}
function Copy$Fw(s,d){return d}
function Clone$Fw($){return{}}
function Copy$RM(s,d){return d}
function Clone$RM($){return{}}
function Copy$Si(s,d){return d}
function Clone$Si($){return{}}
function Copy$qf(s,d){return d}
function Clone$qf($){return{}}
function Copy$ki(s,d){return d}
function Clone$ki($){return{}}
function RD(){var R=null;R=require("fs");return R};function Copy$g4(s,d){return d}
function Clone$g4($){return{}}
function sD(){var R=null;R=require("https");return R};var aq={$ClassName:"TServer_address_result_object_tls",$Parent:TObject,$Init:function($){TObject.$Init($)},Destroy:TObject.Destroy};var gj={$ClassName:"TServer_addContext_credentials_object",$Parent:TObject,$Init:function($){TObject.$Init($)},Destroy:TObject.Destroy};var wm={$ClassName:"JServerAddressResult",$Parent:TObject,$Init:function($){TObject.$Init($)},Destroy:TObject.Destroy};function Copy$X(s,d){return d}
function Clone$X($){return{}}
var bd={$ClassName:"TTranslator",$Parent:TObject,$Init:function($){TObject.$Init($);$.NeedsSemicolon=false;$.Name="";$.Vk=[];$.yK=[];$.mm=[];$.sR=[];$.TK=$.wa=null},xY:function(S){return S.TK.getTokenText()},Qe:function(S){return S.TK.getToken()},Dv:function(S,sj){if(!(S.TK.isIdentifier()||sj.indexOf(bd.Qe(S))>=0))bd.K2(S,0)},Cz:function(S,Eh){if(!(Eh.indexOf(bd.Qe(S))>=0))bd.K2(S,0)},t8:function(S,Re){if(bd.Qe(S)!=Re)bd.K2(S,Re)},on:function(S){var R="";var iL=0;var nQ=null,H3=0;var HO=null,MW=0;var GL=null,Hb=0;var Py=null;var JT=[],w7=[],jq=[];R="";if(S.yK.length+S.sR.length+S.mm.length+S.Vk.length==0)return R;R="unit "+yF(S.Name)+";"+"\r\n"+"\r\n";R+="interface"+"\r\n"+"\r\n";jq=S.yK;var $t1;for(iL=0,$t1=jq.length;iL<$t1;iL++){nQ=jq[iL];R=R+jL.sw$(nQ)}
w7=S.sR;var $t2;for(H3=0,$t2=w7.length;H3<$t2;H3++){HO=w7[H3];R=R+jL.sw$(HO)}
if(S.mm.length>0){var YV=[];R+="type"+"\r\n";jL.wE(jL);YV=S.mm;var $t3;for(MW=0,$t3=YV.length;MW<$t3;MW++){GL=YV[MW];R=R+jL.sw$(GL)}
jL.fQ(jL)}
JT=S.Vk;var $t4;for(Hb=0,$t4=JT.length;Hb<$t4;Hb++){Py=JT[Hb];R=R+jL.sw$(Py)}
return R},fh:function(S){S.NeedsSemicolon=false;return S},K2:function(S,qP){var bi=null,tC="";bi=i.getLineAndCharacterOfPosition(S.wa,S.TK.getTokenPos());tC=("Unknown token \""+bd.xY(S).toString()+"\" in this context ("+(bi.line+1).toString()+":"+(bi.character+1).toString()+")");if(qP>0)tC+=("; Expected ("+qP.toString()+")");console.trace("Error in "+S.Name);throw Exception.Create($New(Exception),tC)},qR:function(S){var R=null;bd.Dv(S,[]);R=jL.o6$($New(Iy),$AsIntf(S,"PW"));R.Name=bd.xY(S);if(bd.hB(S,54,false))R.Type=bd.iP(S);if(S.NeedsSemicolon)bd.Cz(S,[23,24].slice());return R},hK:function(S,RE){do{RE.push(bd.qR(S));if(bd.Qe(S)==23)break;if(bd.Qe(S)!=24)break;if(!bd.xr(S,false))break}while(!(bd.Qe(S)==23||(!S.TK.isIdentifier())||(!S.NeedsSemicolon)&&(!S.TK.isIdentifier())))},TG:function(S){var R=null;var bI=0,XG=false;bd.Dv(S,[121,110,111,112,113].slice());if(bd.Qe(S)==121)return bd.S4(S);bI=0;switch(bd.Qe(S)){case 112:bI=0;bd.Cv(S,[113].slice(),true);break;case 111:bI=1;bd.Cv(S,[113].slice(),true);break;case 110:bI=2;bd.Cv(S,[113].slice(),true);break}
XG=bd.Qe(S)==113;if(XG)bd.xr(S,true);R=bd.s6(S);$As(R,br).IsStatic=XG;$As(R,br).Visibility=bI;if(S.NeedsSemicolon)bd.Cz(S,[23,16].slice());return R},vM:function(S){var R=null;var tt=[],tt=[83,106,15,25].slice();var md=[],md=[121,110,111,112,113,16,23].slice();bd.t8(S,73);R=jL.o6$($New(sQ),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.FH(S,tt,true);if(bd.Qe(S)==25){tt.push(25);do{R.TypeParameters.push(bd.Z2(S))}while(!(bd.Qe(S)!=24));bd.t8(S,27);bd.FH(S,tt,true)}
if(bd.Qe(S)==83){bd.xr(S,true);R.Extends.push(bd.EC(S))}
if(bd.Qe(S)==106){bd.xr(S,true);R.Implements.push(bd.U2(S));while(bd.Qe(S)==24){bd.xr(S,true);R.Implements.push(bd.U2(S))}}
bd.t8(S,15);bd.Cv(S,md,false);while(bd.Qe(S)!=16){R.Members.push(bd.TG(S));if(bd.Qe(S)==23)bd.Cv(S,md,false)}
bd.t8(S,16);return R},S4:function(S){var R=null;bd.t8(S,121);bd.hB(S,17,true);R=jL.o6$($New(cP),$AsIntf(S,"PW"));while(bd.Cv(S,[22].slice(),false)){R.ParameterList.push(bd.sX(S));bd.Cz(S,[24,18,23].slice());if(bd.Qe(S)==18)break}
bd.Cz(S,[18,23].slice());if(bd.Qe(S)!=23)bd.hB(S,23,true);return R},Fi:function(S){var R=null;bd.t8(S,122);R=jL.o6$($New(mG),$AsIntf(S,"PW"));bd.FH(S,[102,108,74,87,73,81,125,126].slice(),true);switch(bd.Qe(S)){case 102:case 108:case 74:R.Variables.push(bd.g7(S));break;case 87:R.Functions.push(bd.L2(S));break;case 73:R.Classes.push(bd.vM(S));break;case 81:R.Enums.push(bd.fo(S));break;case 125:R.Modules.push(bd.uu(S));break;case 126:R.Namespaces.push(bd.qM(S));break}
return R},fo:function(S){var R=null;R=bd.TB(S);return R},L2:function(S){var R=null;bd.t8(S,87);R=jL.o6$($New(Sh),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.FH(S,[17,25].slice(),true);R.CallSignature=bd.uM(S);if(S.NeedsSemicolon)bd.Cz(S,[23].slice());return R},uu:function(S){var R=null;var fp=[],fp=[82,102,108,74,132,87,73,107,81,125,126,89,16,23].slice();var fM=false,v5=null;bd.t8(S,125);R=jL.o6$($New(vO),$AsIntf(S,"PW"));bd.Cv(S,[9].slice(),true);R.IdentifierPath=bd.U2(S);bd.t8(S,15);bd.FH(S,fp,true);while(bd.Qe(S)!=16){fM=bd.Qe(S)==82;if(fM){bd.FH(S,fp.concat([77,56]),true);if(bd.Qe(S)==77){fM=false;bd.Cv(S,[73].slice(),true);if(bd.Qe(S)!=73)bd.FH(S,fp,true)}
if(bd.Qe(S)==56){fM=false;bd.xr(S,false);bd.U2(S);continue}}
switch(bd.Qe(S)){case 102:case 108:R.Variables.push(bd.g7(S));break;case 74:bd.Cv(S,[81].slice(),false);if(bd.Qe(S)==81){R.Enums.push(bd.fo(S))}else{v5=jL.o6$($New(Ci),$AsIntf(S,"PW"));v5.IsConst=true;bd.hK(S,v5.AmbientBindingList);R.Variables.push(v5)}
bd.FH(S,fp,true);break;case 132:R.TypeAliases.push(bd.gf(S));break;case 87:R.Functions.push(bd.L2(S));break;case 126:R.Namespaces.push(bd.Pz(S));bd.FH(S,fp,true);break;case 73:R.Classes.push(bd.VL(S));bd.FH(S,fp,true);break;case 125:R.Modules.push(bd.uu(S));bd.FH(S,fp,true);break;case 107:R.Interfaces.push(bd.q6(S));bd.FH(S,fp,true);break;case 89:bd.Z7(S);if(!S.NeedsSemicolon)bd.FH(S,fp,true);break;case 81:bd.TB(S);bd.FH(S,fp,true);break}
if(bd.Qe(S)==23)bd.FH(S,fp,true)}
bd.t8(S,16);return R},qM:function(S){var R=null;var DT=[],DT=[73,122,82,81,89,87,107,102,23,132,16].slice();var BA=false;bd.t8(S,126);bd.Cv(S,[9].slice(),true);R=jL.o6$($New(Ob),$AsIntf(S,"PW"));R.Name=bd.U2(S);bd.t8(S,15);bd.FH(S,DT,true);while(bd.Qe(S)!=16){BA=bd.Qe(S)==82;if(BA)bd.FH(S,DT,true);switch(bd.Qe(S)){case 73:R.Classes.push(bd.vM(S));break;case 81:bd.TB(S);break;case 87:R.Functions.push(bd.L2(S));break;case 89:bd.Z7(S);break;case 132:R.TypeAliases.push(bd.gf(S));break;case 107:R.Interfaces.push(bd.q6(S));bd.FH(S,DT,true);break;case 102:R.Variables.push(bd.g7(S));break}
if(bd.Qe(S)==23)bd.FH(S,DT,true)}
bd.t8(S,16);return R},s6:function(S){var R=null;var UyQ="";bd.Dv(S,[]);UyQ=bd.xY(S);bd.FH(S,[54,17,23].slice(),true);if(bd.Qe(S)==17){R=bd.hA(S)}else R=bd.Rp(S);R.Name=UyQ;if(S.NeedsSemicolon)bd.Dv(S,[23,16,24].slice());return R},hA:function(S){var R=null;bd.t8(S,17);R=jL.o6$($New(yr),$AsIntf(S,"PW"));R.CallSignature=bd.uM(S);bd.Cz(S,[18,23,112,111,110].slice());return R},Rp:function(S){var R=null;R=jL.o6$($New(Rs),$AsIntf(S,"PW"));if(bd.Qe(S)==54)R.Type=bd.Hk(S);return R},g7:function(S){var R=null;bd.Cz(S,[102,108,74].slice());R=jL.o6$($New(Ci),$AsIntf(S,"PW"));R.IsConst=bd.Qe(S)==74;bd.xr(S,true);bd.hK(S,R.AmbientBindingList);return R},uM:function(S){var R=null;bd.Cz(S,[17,25].slice());R=jL.o6$($New(qD),$AsIntf(S,"PW"));if(bd.Qe(S)==25){do{R.TypeParameters.push(bd.Z2(S))}while(!(bd.Qe(S)!=24));bd.hB(S,17,true)}
bd.t8(S,17);bd.Cv(S,[112,110,111,22,18].slice(),true);while(bd.Qe(S)!=18){R.ParameterList.push(bd.If(S));if(bd.Qe(S)==24)bd.Cv(S,[22].slice(),false)}
bd.Cz(S,[18].slice());bd.FH(S,[54,23].slice(),true);if(bd.Qe(S)==54)R.Type=bd.Hk(S);return R},VL:function(S){var R=null;var hx=[],hx=[83,106,15,25].slice();bd.t8(S,73);R=jL.o6$($New(Ve),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.FH(S,hx,true);if(bd.Qe(S)==25){hx.push(25);do{R.TypeParameters.push(bd.Z2(S))}while(!(bd.Qe(S)!=24));bd.t8(S,27);bd.FH(S,hx,true)}
if(bd.Qe(S)==83){bd.xr(S,true);R.Extends.push(bd.EC(S))}
if(bd.Qe(S)==106){bd.xr(S,true);R.Implements.push(bd.EC(S));while(bd.Qe(S)==24){bd.xr(S,true);R.Implements.push(bd.EC(S))}}
bd.t8(S,15);bd.UB(S,R);return R},Ud:function(S){var R=null;var xy=[],KA=[],KA=[72,75,76,77,78,82,85,88,105].slice();var ju="",Ju=false;bd.Dv(S,[92,9,19].concat(KA));if(bd.Qe(S)==19)return bd.gi(S);ju=bd.xY(S);bd.FH(S,[25,53,54,17,23].slice(),true);if(bd.Qe(S)==25){do{xy.push(bd.Z2(S))}while(!(bd.Qe(S)!=24));bd.FH(S,[53,54,17,23].slice(),true)}
Ju=bd.Qe(S)==53;if(Ju)bd.FH(S,[54,23].slice(),true);switch(bd.Qe(S)){case 54:case 23:R=bd.Wl(S);$As(R,X5).Nullable=Ju;break;case 17:if((ju).toLowerCase()=="constructor"){R=bd.XV(S)}else R=bd.ZS(S);break}
R.Name=ju;R.TypeParameters=xy;if(S.NeedsSemicolon)bd.Cz(S,[23,24,16].slice());return R},UB:function(S,Jh){var Xo=[],Xo=[92,9,82,16,23,19].slice();var yR=0,Gb=false,LS=null;bd.t8(S,15);bd.Cv(S,Xo,false);while(bd.Qe(S)!=16){yR=0;switch(bd.Qe(S)){case 112:yR=0;bd.Cv(S,[92].slice(),true);break;case 111:yR=1;bd.Cv(S,[92].slice(),true);break;case 110:yR=2;bd.Cv(S,[92].slice(),true);break}
Gb=bd.Qe(S)==113;if(Gb)bd.Cv(S,[92,17].slice(),true);LS=bd.Ud(S);LS.Visibility=yR;LS.IsStatic=Gb;Jh.Members.push(LS);if(bd.Qe(S)==23)bd.Cv(S,Xo,false)}},XV:function(S){var R=null;R=jL.o6$($New(r2),$AsIntf(S,"PW"));R.Type=bd.Tv(S);if(S.NeedsSemicolon)bd.Cz(S,[23,16].slice());return R},KS:function(S){var R=null;bd.t8(S,92);R=jL.o6$($New(r2),$AsIntf(S,"PW"));bd.FH(S,[17,25].slice(),true);if(bd.Qe(S)==25){do{R.TypeParameters.push(bd.Z2(S))}while(!(bd.Qe(S)!=24));bd.FH(S,[17].slice(),true)}
bd.t8(S,17);bd.Cv(S,[112,110,111,22,18].slice(),true);while(bd.Qe(S)!=18){R.ParameterList.push(bd.If(S));if(bd.Qe(S)==24)bd.Cv(S,[22].slice(),false)}
bd.t8(S,18);bd.hB(S,54,true);R.Type=bd.iP(S);return R},p2:function(S){var R=null;bd.t8(S,92);R=jL.o6$($New(Oo),$AsIntf(S,"PW"));bd.hB(S,17,true);while(bd.Cv(S,[22].slice(),false)){R.ParameterList.push(bd.sX(S));bd.Cz(S,[24,18,23].slice());if(bd.Qe(S)==18)break}
bd.Cz(S,[18,23].slice());if(bd.FH(S,[54,34].slice(),false))R.ResultType=bd.Hk(S);return R},cb:function(S){var An=[],An=[82,122,107,125,89,1].slice();var gF=false,dV=[],oj=null;bd.FH(S,An,true);while(bd.Qe(S)!=1){gF=bd.Qe(S)==82;if(gF){dV=An;dV.push(82);bd.FH(S,dV,true)}
switch(bd.Qe(S)){case 122:S.Vk.push(bd.Fi(S));break;case 107:oj=bd.q6(S);oj.IsExport=gF;S.mm.push(oj);bd.t8(S,16);bd.FH(S,An,true);break;case 125:S.sR.push(bd.zb(S));break;case 89:S.yK.push(bd.Z7(S));break}
if(([16,23].indexOf(bd.Qe(S))>=0))bd.FH(S,An,true)}},TB:function(S){var R=null;var A6=[],A6=[81,77,78,89,96].slice();bd.t8(S,81);R=jL.o6$($New(nw),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.hB(S,15,true);bd.Cv(S,[16].concat(A6),true);if(bd.Qe(S)!=16){do{R.Items.push(bd.KZ(S));if(bd.Qe(S)==16)break}while(!(!bd.Cv(S,A6,false)))}
bd.t8(S,16);return R},KZ:function(S){var R=null;var Ht=[],Ht=[81,77,78,89,96].slice();bd.Dv(S,Ht);R=jL.o6$($New(zi),$AsIntf(S,"PW"));R.Name=bd.xY(S);if(bd.hB(S,56,false)){bd.hB(S,8,true);R.Value=bd.xY(S);bd.sC(S)}
bd.Cz(S,[24,16].slice());return R},BH:function(S){var R=null;bd.t8(S,82);R=jL.o6$($New(wJ),$AsIntf(S,"PW"));bd.Cv(S,[77].slice(),true);R.yA=bd.Qe(S)==82||(bd.xY(S)).toLowerCase()=="default";if(R.yA)bd.xr(S,true);R.Name=bd.xY(S);bd.hB(S,23,true);return R},V7:function(S){var R=null;bd.t8(S,87);R=jL.o6$($New(cq),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.FH(S,[17].slice(),true);R.Type=bd.Tv(S);return R},sX:function(S){var R=null;var j1=false;var PJ=[],PJ=[53,24,54,18].slice();bd.Dv(S,[22].slice());j1=bd.Qe(S)==22;if(j1)bd.xr(S,true);R=jL.o6$($New(bb),$AsIntf(S,"PW"));R.Name=bd.xY(S);bd.FH(S,PJ,true);R.IsOptional=bd.Qe(S)==53;PJ.push(53);if(R.IsOptional)bd.FH(S,PJ,true);if(bd.Qe(S)==54)R.Type=bd.Hk(S);return R},Tv:function(S){var R=null;bd.Cz(S,[17,25].slice());R=jL.o6$($New(v2),$AsIntf(S,"PW"));if(bd.Qe(S)==25){do{R.TypeParameters.push(bd.Z2(S))}while(!(bd.Qe(S)!=24));bd.hB(S,17,true)}
while(bd.Cv(S,[22].slice(),false)){R.ParameterList.push(bd.sX(S));bd.Cz(S,[24,18,23].slice());if(bd.Qe(S)==18)break}
bd.Cz(S,[18,23].slice());if(bd.FH(S,[54,34].slice(),false))R.ResultType=bd.Hk(S);return R},Cv:function(S,tu,kK){var R=false;bd.sC(S);R=S.TK.isIdentifier()||tu.indexOf(bd.Qe(S))>=0;if((!R)&&kK)bd.K2(S,0);return R},xr:function(S,QA){var R=false;bd.sC(S);R=S.TK.isIdentifier();if((!R)&&QA)bd.K2(S,69);return R},U2:function(S){var R="";bd.Dv(S,[9,97].slice());R=bd.xY(S);while(bd.hB(S,21,false)){bd.xr(S,true);R+="."+bd.xY(S)}
return R},Z7:function(S){var R=null;bd.t8(S,89);R=jL.o6$($New(ix),$AsIntf(S,"PW"));bd.Cv(S,[37,9].slice(),true);switch(bd.Qe(S)){case 37:R.Name="*";bd.hB(S,116,true);bd.xr(S,true);bd.hB(S,133,true);bd.hB(S,9,true);break;case 9:R.Name=S.TK.getTokenValue();break;default:R.Name=bd.xY(S);bd.hB(S,56,true);bd.Cv(S,[127].slice(),true);if(bd.Qe(S)==127){bd.hB(S,17,false);bd.hB(S,9,false);bd.hB(S,18,false)}else R.Value=bd.U2(S)}
if(S.NeedsSemicolon)bd.hB(S,23,true);return R},gi:function(S){var R=null;bd.t8(S,19);R=jL.o6$($New(Ug),$AsIntf(S,"PW"));R.IndexSignature=bd.gx(S);if(S.NeedsSemicolon)bd.Dv(S,[23,16,24].slice());return R},gx:function(S){var R=null;bd.t8(S,19);R=jL.o6$($New(H8),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.hB(S,54,true);bd.FH(S,[130,128].slice(),true);R.IsStringIndex=bd.Qe(S)==130;bd.hB(S,20,true);bd.hB(S,54,true);R.Type=bd.iP(S);return R},q6:function(S){var R=null;bd.t8(S,107);R=jL.o6$($New(P4),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.FH(S,[25,83,15].slice(),true);if(bd.Qe(S)==25){do{R.TypeParameters.push(bd.Z2(S))}while(!(bd.Qe(S)!=24));bd.FH(S,[83,15].slice(),true)}
if(bd.Qe(S)==83){bd.xr(S,true);R.Extends.push(bd.EC(S));while(bd.Qe(S)==24){bd.xr(S,true);R.Extends.push(bd.EC(S))}}
bd.t8(S,15);R.Type=bd.C5(S);bd.t8(S,16);return R},ZS:function(S){var R=null;R=jL.o6$($New(rS),$AsIntf(S,"PW"));R.CallSignature=bd.uM(S);if(S.NeedsSemicolon)bd.Cz(S,[23,16].slice());return R},zb:function(S){var R=null;var lT=[],lT=[73,82,81,89,125,87,107,102,23,16].slice();bd.t8(S,125);R=jL.o6$($New(Mj),$AsIntf(S,"PW"));bd.Cv(S,[9].slice(),true);R.Name=bd.U2(S);bd.t8(S,15);bd.FH(S,lT,true);while(bd.Qe(S)!=16){switch(bd.Qe(S)){case 73:R.Classes.push(bd.VL(S));break;case 82:R.Exports.push(bd.BH(S));break;case 81:bd.TB(S);break;case 87:R.Functions.push(bd.V7(S));break;case 89:bd.Z7(S);break;case 125:R.Modules.push(bd.zb(S));break;case 107:R.Interfaces.push(bd.q6(S));break;case 102:R.Variables.push(bd.p8(S));break}
bd.FH(S,lT,true)}
bd.t8(S,16);return R},Pz:function(S){var R=null;var cN=[],cN=[115,73,122,82,81,89,87,107,23,16].slice();var FR=false,iT=null;bd.t8(S,126);bd.Cv(S,[9].slice(),true);R=jL.o6$($New(qw),$AsIntf(S,"PW"));R.Name=bd.U2(S);bd.t8(S,15);bd.FH(S,cN,true);while(bd.Qe(S)!=16){FR=bd.Qe(S)==115;if(FR)bd.FH(S,[73].slice(),true);switch(bd.Qe(S)){case 73:iT=bd.VL(S);iT.IsAbstract=FR;R.Classes.push(iT);break;case 81:bd.TB(S);break;case 87:R.Functions.push(bd.V7(S));break;case 89:bd.Z7(S);break;case 107:R.Interfaces.push(bd.q6(S));break}
bd.FH(S,cN,true)}
bd.t8(S,16);return R},C5:function(S){var R=null;var tg=[],tg=[9,8,92,25,17,19,16].slice();var ms=[],ms=[72,73,75,76,77,78,82,83,85,86,89,90,94,97,98,100].slice();bd.t8(S,15);R=jL.o6$($New(Z9),$AsIntf(S,"PW"));bd.Cv(S,tg.concat(ms),true);while(bd.Qe(S)!=16){R.Members.push(bd.x5(S));if(([23,24].indexOf(bd.Qe(S))>=0))bd.Cv(S,tg.concat(ms),true)}
bd.t8(S,16);return R},If:function(S){var R=null;bd.Dv(S,[112,110,111,22].slice());R=jL.o6$($New(a9),$AsIntf(S,"PW"));R.Name=bd.xY(S);R.IsRest=bd.Qe(S)==22;if(R.IsRest){bd.xr(S,true);R.Name=bd.xY(S);if(bd.hB(S,54,false))R.Type=bd.iP(S);bd.t8(S,18);return R}
bd.Dv(S,[112,110,111].slice());switch(bd.Qe(S)){case 112:R.AccessibilityModifier=0;bd.xr(S,false);break;case 110:R.AccessibilityModifier=1;bd.xr(S,false);break;case 111:R.AccessibilityModifier=2;bd.xr(S,false);break}
bd.Dv(S,[]);bd.FH(S,[53,54,56,24,18].slice(),true);R.IsOptional=bd.Qe(S)==53;if(R.IsOptional)bd.FH(S,[54,56,24,18].slice(),true);if(bd.Qe(S)==54)R.Type=bd.Hk(S);bd.Cz(S,[56,24,18].slice());if(bd.Qe(S)==56){bd.xr(S,true);R.DefaultValue=bd.xY(S)}
bd.Cz(S,[24,18].slice());return R},zm:function(S){var R=null;var Ky=[],Ky=[69,9,117,128,130,120,103,101,97,15,17,19].slice();var f5=null;bd.Cz(S,Ky);switch(bd.Qe(S)){case 17:R=bd.Hk(S);bd.t8(S,18);bd.sC(S);break;case 69:case 97:R=RA.rt($New(RA),$AsIntf(S,"PW"),bd.U2(S));if(bd.Qe(S)==25){do{$As(R,RA).Arguments.push(bd.fB(S))}while(!(bd.Qe(S)!=24));bd.t8(S,27);bd.sC(S)}
break;case 9:R=RA.rt($New(RA),$AsIntf(S,"PW"),S.TK.getTokenValue());bd.sC(S);break;case 117:R=jL.o6$($New(fc),$AsIntf(S,"PW"));bd.sC(S);break;case 128:R=jL.o6$($New(vW),$AsIntf(S,"PW"));bd.sC(S);break;case 103:R=null;bd.sC(S);break;case 101:R=jL.o6$($New(sl),$AsIntf(S,"PW"));$As(R,sl).Type=bd.Hk(S);break;case 130:R=jL.o6$($New(B4),$AsIntf(S,"PW"));bd.sC(S);break;case 120:R=jL.o6$($New(ZR),$AsIntf(S,"PW"));bd.sC(S);break;case 15:R=bd.C5(S);bd.sC(S);break;case 19:R=bd.wB(S);bd.sC(S);break}
while(bd.Qe(S)==19){f5=R;R=jL.o6$($New(hr),$AsIntf(S,"PW"));$As(R,hr).Type=f5;bd.hB(S,20,true);bd.sC(S)}
return R},Wl:function(S){var R=null;bd.Cz(S,[54,23].slice());R=jL.o6$($New(X5),$AsIntf(S,"PW"));if(bd.Qe(S)==23)return R;R.Type=bd.Hk(S);if(S.NeedsSemicolon)bd.Dv(S,[23,16,24].slice());return R},FH:function(S,b3,jm){var R=false;R=b3.indexOf(bd.sC(S))>=0;if((!R)&&jm)bd.K2(S,0);return R},hB:function(S,tv,BD){var R=false;R=bd.sC(S)==tv;if((!R)&&BD)bd.K2(S,tv);return R},sC:function(S){var R=0;R=S.TK.scan();return R},wB:function(S){var R=null;bd.t8(S,19);R=jL.o6$($New(i8),$AsIntf(S,"PW"));do{R.Types.push(bd.Hk(S))}while(!(bd.Qe(S)==20));bd.t8(S,20);return R},Hk:function(S){var R=null;var HQ=[],HQ=[69,9,117,128,130,120,103,101,97,92,25,15,17,19].slice();var oi=0,EML=false,SW=null;oi=S.TK.getTextPos();bd.FH(S,HQ,true);if(bd.Qe(S)==17){EML=true;bd.Cv(S,HQ.concat([112,111,110,18,22]),true);if(!([112,111,110,18,22].indexOf(bd.Qe(S))>=0)){if(S.TK.isIdentifier()){bd.FH(S,[25,47,54,24,53,21,19,18].slice(),true);EML=([54,53,24,18].indexOf(bd.Qe(S))>=0)}else EML=!bd.Qe(S)==17}
S.TK.setTextPos(oi);bd.FH(S,HQ,true);if(EML)return bd.Tv(S)}
if(bd.Qe(S)==25)return bd.Tv(S);if(bd.Qe(S)==92)return bd.p2(S);R=bd.zm(S);while(bd.Qe(S)==47){if(!$Is(R,zj)){SW=R;R=jL.o6$($New(zj),$AsIntf(S,"PW"));$As(R,zj).Types.push(SW)}
bd.FH(S,HQ,true);$As(R,zj).Types.push(bd.zm(S))}
return R},gf:function(S){var R=null;bd.t8(S,132);R=jL.o6$($New(QE),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.FH(S,[25,56].slice(),true);if(bd.Qe(S)==25){R.TypeParameters.push(bd.Z2(S));bd.hB(S,56,true)}
R.Type=bd.Hk(S);if(S.NeedsSemicolon)bd.t8(S,23);return R},iP:function(S){var R=null;bd.t8(S,54);R=bd.Hk(S);return R},fB:function(S){var R=null;bd.Cz(S,[25,24].slice());R=jL.o6$($New(wX),$AsIntf(S,"PW"));R.Type=bd.Hk(S);bd.Cz(S,[27,24].slice());return R},x5:function(S){var R=null;var M1=[],BI=[],BI=[9,8,110,92,25,17,19].slice();var To=[],To=[72,73,75,76,77,78,82,83,85,86,89,90,94,97,98,100].slice();var w2=0,Pd=false,ED="",IR=false;w2=S.TK.getTextPos();bd.Dv(S,BI.concat(To));if(bd.Qe(S)==92){Pd=!bd.FH(S,[53,54].slice(),false);S.TK.setTextPos(w2-3);S.TK.scan();if(Pd)return bd.KS(S)}
if(([17,25].indexOf(bd.Qe(S))>=0))return bd.uM(S);if(bd.Qe(S)==19)return bd.gx(S);if(S.TK.isIdentifier()||[9,8,92].concat(To).indexOf(S.TK.getToken())>=0){ED=bd.xY(S);bd.FH(S,[25,53,54,17].slice(),true);IR=bd.Qe(S)==53;if(IR)bd.FH(S,[54,17,25].slice(),true);switch(bd.Qe(S)){case 54:R=bd.Wl(S);$As(R,X5).Nullable=IR;break;case 17:case 25:R=bd.ZS(S);break}
R.TypeArguments=M1;R.Name=ED}
return R},Z2:function(S){var R=null;bd.Cz(S,[25,24].slice());R=jL.o6$($New(vE),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.FH(S,[83,27,24].slice(),true);if(bd.Qe(S)==83){R.ExtendsType=bd.Hk(S);bd.Cz(S,[27,24].slice())}
return R},EC:function(S){var R=null;bd.Dv(S,[]);R=jL.o6$($New(uk),$AsIntf(S,"PW"));R.Name=bd.U2(S);if(bd.Qe(S)==25){do{R.Arguments.push(bd.fB(S))}while(!(bd.Qe(S)!=24));bd.sC(S)}
return R},p8:function(S){var R=null;bd.t8(S,102);R=jL.o6$($New(kZ),$AsIntf(S,"PW"));bd.xr(S,true);R.Name=bd.xY(S);bd.hB(S,54,true);R.Type=bd.Hk(S);return R},HR:function(S,sP){var R="";S.TK=i.createScanner(0,true,0,sP);S.wa=i.createSourceFile("main",sP,0);try{bd.cb(S)}catch($e){var Bc=$W($e);console.error(Bc.FMessage)}
R=bd.on(S);return R},Destroy:TObject.Destroy};bd.$Intf={PW:[]}
function yF(cm){var R="";var fk=[];if(cm.length==0)return"Unknown";fk=(cm).split("\\");R=fk[(fk.length-1)];fk=(cm).split("\/");R=fk[(fk.length-1)];R=StrReplace(R,"-","_");R=$StrSet(R,1,(R.charAt(0)).toUpperCase());return R};var NP=["vPublic","vProtected","vPrivate"];var jL={$ClassName:"TCustomDeclaration",$Parent:TObject,$Init:function($){TObject.$Init($);$.Zv=null},wE:function(S){++EN},FD:function(S,Xz){qq.push(Xz)},o6:function(S,HW){S.Zv=HW;return S},fQ:function(S){--EN},H1:function(S){qq.pop()},pT:function(S){var R="";R=DupeString("  ",EN);return R},L5:function(S){var R="";var pu=0;R="";if(qq.length>0){R+=qq[0];var $t5;for(pu=0+1,$t5=qq.length;pu<$t5;pu++){R+="."+qq[pu]}}
return R},Destroy:TObject.Destroy,o6$:function($){return $.ClassType.o6.apply($.ClassType,arguments)},sw$:function($){return $.ClassType.sw($)}};var iy={$ClassName:"TCustomType",$Parent:jL,$Init:function($){jL.$Init($)},Destroy:TObject.Destroy,o6:jL.o6,sw:jL.sw};var iN={$ClassName:"TCustomNamedType",$Parent:iy,$Init:function($){iy.$Init($)},sw:function(S){var R="";R="J"+iN.wi$(S);return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)},wi$:function($){return $.ClassType.wi($)}};var wo={$ClassName:"TPredefinedType",$Parent:iN,$Init:function($){iN.$Init($)},sw:function(S){var R="";R=iN.wi$(S);return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)},wi:iN.wi};var fc={$ClassName:"TVariantType",$Parent:wo,$Init:function($){wo.$Init($)},wi:function(S){var R="";R="Variant";return R},Destroy:TObject.Destroy,o6:jL.o6,sw:wo.sw,wi$:function($){return $.ClassType.wi($)}};var FB={$ClassName:"TNamedDeclaration",$Parent:jL,$Init:function($){jL.$Init($);$.Name=""},Destroy:TObject.Destroy,o6:jL.o6,sw:jL.sw};var kZ={$ClassName:"TVariableDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.Type=null},sw:function(S){var R="";console.log("not implemented: TVariableDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var zj={$ClassName:"TUnionType",$Parent:iy,$Init:function($){iy.$Init($);$.Types=[]},sw:function(S){var R="";var VY=0;var Rc=null;R="Variant {";var $t6;for(VY=0,$t6=(S.Types.length-1);VY<$t6;VY++){R+=(S.Types[VY])?jL.sw$(S.Types[VY]):"void";R+=" or "}
Rc=S.Types[(S.Types.length-1)];R+=(Rc)?jL.sw$(Rc):"void";R+="}";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var uk={$ClassName:"TTypeReference",$Parent:jL,$Init:function($){jL.$Init($);$.Name="";$.Arguments=[]},sw:function(S){var R="";var o1=0;R="J"+S.Name;if(S.Arguments.length>0){R+=" {"+jL.sw$(S.Arguments[0]);var $t7;for(o1=0+1,$t7=S.Arguments.length;o1<$t7;o1++){R+=", "+jL.sw$(S.Arguments[o1])}
R+="} "}
return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var vE={$ClassName:"TTypeParameter",$Parent:jL,$Init:function($){jL.$Init($);$.Name="";$.ExtendsType=null},sw:function(S){var R="";R=S.Name;if(S.ExtendsType)R+=" extends "+jL.sw$(S.ExtendsType);return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var sl={$ClassName:"TTypeOfType",$Parent:iN,$Init:function($){iN.$Init($);$.Type=null},wi:function(S){var R="";R="type of";return R},Destroy:TObject.Destroy,o6:jL.o6,sw:iN.sw,wi$:function($){return $.ClassType.wi($)}};var wX={$ClassName:"TTypeArgument",$Parent:jL,$Init:function($){jL.$Init($);$.Type=null},sw:function(S){var R="";if(S.Type){R=jL.sw$(S.Type)}else R="Variant";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var QE={$ClassName:"TTypeAlias",$Parent:FB,$Init:function($){FB.$Init($);$.Type=null},sw:function(S){var R="";R=jL.pT(S.ClassType)+S.Name+" = "+jL.sw$(S.Type)+";"+"\r\n";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var i8={$ClassName:"TTupleType",$Parent:iy,$Init:function($){iy.$Init($)},sw:function(S){var R="";R="TupletType";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var B4={$ClassName:"TStringType",$Parent:wo,$Init:function($){wo.$Init($)},wi:function(S){var R="";R="String";return R},Destroy:TObject.Destroy,o6:jL.o6,sw:wo.sw,wi$:function($){return $.ClassType.wi($)}};var nh={$ClassName:"TCustomTypeMember",$Parent:FB,$Init:function($){FB.$Init($);$.TypeParameters=[];$.Visibility=0;$.IsStatic=false;$.TypeArguments=[]},o6:function(S,q8){jL.o6(S,q8);S.Visibility=0;return S},Destroy:TObject.Destroy,o6$:function($){return $.ClassType.o6.apply($.ClassType,arguments)},sw:jL.sw};var eE={$ClassName:"TClassTypeMember",$Parent:nh,$Init:function($){nh.$Init($)},Destroy:TObject.Destroy,o6:nh.o6,sw:jL.sw};var X5={$ClassName:"TPropertyMemberDeclaration",$Parent:eE,$Init:function($){eE.$Init($);$.Nullable=false;$.Type=null},sw:function(S){var R="";var HI=0;var k2=null;R=jL.pT(S.ClassType)+XE(S.Name);if(S.TypeArguments.length>0){var G9=[];R+="{<";G9=S.TypeArguments;var $t8;for(HI=0,$t8=G9.length;HI<$t8;HI++){k2=G9[HI];R+=jL.sw$(k2)}
R+=">}"}
R+=": ";if(S.Type){if($Is(S.Type,Z9))R+="record"+"\r\n";R+=jL.sw$(S.Type)}else R+="Variant";R+=";";if(S.Nullable)R+=" \/\/ nullable";R+="\r\n";return R},Destroy:TObject.Destroy,o6:nh.o6,sw$:function($){return $.ClassType.sw($)}};var a9={$ClassName:"TParameter",$Parent:FB,$Init:function($){FB.$Init($);$.DefaultValue="";$.IsRest=$.IsOptional=false;$.AccessibilityModifier=0;$.Type=null},sw:function(S){var R="";R=S.Name+": ";if(S.Type){if($Is(S.Type,Z9))R+="record"+"\r\n";R+=jL.sw$(S.Type)}else R+="Variant";if(S.DefaultValue!="")R+=" = "+S.DefaultValue;if(S.IsRest)R+=" {...}";return R},Tl:function(S,zF){var R="";var B1=null;R=XE(S.Name);if(!zF){R+=": ";if(S.Type){if($Is(S.Type,Z9))R+="record"+"\r\n";if($Is(S.Type,v2)){B1=$As(S.Type,v2).ResultType;R+=(B1)?"function":"procedure"}
R+=jL.sw$(S.Type)}else R+="Variant"}
return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var Z9={$ClassName:"TObjectType",$Parent:iy,$Init:function($){iy.$Init($);$.Members=[]},sw:function(S){var R="";var yQ=0;var qO=null,Ia=null;var mr=[];jL.wE(S.ClassType);mr=S.Members;var $t9;for(yQ=0,$t9=mr.length;yQ<$t9;yQ++){qO=mr[yQ];if($Is(qO,qD)){R+=jL.pT(S.ClassType);Ia=$As(qO,qD).Type;R+=(Ia)?"function":"procedure";R+=jL.sw$(qO)+";"+"\r\n"}else R+=jL.sw$(qO)}
jL.fQ(S.ClassType);R+=jL.pT(S.ClassType)+"end";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var qw={$ClassName:"TNamespaceDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.Namespaces=[];$.Interfaces=[];$.Classes=[];$.Functions=[];$.Enums=[]},sw:function(S){var R="";var Kj=0;var LT=null,Xl=0;var U5=null,xc=0;var lm=null,O4p=0;var mh=null,jg=0;var JE=null;var Io=[];jL.FD(S.ClassType,S.Name);if(S.Enums.length+S.Classes.length+S.Interfaces.length>0){var xw=[],cI=[],oG=[];R+="type"+"\r\n";jL.wE(S.ClassType);oG=S.Enums;var $tA;for(Kj=0,$tA=oG.length;Kj<$tA;Kj++){LT=oG[Kj];R+=jL.sw$(LT)}
cI=S.Classes;var $tB;for(Xl=0,$tB=cI.length;Xl<$tB;Xl++){U5=cI[Xl];R+=jL.sw$(U5)}
xw=S.Interfaces;var $tC;for(xc=0,$tC=xw.length;xc<$tC;xc++){lm=xw[xc];R+=jL.sw$(lm)}
jL.fQ(S.ClassType)}
if(S.Functions.length>0){var Nh=[];Nh=S.Functions;var $tD;for(O4p=0,$tD=Nh.length;O4p<$tD;O4p++){mh=Nh[O4p];R+=jL.sw$(mh)}
R+="\r\n"}
Io=S.Namespaces;var $tE;for(jg=0,$tE=Io.length;jg<$tE;jg++){JE=Io[jg];R+=jL.sw$(JE)}
R+="\r\n";jL.H1(S.ClassType);return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var RA={$ClassName:"TNamedType",$Parent:iN,$Init:function($){iN.$Init($);$.Arguments=[];$.yd=""},rt:function(S,gT,kV){jL.o6(S,gT);S.yd=kV;return S},sw:function(S){var R="";var kP=0;var DV=null;R=iN.sw(S);if(S.Arguments.length>0){var Lc=[];R+="{<";Lc=S.Arguments;var $tF;for(kP=0,$tF=Lc.length;kP<$tF;kP++){DV=Lc[kP];R+=jL.sw$(DV)}
R+=">}"}
return R},wi:function(S){var R="";R=S.yd;return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)},wi$:function($){return $.ClassType.wi($)}};var Mj={$ClassName:"TModuleDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.Variables=[];$.Interfaces=[];$.Classes=[]},sw:function(S){var R="";var Y3=0;var pP=null,g5=0;var J7=null,Uq=0;var AW=null;R="";if(S.Classes.length+S.Interfaces.length>0){var Ux=[],go=[];R+="type"+"\r\n";jL.wE(S.ClassType);go=S.Classes;var $tG;for(Y3=0,$tG=go.length;Y3<$tG;Y3++){pP=go[Y3];R=R+jL.sw$(pP)}
Ux=S.Interfaces;var $tH;for(g5=0,$tH=Ux.length;g5<$tH;g5++){J7=Ux[g5];R=R+jL.sw$(J7)}
jL.fQ(S.ClassType)}
if(S.Variables.length>0){var F7=[];R+="var"+"\r\n";jL.wE(S.ClassType);F7=S.Variables;var $tI;for(Uq=0,$tI=F7.length;Uq<$tI;Uq++){AW=F7[Uq];R=R+jL.sw$(AW)}
jL.fQ(S.ClassType)}
return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var rS={$ClassName:"TMethodDeclaration",$Parent:eE,$Init:function($){eE.$Init($);$.CallSignature=null},sw:function(S){var R="";var iZ="";var Kl="";var nm=0,lf=0;var aS=null,gg=0;var hZ=[];nm=0;hZ=S.CallSignature.ParameterList;var $tJ;for(lf=0,$tJ=hZ.length;lf<$tJ;lf++){aS=hZ[lf];if(aS.IsOptional)++nm}
iZ=jL.pT(S.ClassType);iZ+=(S.CallSignature.Type)?"function":"procedure";iZ+=" "+XE(S.Name);Kl=";";Kl+=(nm>0)?" overload;":"";Kl+="\r\n";R="";var $tK;for(gg=0,$tK=nm;gg<=$tK;gg++){R+=iZ+qD.I1(S.CallSignature,gg)+Kl}
return R},Destroy:TObject.Destroy,o6:nh.o6,sw$:function($){return $.ClassType.sw($)}};var P4={$ClassName:"TInterfaceDeclaration",$Parent:jL,$Init:function($){jL.$Init($);$.TypeParameters=[];$.Type=null;$.Name="";$.Extends=[];$.IsExport=false},sw:function(S){var R="";var HG=0;var Dxv=null,Yl=0;R+=jL.pT(S.ClassType)+"J"+S.Name;if(S.TypeParameters.length>0){var AP=[];R+="{<";AP=S.TypeParameters;var $tL;for(HG=0,$tL=AP.length;HG<$tL;HG++){Dxv=AP[HG];R+=jL.sw$(Dxv)}
R+=">}"}
R+=" = class external";if(S.Extends.length>0){R+="(";R+=jL.sw$(S.Extends[0]);var $tM;for(Yl=0+1,$tM=S.Extends.length;Yl<$tM;Yl++){R+=", "+jL.sw$(S.Extends[Yl])}
R+=")"}
R+="\r\n";R+=jL.sw$(S.Type);R+=";"+"\r\n"+"\r\n";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var H8={$ClassName:"TIndexSignature",$Parent:nh,$Init:function($){nh.$Init($);$.IsStringIndex=false;$.Type=null},sw:function(S){var R="";R=jL.pT(S.ClassType)+"\/\/ ";R+="property Item["+S.Name+": ";R+=(S.IsStringIndex)?"String":"Integer";R+="]: "+jL.sw$(S.Type)+";"+"\r\n";return R},Destroy:TObject.Destroy,o6:nh.o6,sw$:function($){return $.ClassType.sw($)}};var Ug={$ClassName:"TIndexMemberDeclaration",$Parent:eE,$Init:function($){eE.$Init($);$.IndexSignature=null},sw:function(S){var R="";R=jL.sw$(S.IndexSignature)+";"+"\r\n";return R},Destroy:TObject.Destroy,o6:nh.o6,sw$:function($){return $.ClassType.sw($)}};var ix={$ClassName:"TImportDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.Value=""},sw:function(S){var R="";console.log("not implemented: TImportDeclaration.GetAsCode");return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var v2={$ClassName:"TFunctionType",$Parent:iN,$Init:function($){iN.$Init($);$.ParameterList=[];$.ResultType=null},sw:function(S){var R="";var Ku=0;if(S.ParameterList.length>0){R="("+bb.ow(S.ParameterList[0],false);var $tN;for(Ku=0+1,$tN=S.ParameterList.length;Ku<$tN;Ku++){R+="; "+bb.ow(S.ParameterList[Ku],false)}
R+=")"}
if(S.ResultType)R+=": "+jL.sw$(S.ResultType);return R},uU:function(S,KJ){var R="";var z2=false;var bp=0,jG=0;bp=0;if(S.ParameterList.length>0){if(!(S.ParameterList[0].IsOptional&&KJ==0)){bp+=(S.ParameterList[0].IsOptional?1:0);z2=S.ParameterList.length>=2&&aW(S.ParameterList[0],S.ParameterList[1])&&((!S.ParameterList[0].IsOptional)||bp<KJ);R="("+bb.ow(S.ParameterList[0],z2);var $tO;for(jG=0+1,$tO=S.ParameterList.length;jG<$tO;jG++){if(S.ParameterList[jG].IsOptional&&bp>=KJ)break;bp+=(S.ParameterList[jG].IsOptional?1:0);R+=(z2)?", ":"; ";z2=jG+1<S.ParameterList.length&&aW(S.ParameterList[0],S.ParameterList[1])&&((!S.ParameterList[jG].IsOptional)||bp<KJ);R+=bb.ow(S.ParameterList[jG],z2)}
R+=")"}}
if(S.ResultType)R+=": "+jL.sw$(S.ResultType);return R},wi:function(S){var R="";R="function";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)},wi$:function($){return $.ClassType.wi($)}};var bb={$ClassName:"TFunctionParameter",$Parent:FB,$Init:function($){FB.$Init($);$.Type=null;$.IsOptional=false},sw:function(S){var R="";R=XE(S.Name)+": ";if(S.Type){if($Is(S.Type,Z9))R+="record"+"\r\n";R+=jL.sw$(S.Type)}else R+="Variant";return R},ow:function(S,EF){var R="";R=XE(S.Name);if(!EF){R+=": ";if(S.Type){if($Is(S.Type,Z9))R+="record"+"\r\n";R+=jL.sw$(S.Type)}else R+="Variant"}
return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var cq={$ClassName:"TFunctionDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.Type=null},sw:function(S){var R="";var oP="";var J5="";var xm=0,OW=0;var rM=null,rw=0;var Db=[];xm=0;Db=S.Type.ParameterList;var $tP;for(OW=0,$tP=Db.length;OW<$tP;OW++){rM=Db[OW];if(rM.IsOptional)++xm}
oP=jL.pT(S.ClassType);oP+=(S.Type.ResultType)?"function":"procedure";oP+=" "+XE(S.Name);J5=";"+((xm>0)?" overload;":"");J5+="\r\n";R="";var $tQ;for(rw=0,$tQ=xm;rw<=$tQ;rw++){R+=oP+v2.uU(S.Type,rw)+J5}
return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var vW={$ClassName:"TFloatType",$Parent:wo,$Init:function($){wo.$Init($)},wi:function(S){var R="";R="Float";return R},Destroy:TObject.Destroy,o6:jL.o6,sw:wo.sw,wi$:function($){return $.ClassType.wi($)}};var wJ={$ClassName:"TExportDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.yA=false},sw:function(S){var R="";R="";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var zi={$ClassName:"TEnumerationItem",$Parent:jL,$Init:function($){jL.$Init($);$.Name=$.Value=""},sw:function(S){var R="";R=S.Name;return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var nw={$ClassName:"TEnumerationDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.Items=[]},sw:function(S){var R="";var mY=0;var sv=null;var Il=[];R+=jL.pT(S.ClassType)+"T"+S.Name+" = Variant;"+"\r\n";R+=jL.pT(S.ClassType)+"T"+S.Name+"Helper = strict helper for T"+S.Name+"\r\n";jL.wE(S.ClassType);Il=S.Items;var $tR;for(mY=0,$tR=Il.length;mY<$tR;mY++){sv=Il[mY];R+=jL.pT(S.ClassType)+"const "+XE(jL.sw$(sv));if(sv.Value!=""){try{R+=" = "+(parseInt(sv.Value,10)).toString()+";"+"\r\n"}catch($e){R+=" = '"+sv.Value+"';"+"\r\n"}}else R+=" = '"+sv.Name+"';"+"\r\n"}
jL.fQ(S.ClassType);R+=jL.pT(S.ClassType)+"end;"+"\r\n";R+="\r\n";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var Oo={$ClassName:"TConstructorType",$Parent:iN,$Init:function($){iN.$Init($);$.ResultType=null;$.ParameterList=[]},sw:function(S){var R="";var d7=0;if(S.ParameterList.length>0){R="("+bb.ow(S.ParameterList[0],false);var $tS;for(d7=0+1,$tS=S.ParameterList.length;d7<$tS;d7++){R+="; "+bb.ow(S.ParameterList[d7],false)}
R+=")"}
if(S.ResultType)R+=": "+jL.sw$(S.ResultType);return R},wi:function(S){var R="";R="constructor";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)},wi$:function($){return $.ClassType.wi($)}};var r2={$ClassName:"TConstructorDeclaration",$Parent:eE,$Init:function($){eE.$Init($);$.Type=null},sw:function(S){var R="";R=jL.pT(S.ClassType)+"constructor Create";if(S.Type)R+=jL.sw$(S.Type);R+=";"+"\r\n";return R},Destroy:TObject.Destroy,o6:nh.o6,sw$:function($){return $.ClassType.sw($)}};var Ve={$ClassName:"TClassDeclaration",$Parent:P4,$Init:function($){P4.$Init($);$.Members=[];$.IsAbstract=false},sw:function(S){var R="";var QC=0;var KQ=0;var n1=null;var Gq=[];R+=jL.pT(S.ClassType)+"J"+S.Name+" = class external '"+S.Name+"'";if(S.Extends.length>0){R+="(";R+=jL.sw$(S.Extends[0]);var $tT;for(QC=0+1,$tT=S.Extends.length;QC<$tT;QC++){R+=", "+jL.sw$(S.Extends[QC])}
R+=")"}
R+="\r\n";jL.wE(S.ClassType);Gq=S.Members;var $tU;for(KQ=0,$tU=Gq.length;KQ<$tU;KQ++){n1=Gq[KQ];R+=jL.sw$(n1)}
jL.fQ(S.ClassType);R+=jL.pT(S.ClassType)+"end;"+"\r\n"+"\r\n";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var qD={$ClassName:"TCallSignature",$Parent:nh,$Init:function($){nh.$Init($);$.ParameterList=[];$.Type=null;$.TypeParameters=[]},sw:function(S){var R="";var c4=0;var i7=null,qW=0;R="";if(S.TypeParameters.length>0){var t6=[];R+="{<";t6=S.TypeParameters;var $tV;for(c4=0,$tV=t6.length;c4<$tV;c4++){i7=t6[c4];R+=jL.sw$(i7)}
R+=">}"}
if(S.ParameterList.length>0){R+="(";var $tW;for(qW=0,$tW=(S.ParameterList.length-1);qW<$tW;qW++){R+=a9.Tl(S.ParameterList[qW],false)+"; "}
R+=a9.Tl(S.ParameterList[(S.ParameterList.length-1)],false)+")"}
if(S.Type){R+=": ";if($Is(S.Type,Z9))R+="record"+"\r\n";R+=jL.sw$(S.Type)}
R+=";";return R},I1:function(S,IW){var R="";var u5=false;var zC=0,Em=0;zC=0;if(S.ParameterList.length>0){if(!(S.ParameterList[0].IsOptional&&IW==0)){zC+=(S.ParameterList[0].IsOptional?1:0);u5=S.ParameterList.length>=2&&lA(S.ParameterList[0],S.ParameterList[1])&&((!S.ParameterList[0].IsOptional)||zC<IW);R="("+a9.Tl(S.ParameterList[0],u5);var $tX;for(Em=0+1,$tX=S.ParameterList.length;Em<$tX;Em++){if(S.ParameterList[Em].IsOptional&&zC>=IW)break;zC+=(S.ParameterList[Em].IsOptional?1:0);R+=(u5)?", ":"; ";u5=Em+1<S.ParameterList.length&&lA(S.ParameterList[Em],S.ParameterList[Em+1])&&((!S.ParameterList[Em].IsOptional)||zC<IW);R+=a9.Tl(S.ParameterList[Em],u5)}
R+=")"}}
if(S.Type){R+=": ";if($Is(S.Type,Z9))R+="record"+"\r\n";R+=jL.sw$(S.Type)}
return R},Destroy:TObject.Destroy,o6:nh.o6,sw$:function($){return $.ClassType.sw($)}};var ZR={$ClassName:"TBooleanType",$Parent:wo,$Init:function($){wo.$Init($)},wi:function(S){var R="";R="Boolean";return R},Destroy:TObject.Destroy,o6:jL.o6,sw:wo.sw,wi$:function($){return $.ClassType.wi($)}};var hr={$ClassName:"TArrayType",$Parent:iy,$Init:function($){iy.$Init($);$.Type=null},sw:function(S){var R="";R="array of "+jL.sw$(S.Type);return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var Ci={$ClassName:"TAmbientVariableDeclaration",$Parent:jL,$Init:function($){jL.$Init($);$.IsConst=false;$.AmbientBindingList=[]},sw:function(S){var R="";var WN=0;var F5=null;var nr=[];nr=S.AmbientBindingList;var $tY;for(WN=0,$tY=nr.length;WN<$tY;WN++){F5=nr[WN];R+=jL.pT(S.ClassType)+jL.sw$(F5)}
R+=";"+"\r\n";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var nx={$ClassName:"TAmbientBodyElement",$Parent:jL,$Init:function($){jL.$Init($)},Destroy:TObject.Destroy,o6:jL.o6,sw:jL.sw};var br={$ClassName:"TAmbientPropertyMemberDeclaration",$Parent:nx,$Init:function($){nx.$Init($);$.Visibility=0;$.IsStatic=false;$.Name=""},Destroy:TObject.Destroy,o6:jL.o6,sw:jL.sw};var Rs={$ClassName:"TAmbientPropertyMemberDeclarationProperty",$Parent:br,$Init:function($){br.$Init($);$.Type=null},sw:function(S){var R="";R=jL.pT(S.ClassType);if(S.IsStatic)R+="class var ";R+=XE(S.Name);R+=": "+((S.Type)?jL.sw$(S.Type):"Variant");R+=";"+"\r\n";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var yr={$ClassName:"TAmbientPropertyMemberDeclarationMethod",$Parent:br,$Init:function($){br.$Init($);$.CallSignature=null},sw:function(S){var R="";var Xq="";var tK="";var oH=0,xR=0;var x4=null,f1=0;var HK=[];oH=0;HK=S.CallSignature.ParameterList;var $tZ;for(xR=0,$tZ=HK.length;xR<$tZ;xR++){x4=HK[xR];if(x4.IsOptional)++oH}
Xq=jL.pT(S.ClassType);Xq+=(S.CallSignature.Type)?"function":"procedure";Xq+=" "+XE(S.Name);tK=(oH>0)?" overload;":"";tK+=";"+"\r\n";R="";var $ta;for(f1=0,$ta=oH;f1<=$ta;f1++){R+=Xq+qD.I1(S.CallSignature,f1)+tK}
return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var Ob={$ClassName:"TAmbientNamespaceDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.TypeAliases=[];$.Namespaces=[];$.Variables=[];$.Interfaces=[];$.Enums=[];$.Functions=[];$.Classes=[]},sw:function(S){var R="";var TtD=0,Ty=0;var bJ=null,DQ=0;var Uv=null,S3=0;var d9=null,T7=0;var Nx=null,Ka=0;var eG=null,Su=0;var cy=null,JN=0;var uW=null,n8=0;var yN=null,rD=0;var Q8=null;var MG=[],Ow=[];jL.FD(S.ClassType,S.Name);TtD=0;Ow=S.Variables;var $tb;for(Ty=0,$tb=Ow.length;Ty<$tb;Ty++){bJ=Ow[Ty];if(bJ.IsConst)++TtD}
if(TtD>0){var Xy=[];R+="const"+"\r\n";jL.wE(S.ClassType);Xy=S.Variables;var $tc;for(DQ=0,$tc=Xy.length;DQ<$tc;DQ++){Uv=Xy[DQ];if(Uv.IsConst)R=R+jL.sw$(Uv)}
jL.fQ(S.ClassType);R+="\r\n"}
if(S.Enums.length+S.Classes.length+S.Interfaces.length+S.TypeAliases.length>0){var zY=[],kS=[],Vo=[],FZ=[];R+="type"+"\r\n";jL.wE(S.ClassType);kS=S.Enums;var $td;for(S3=0,$td=kS.length;S3<$td;S3++){d9=kS[S3];R+=jL.sw$(d9)}
zY=S.Classes;var $te;for(T7=0,$te=zY.length;T7<$te;T7++){Nx=zY[T7];R+=jL.sw$(Nx)}
FZ=S.Interfaces;var $tf;for(Ka=0,$tf=FZ.length;Ka<$tf;Ka++){eG=FZ[Ka];R+=jL.sw$(eG)}
Vo=S.TypeAliases;var $tg;for(Su=0,$tg=Vo.length;Su<$tg;Su++){cy=Vo[Su];R+=jL.sw$(cy)}
jL.fQ(S.ClassType)}
if(S.Functions.length>0){var c5=[];c5=S.Functions;var $th;for(JN=0,$th=c5.length;JN<$th;JN++){uW=c5[JN];R+=jL.sw$(uW)}
R+="\r\n"}
if(S.Variables.length-TtD>0){var pY=[];R+="var"+"\r\n";jL.wE(S.ClassType);pY=S.Variables;var $ti;for(n8=0,$ti=pY.length;n8<$ti;n8++){yN=pY[n8];if(!yN.IsConst)R=R+jL.sw$(yN)}
jL.fQ(S.ClassType);R+="\r\n"}
MG=S.Namespaces;var $tj;for(rD=0,$tj=MG.length;rD<$tj;rD++){Q8=MG[rD];R+=jL.sw$(Q8)}
R+="\r\n";jL.H1(S.ClassType);return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var vO={$ClassName:"TAmbientModuleDeclaration",$Parent:jL,$Init:function($){jL.$Init($);$.Interfaces=[];$.Namespaces=[];$.Modules=[];$.Classes=[];$.Functions=[];$.TypeAliases=[];$.IdentifierPath="";$.Enums=[];$.Variables=[]},sw:function(S){var R="";var Jt=0,sW=0;var Ok=null,Jq=0;var RR=null,UG=0;var wF=null,P9L=0;var oA=null,mL=0;var hX=null,Sn=0;var yY=null,ia=0;var VC=null,ai=0;var LX=null,iM=0;var BR=null,qa=0;var w9=null;var zN=[],Pr=[],sn=[];R="\/\/"+S.IdentifierPath+"\r\n"+"\r\n";Jt=0;zN=S.Variables;var $tk;for(sW=0,$tk=zN.length;sW<$tk;sW++){Ok=zN[sW];if(Ok.IsConst)++Jt}
if(Jt>0){var kQ=[];R+="const"+"\r\n";jL.wE(S.ClassType);kQ=S.Variables;var $tl;for(Jq=0,$tl=kQ.length;Jq<$tl;Jq++){RR=kQ[Jq];if(RR.IsConst)R=R+jL.sw$(RR)}
jL.fQ(S.ClassType);R+="\r\n"}
if(S.Enums.length+S.Classes.length+S.Interfaces.length>0){var ke=[],Vu=[],fS=[],AB=[];R+="type"+"\r\n";jL.wE(S.ClassType);Vu=S.Enums;var $tm;for(UG=0,$tm=Vu.length;UG<$tm;UG++){wF=Vu[UG];R+=jL.sw$(wF)}
ke=S.Classes;var $tn;for(P9L=0,$tn=ke.length;P9L<$tn;P9L++){oA=ke[P9L];R+=jL.sw$(oA)}
AB=S.Interfaces;var $to;for(mL=0,$to=AB.length;mL<$to;mL++){hX=AB[mL];R+=jL.sw$(hX)}
fS=S.TypeAliases;var $tp;for(Sn=0,$tp=fS.length;Sn<$tp;Sn++){yY=fS[Sn];R+=jL.sw$(yY)}
jL.fQ(S.ClassType)}
Pr=S.Modules;var $tq;for(ia=0,$tq=Pr.length;ia<$tq;ia++){VC=Pr[ia];R+=jL.sw$(VC)}
if(S.Functions.length>0){var Tf=[];Tf=S.Functions;var $tr;for(ai=0,$tr=Tf.length;ai<$tr;ai++){LX=Tf[ai];R+=jL.sw$(LX)}
R+="\r\n"}
if(S.Variables.length-Jt>0){var wz=[];R+="var"+"\r\n";jL.wE(S.ClassType);wz=S.Variables;var $ts;for(iM=0,$ts=wz.length;iM<$ts;iM++){BR=wz[iM];if(!BR.IsConst)R=R+jL.sw$(BR)}
jL.fQ(S.ClassType);R+="\r\n"}
sn=S.Namespaces;var $tt;for(qa=0,$tt=sn.length;qa<$tt;qa++){w9=sn[qa];R+=jL.sw$(w9)}
R+="\r\n";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var Sh={$ClassName:"TAmbientFunctionDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.CallSignature=null},sw:function(S){var R="";var Dj="";var Cu="";var dk=0,hY=0;var mo=null,pA=0;var eH=[];dk=0;eH=S.CallSignature.ParameterList;var $tu;for(hY=0,$tu=eH.length;hY<$tu;hY++){mo=eH[hY];if(mo.IsOptional)++dk}
Dj=jL.pT(S.ClassType);Dj+=(S.CallSignature.Type)?"function":"procedure";Dj+=" "+XE(S.Name);Cu=";"+((dk>0)?" overload;":"");if(jL.L5(S.ClassType)!="")Cu+=" external '"+jL.L5(S.ClassType)+"."+S.Name+"'";Cu+="\r\n";R="";var $tv;for(pA=0,$tv=dk;pA<=$tv;pA++){R+=Dj+qD.I1(S.CallSignature,pA)+Cu}
return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var Pg={$ClassName:"TAmbientEnumerationDeclaration",$Parent:nw,$Init:function($){nw.$Init($)},Destroy:TObject.Destroy,o6:jL.o6,sw:nw.sw};var mG={$ClassName:"TAmbientDeclaration",$Parent:FB,$Init:function($){FB.$Init($);$.Variables=[];$.Namespaces=[];$.Modules=[];$.Classes=[];$.Functions=[]},sw:function(S){var R="";var LF=0;var gn=null,XU=0;var EQ=null,VB=0;var SI=null,Ye=0;var o7=null,mE=0;var ay=null;var ul=[],yJ=[],jj=[],wI=[];yJ=S.Functions;var $tw;for(LF=0,$tw=yJ.length;LF<$tw;LF++){gn=yJ[LF];R+=jL.sw$(gn)}
ul=S.Modules;var $tx;for(XU=0,$tx=ul.length;XU<$tx;XU++){EQ=ul[XU];R+=jL.sw$(EQ)}
if(S.Classes.length>0){var m3=[];R+="type"+"\r\n";jL.wE(S.ClassType);m3=S.Classes;var $ty;for(VB=0,$ty=m3.length;VB<$ty;VB++){SI=m3[VB];R+=jL.sw$(SI)}
jL.fQ(S.ClassType)}
if(S.Variables.length>0){wI=S.Variables;var $tz;for(Ye=0,$tz=wI.length;Ye<$tz;Ye++){o7=wI[Ye];R+=jL.sw$(o7)}}
jj=S.Namespaces;var $t01;for(mE=0,$t01=jj.length;mE<$t01;mE++){ay=jj[mE];R+=jL.sw$(ay)}
return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var cP={$ClassName:"TAmbientConstructorDeclaration",$Parent:nx,$Init:function($){nx.$Init($);$.ParameterList=[]},sw:function(S){var R="";var Bn=0;R=jL.pT(S.ClassType)+"constructor Create";if(S.ParameterList.length>0){R+="(";var $t11;for(Bn=0,$t11=(S.ParameterList.length-1);Bn<$t11;Bn++){R+=bb.ow(S.ParameterList[Bn],false)+"; "}
R+=bb.ow(S.ParameterList[(S.ParameterList.length-1)],false)+")";R+=")"}
R+=";"+"\r\n";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var sQ={$ClassName:"TAmbientClassDeclaration",$Parent:jL,$Init:function($){jL.$Init($);$.Members=[];$.Name="";$.Extends=[]},sw:function(S){var R="";var KX=0;var fG=0,wd=0;var MQ=null,da=0;var MI=[];R+=jL.pT(S.ClassType)+"J"+S.Name+" = class external '"+S.Name+"'";if(S.Extends.length>0){R+="(";R+=jL.sw$(S.Extends[0]);var $t21;for(KX=0+1,$t21=S.Extends.length;KX<$t21;KX++){R+=", "+jL.sw$(S.Extends[KX])}
R+=")"}
R+="\r\n";fG=0;jL.wE(S.ClassType);MI=S.Members;var $t31;for(wd=0,$t31=MI.length;wd<$t31;wd++){MQ=MI[wd];da=($Is(MQ,br))?$As(MQ,br).Visibility:0;if(fG!=da){jL.fQ(S.ClassType);R+=jL.pT(S.ClassType);switch(da){case 0:R+="public"+"\r\n";break;case 1:R+="protected"+"\r\n";break;case 2:R+="private"+"\r\n";break}
jL.wE(S.ClassType);fG=da}
R+=jL.sw$(MQ)}
jL.fQ(S.ClassType);R+=jL.pT(S.ClassType)+"end;"+"\r\n"+"\r\n";return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var Iy={$ClassName:"TAmbientBinding",$Parent:FB,$Init:function($){FB.$Init($);$.Type=null},sw:function(S){var R="";R=S.Name+": "+jL.sw$(S.Type);return R},Destroy:TObject.Destroy,o6:jL.o6,sw$:function($){return $.ClassType.sw($)}};var Rgc=["amPublic","amPrivate","amProtected"];function lA(ZT,NG){var R=false;R=(!(ZT.Type!==null)!=!(ZT.Type!==null));if(R&&(ZT.Type!==null))R=jL.sw$(ZT.Type)==jL.sw$(NG.Type);return R};function aW(iX,kz){var R=false;R=(!(iX.Type!==null)!=!(iX.Type!==null));if(R&&(iX.Type!==null))R=jL.sw$(iX.Type)==jL.sw$(kz.Type);return R};function XE(kw){var R="";R=kw;if((["abstract","begin","class","const","constructor","default","div","end","exit","export","external","function","interface","label","method","object","private","property","protected","public","repeat","string","then","type","unit","uses"].indexOf((kw).toLowerCase())>=0))R="&"+R;if((["length","include","exclude"].indexOf((kw).toLowerCase())>=0))R="_"+R;return R};var i=null;var i=require("typescript");var EN=0;var qq=[];var C=[],DD="",a3="",mD=null;var mD=RD();C=process.argv;C.splice(0,2);if(C.length==0){return"Usage: ts2pas inputfile [outputfile]"}
DD=C[0];if(((DD).indexOf("https:\/\/github.com\\")>=0)){w1(StrAfter(DD,"https:\/\/github.com\\"))}else{a3=C[0]+".pas";if(C.length==2)a3=C[1];B7(DD,a3)}
